export type LipShape =
  | "spread"
  | "neutral"
  | "open"
  | "rounded"
  | "pursed"
  | "teeth-on-lip"
  | "closed"
  | "tongue-between-teeth";

export type TonguePosition =
  | "high-front"
  | "mid-front"
  | "low-front"
  | "central"
  | "high-back"
  | "mid-back"
  | "low-back"
  | "tip-between-teeth"
  | "tip-on-ridge"
  | "blade-on-palate"
  | "back-on-velum"
  | "retroflex-curl"
  | "glottal";

export type JawOpening = "narrow" | "medium" | "wide";

export interface PhonemeArticulationGuide {
  symbol: string;
  nameEs: string;
  category: "vowel" | "diphthong" | "consonant";
  voicing: "voiced" | "voiceless";
  mannerEs: string;
  placeEs: string;
  lipShape: LipShape;
  tonguePosition: TonguePosition;
  jawOpening: JawOpening;
  vocalCordsVibrate: boolean;
  visualCueEs: string;
}

export const ARTICULATION_GUIDE_MAP: Record<string, PhonemeArticulationGuide> = {
  // --- Vocales Frontales ---
  "/iː/": {
    symbol: "/iː/",
    nameEs: "i larga y tensa",
    category: "vowel",
    voicing: "voiced",
    mannerEs: "Vocal cerrada anterior (tensa)",
    placeEs: "Labios estirados, lengua alta al frente",
    lipShape: "spread",
    tonguePosition: "high-front",
    jawOpening: "narrow",
    vocalCordsVibrate: true,
    visualCueEs: "Sonrisa amplia: estira los labios hacia los lados y sube la parte delantera de la lengua cerca del paladar.",
  },
  "/ɪ/": {
    symbol: "/ɪ/",
    nameEs: "i corta y laxa",
    category: "vowel",
    voicing: "voiced",
    mannerEs: "Vocal semicerrada anterior (relajada)",
    placeEs: "Labios neutros, lengua relajada",
    lipShape: "neutral",
    tonguePosition: "mid-front",
    jawOpening: "narrow",
    vocalCordsVibrate: true,
    visualCueEs: "Boca relajada: no estires los labios, baja la mandíbula un milímetro respecto a /iː/.",
  },
  "/eɪ/": {
    symbol: "/eɪ/",
    nameEs: "Diptongo ey",
    category: "diphthong",
    voicing: "voiced",
    mannerEs: "Diptongo de cierre frontal",
    placeEs: "De media-frontal a alta",
    lipShape: "spread",
    tonguePosition: "mid-front",
    jawOpening: "medium",
    vocalCordsVibrate: true,
    visualCueEs: "Deslizamiento: empieza con la boca entreabierta en 'e' y desliza hacia la 'i' tensando los labios.",
  },
  "/ɛ/": {
    symbol: "/ɛ/",
    nameEs: "e abierta y corta",
    category: "vowel",
    voicing: "voiced",
    mannerEs: "Vocal semiabierta anterior",
    placeEs: "Mandíbula abierta, lengua media",
    lipShape: "neutral",
    tonguePosition: "mid-front",
    jawOpening: "medium",
    vocalCordsVibrate: true,
    visualCueEs: "Abre la mandíbula un poco más que para la 'e' española, manteniendo los labios relajados.",
  },
  "/æ/": {
    symbol: "/æ/",
    nameEs: "a frontal abierta (cat)",
    category: "vowel",
    voicing: "voiced",
    mannerEs: "Vocal abierta anterior",
    placeEs: "Boca muy abierta, lengua plana al frente",
    lipShape: "open",
    tonguePosition: "low-front",
    jawOpening: "wide",
    vocalCordsVibrate: true,
    visualCueEs: "Abre bien la mandíbula hacia abajo como si fueras a decir 'a', pero estira un poco los labios como para 'e'.",
  },

  // --- Vocales Centrales ---
  "/ə/": {
    symbol: "/ə/",
    nameEs: "Schwa (vocal neutra)",
    category: "vowel",
    voicing: "voiced",
    mannerEs: "Vocal central media (átona)",
    placeEs: "Músculos completamente relajados",
    lipShape: "neutral",
    tonguePosition: "central",
    jawOpening: "medium",
    vocalCordsVibrate: true,
    visualCueEs: "Cero esfuerzo: la lengua descansa en el centro de la boca, mandíbula ligeramente abierta.",
  },
  "/ʌ/": {
    symbol: "/ʌ/",
    nameEs: "a corta central (but)",
    category: "vowel",
    voicing: "voiced",
    mannerEs: "Vocal semiabierta posterior/central",
    placeEs: "Boca abierta, lengua baja y relajada",
    lipShape: "neutral",
    tonguePosition: "central",
    jawOpening: "medium",
    vocalCordsVibrate: true,
    visualCueEs: "Un golpe de voz corto y relajado desde el centro de la boca, mandíbula moderadamente caída.",
  },
  "/ɜːr/": {
    symbol: "/ɜːr/",
    nameEs: "Vocal r-coloreada (bird)",
    category: "vowel",
    voicing: "voiced",
    mannerEs: "Vocal central con resonancia r",
    placeEs: "Lengua retraída o curvada hacia atrás",
    lipShape: "neutral",
    tonguePosition: "retroflex-curl",
    jawOpening: "narrow",
    vocalCordsVibrate: true,
    visualCueEs: "Curva la punta de la lengua hacia atrás sin tocar el paladar mientras emites el sonido vocal.",
  },
  "/ɚ/": {
    symbol: "/ɚ/",
    nameEs: "Schwa r-coloreada (teacher)",
    category: "vowel",
    voicing: "voiced",
    mannerEs: "Vocal central átona r",
    placeEs: "Lengua relajada ligeramente curvada",
    lipShape: "neutral",
    tonguePosition: "retroflex-curl",
    jawOpening: "narrow",
    vocalCordsVibrate: true,
    visualCueEs: "Sonido 'er' suave al final de palabras, punta de la lengua levemente elevada.",
  },

  // --- Vocales Posteriores ---
  "/uː/": {
    symbol: "/uː/",
    nameEs: "u larga y tensa (boot)",
    category: "vowel",
    voicing: "voiced",
    mannerEs: "Vocal cerrada posterior (tensa)",
    placeEs: "Labios bien redondeados, lengua alta atrás",
    lipShape: "rounded",
    tonguePosition: "high-back",
    jawOpening: "narrow",
    vocalCordsVibrate: true,
    visualCueEs: "Forma un círculo pequeño y tenso con los labios (como para silbar) y eleva la parte posterior de la lengua.",
  },
  "/ʊ/": {
    symbol: "/ʊ/",
    nameEs: "u corta y laxa (book)",
    category: "vowel",
    voicing: "voiced",
    mannerEs: "Vocal semicerrada posterior (relajada)",
    placeEs: "Labios ligeramente redondeados y relajados",
    lipShape: "neutral",
    tonguePosition: "high-back",
    jawOpening: "narrow",
    vocalCordsVibrate: true,
    visualCueEs: "Labios apenas redondeados y flojos, mandíbula ligeramente más abierta que en /uː/.",
  },
  "/oʊ/": {
    symbol: "/oʊ/",
    nameEs: "Diptongo ou (boat)",
    category: "diphthong",
    voicing: "voiced",
    mannerEs: "Diptongo de cierre posterior",
    placeEs: "De media-posterior a redondeada cerrada",
    lipShape: "rounded",
    tonguePosition: "mid-back",
    jawOpening: "medium",
    vocalCordsVibrate: true,
    visualCueEs: "Empieza en 'o' redondeando los labios y ve cerrando el círculo hacia 'u'.",
  },
  "/ɔː/": {
    symbol: "/ɔː/",
    nameEs: "o abierta (law / thought)",
    category: "vowel",
    voicing: "voiced",
    mannerEs: "Vocal semiabierta posterior redondeada",
    placeEs: "Mandíbula baja, labios ovalados",
    lipShape: "rounded",
    tonguePosition: "low-back",
    jawOpening: "wide",
    vocalCordsVibrate: true,
    visualCueEs: "Abre la boca verticalmente en forma de óvalo con los labios ligeramente salientes.",
  },
  "/ɑː/": {
    symbol: "/ɑː/",
    nameEs: "a abierta posterior (father)",
    category: "vowel",
    voicing: "voiced",
    mannerEs: "Vocal abierta posterior no redondeada",
    placeEs: "Boca muy abierta, lengua plana en el fondo",
    lipShape: "open",
    tonguePosition: "low-back",
    jawOpening: "wide",
    vocalCordsVibrate: true,
    visualCueEs: "Boca muy abierta (como en el médico diciendo 'aah'), lengua plana y atrás.",
  },
  "/aɪ/": {
    symbol: "/aɪ/",
    nameEs: "Diptongo ai (bite)",
    category: "diphthong",
    voicing: "voiced",
    mannerEs: "Diptongo amplio de apertura a cierre",
    placeEs: "De abierta a cerrada frontal",
    lipShape: "spread",
    tonguePosition: "low-front",
    jawOpening: "wide",
    vocalCordsVibrate: true,
    visualCueEs: "Comienza con la mandíbula bien abierta ('a') y ciérrala estirando los labios en una sonrisa ('i').",
  },
  "/aʊ/": {
    symbol: "/aʊ/",
    nameEs: "Diptongo au (cow)",
    category: "diphthong",
    voicing: "voiced",
    mannerEs: "Diptongo amplio de apertura a cierre",
    placeEs: "De abierta a redondeada posterior",
    lipShape: "rounded",
    tonguePosition: "low-front",
    jawOpening: "wide",
    vocalCordsVibrate: true,
    visualCueEs: "Comienza con la mandíbula abierta ('a') y ciérrala redondeando los labios ('u').",
  },
  "/ɔɪ/": {
    symbol: "/ɔɪ/",
    nameEs: "Diptongo oi (boy)",
    category: "diphthong",
    voicing: "voiced",
    mannerEs: "Diptongo de cierre frontal",
    placeEs: "De redondeada posterior a estirada frontal",
    lipShape: "spread",
    tonguePosition: "mid-back",
    jawOpening: "medium",
    vocalCordsVibrate: true,
    visualCueEs: "Empieza con labios redondeados ('o') y muévelos rápidamente hacia una sonrisa ('i').",
  },

  // --- Consonantes: Fricativas Interdentales y Labiodentales ---
  "/θ/": {
    symbol: "/θ/",
    nameEs: "th sorda (think)",
    category: "consonant",
    voicing: "voiceless",
    mannerEs: "Fricativa interdental sorda",
    placeEs: "Punta de la lengua entre los dientes",
    lipShape: "tongue-between-teeth",
    tonguePosition: "tip-between-teeth",
    jawOpening: "narrow",
    vocalCordsVibrate: false,
    visualCueEs: "Saca suavemente la punta de la lengua entre los dientes incisivos y expulsa aire continuo sin usar la voz.",
  },
  "/ð/": {
    symbol: "/ð/",
    nameEs: "th sonora (this, the)",
    category: "consonant",
    voicing: "voiced",
    mannerEs: "Fricativa interdental sonora",
    placeEs: "Lengua entre dientes con vibración",
    lipShape: "tongue-between-teeth",
    tonguePosition: "tip-between-teeth",
    jawOpening: "narrow",
    vocalCordsVibrate: true,
    visualCueEs: "Misma posición que /θ/ (lengua entre los dientes), pero haciendo vibrar las cuerdas vocales (siente un cosquilleo).",
  },
  "/f/": {
    symbol: "/f/",
    nameEs: "f (fish)",
    category: "consonant",
    voicing: "voiceless",
    mannerEs: "Fricativa labiodental sorda",
    placeEs: "Dientes superiores sobre labio inferior",
    lipShape: "teeth-on-lip",
    tonguePosition: "central",
    jawOpening: "narrow",
    vocalCordsVibrate: false,
    visualCueEs: "Apoya suavemente el borde de los dientes superiores sobre la parte interna del labio inferior y sopla.",
  },
  "/v/": {
    symbol: "/v/",
    nameEs: "v sonora (voice, very)",
    category: "consonant",
    voicing: "voiced",
    mannerEs: "Fricativa labiodental sonora",
    placeEs: "Dientes superiores sobre labio inferior + voz",
    lipShape: "teeth-on-lip",
    tonguePosition: "central",
    jawOpening: "narrow",
    vocalCordsVibrate: true,
    visualCueEs: "Dientes sobre el labio inferior igual que en /f/, pero emitiendo voz continua con fuerte vibración.",
  },

  // --- Consonantes: Alveolares y Post-alveolares ---
  "/s/": {
    symbol: "/s/",
    nameEs: "s sorda (see)",
    category: "consonant",
    voicing: "voiceless",
    mannerEs: "Fricativa alveolar sorda",
    placeEs: "Dientes casi cerrados, aire silbante",
    lipShape: "neutral",
    tonguePosition: "tip-on-ridge",
    jawOpening: "narrow",
    vocalCordsVibrate: false,
    visualCueEs: "Dientes casi juntos; la lengua apunta a la encía superior creando un canal estrecho para el aire.",
  },
  "/z/": {
    symbol: "/z/",
    nameEs: "z sonora (zoo, busy)",
    category: "consonant",
    voicing: "voiced",
    mannerEs: "Fricativa alveolar sonora",
    placeEs: "Zumbido de abeja con dientes juntos",
    lipShape: "neutral",
    tonguePosition: "tip-on-ridge",
    jawOpening: "narrow",
    vocalCordsVibrate: true,
    visualCueEs: "Haz el sonido de una abeja 'zzzz': misma posición de /s/ pero con vibración potente en la garganta.",
  },
  "/ʃ/": {
    symbol: "/ʃ/",
    nameEs: "sh (shoe, ship)",
    category: "consonant",
    voicing: "voiceless",
    mannerEs: "Fricativa postalveolar sorda",
    placeEs: "Labios ligeramente trompeta, aire suave",
    lipShape: "pursed",
    tonguePosition: "blade-on-palate",
    jawOpening: "narrow",
    vocalCordsVibrate: false,
    visualCueEs: "Como pidiendo silencio 'shhh': proyecta los labios hacia adelante y eleva el cuerpo de la lengua.",
  },
  "/ʒ/": {
    symbol: "/ʒ/",
    nameEs: "zh sonora (vision, measure)",
    category: "consonant",
    voicing: "voiced",
    mannerEs: "Fricativa postalveolar sonora",
    placeEs: "Labios proyectados con vibración",
    lipShape: "pursed",
    tonguePosition: "blade-on-palate",
    jawOpening: "narrow",
    vocalCordsVibrate: true,
    visualCueEs: "Misma boca que /ʃ/ ('shhh'), pero activando la voz para crear un zumbido denso.",
  },
  "/tʃ/": {
    symbol: "/tʃ/",
    nameEs: "ch (cheese, match)",
    category: "consonant",
    voicing: "voiceless",
    mannerEs: "Africada postalveolar sorda",
    placeEs: "Bloqueo 't' + liberación 'sh'",
    lipShape: "pursed",
    tonguePosition: "blade-on-palate",
    jawOpening: "narrow",
    vocalCordsVibrate: false,
    visualCueEs: "Bloquea el aire con la lengua en la encía superior y suéltalo explosivamente en un sonido 'ch'.",
  },
  "/dʒ/": {
    symbol: "/dʒ/",
    nameEs: "j inglesa (jump, bridge)",
    category: "consonant",
    voicing: "voiced",
    mannerEs: "Africada postalveolar sonora",
    placeEs: "Bloqueo 'd' + liberación sonora",
    lipShape: "pursed",
    tonguePosition: "blade-on-palate",
    jawOpening: "narrow",
    vocalCordsVibrate: true,
    visualCueEs: "Explosión con voz: bloquea como para 'd' y libera con fuerza el sonido 'j' enérgico.",
  },

  // --- Oclusivas (Stops) ---
  "/p/": {
    symbol: "/p/",
    nameEs: "p (pen)",
    category: "consonant",
    voicing: "voiceless",
    mannerEs: "Oclusiva bilabial sorda",
    placeEs: "Ambos labios cerrados + explosión",
    lipShape: "closed",
    tonguePosition: "central",
    jawOpening: "narrow",
    vocalCordsVibrate: false,
    visualCueEs: "Junta ambos labios firmemente, acumula presión de aire y suéltala de golpe con una pequeña bocanada.",
  },
  "/b/": {
    symbol: "/b/",
    nameEs: "b (book)",
    category: "consonant",
    voicing: "voiced",
    mannerEs: "Oclusiva bilabial sonora",
    placeEs: "Labios cerrados + vibración vocal",
    lipShape: "closed",
    tonguePosition: "central",
    jawOpening: "narrow",
    vocalCordsVibrate: true,
    visualCueEs: "Junta los labios y libéralos inmediatamente haciendo vibrar las cuerdas vocales desde el primer instante.",
  },
  "/t/": {
    symbol: "/t/",
    nameEs: "t aspirada (tea)",
    category: "consonant",
    voicing: "voiceless",
    mannerEs: "Oclusiva alveolar sorda",
    placeEs: "Punta de lengua en encía superior",
    lipShape: "neutral",
    tonguePosition: "tip-on-ridge",
    jawOpening: "narrow",
    vocalCordsVibrate: false,
    visualCueEs: "Punta de la lengua en la encía superior (no en los dientes como en español); suelta con golpe de aire.",
  },
  "/d/": {
    symbol: "/d/",
    nameEs: "d (door)",
    category: "consonant",
    voicing: "voiced",
    mannerEs: "Oclusiva alveolar sonora",
    placeEs: "Punta de lengua en encía + voz",
    lipShape: "neutral",
    tonguePosition: "tip-on-ridge",
    jawOpening: "narrow",
    vocalCordsVibrate: true,
    visualCueEs: "Presiona la punta de la lengua en la encía superior y suéltala con sonido de voz.",
  },
  "/k/": {
    symbol: "/k/",
    nameEs: "k (cat, key)",
    category: "consonant",
    voicing: "voiceless",
    mannerEs: "Oclusiva velar sorda",
    placeEs: "Parte trasera de la lengua en el velo",
    lipShape: "neutral",
    tonguePosition: "back-on-velum",
    jawOpening: "medium",
    vocalCordsVibrate: false,
    visualCueEs: "Sella el paladar blando con la parte posterior de la lengua y suelta con un golpe de aire seco.",
  },
  "/ɡ/": {
    symbol: "/ɡ/",
    nameEs: "g (go, get)",
    category: "consonant",
    voicing: "voiced",
    mannerEs: "Oclusiva velar sonora",
    placeEs: "Parte trasera de la lengua + voz",
    lipShape: "neutral",
    tonguePosition: "back-on-velum",
    jawOpening: "medium",
    vocalCordsVibrate: true,
    visualCueEs: "Misma posición de /k/, pero soltando con resonancia de voz en la garganta.",
  },

  // --- Nasales, Líquidas y Aproximantes ---
  "/m/": {
    symbol: "/m/",
    nameEs: "m (man)",
    category: "consonant",
    voicing: "voiced",
    mannerEs: "Nasal bilabial sonora",
    placeEs: "Labios cerrados, aire por la nariz",
    lipShape: "closed",
    tonguePosition: "central",
    jawOpening: "narrow",
    vocalCordsVibrate: true,
    visualCueEs: "Labios juntos, cuerdas vocales vibrando y el aire saliendo libremente por la nariz.",
  },
  "/n/": {
    symbol: "/n/",
    nameEs: "n (no)",
    category: "consonant",
    voicing: "voiced",
    mannerEs: "Nasal alveolar sonora",
    placeEs: "Lengua en encía superior, aire nasal",
    lipShape: "neutral",
    tonguePosition: "tip-on-ridge",
    jawOpening: "narrow",
    vocalCordsVibrate: true,
    visualCueEs: "Sella la encía superior con la punta de la lengua y deja resonar el aire en la cavidad nasal.",
  },
  "/ŋ/": {
    symbol: "/ŋ/",
    nameEs: "ng nasal (sing, ring)",
    category: "consonant",
    voicing: "voiced",
    mannerEs: "Nasal velar sonora",
    placeEs: "Lengua sellando el velo, aire nasal",
    lipShape: "neutral",
    tonguePosition: "back-on-velum",
    jawOpening: "medium",
    vocalCordsVibrate: true,
    visualCueEs: "Eleva la parte trasera de la lengua para bloquear la boca; el sonido resuena exclusivamente por la nariz.",
  },
  "/l/": {
    symbol: "/l/",
    nameEs: "l (light, ball)",
    category: "consonant",
    voicing: "voiced",
    mannerEs: "Aproximante lateral alveolar",
    placeEs: "Punta de lengua en encía, aire lateral",
    lipShape: "neutral",
    tonguePosition: "tip-on-ridge",
    jawOpening: "narrow",
    vocalCordsVibrate: true,
    visualCueEs: "Punta de la lengua apoyada en el centro de la encía superior; el aire fluye libre por ambos lados.",
  },
  "/ɹ/": {
    symbol: "/ɹ/",
    nameEs: "r americana (red, run)",
    category: "consonant",
    voicing: "voiced",
    mannerEs: "Aproximante postalveolar / retrofleja",
    placeEs: "Lengua curvada atrás sin tocar el paladar",
    lipShape: "pursed",
    tonguePosition: "retroflex-curl",
    jawOpening: "narrow",
    vocalCordsVibrate: true,
    visualCueEs: "¡Nunca vibres la punta de la lengua! Enróllala ligeramente hacia atrás en el centro de la boca sin tocar nada.",
  },
  "/w/": {
    symbol: "/w/",
    nameEs: "w (water, win)",
    category: "consonant",
    voicing: "voiced",
    mannerEs: "Aproximante labiovelar sonora",
    placeEs: "Labios en círculo estrecho + dorso alto",
    lipShape: "rounded",
    tonguePosition: "high-back",
    jawOpening: "narrow",
    vocalCordsVibrate: true,
    visualCueEs: "Redondea los labios hacia afuera como para silbar y deslízalos rápidamente hacia la vocal siguiente.",
  },
  "/j/": {
    symbol: "/j/",
    nameEs: "y de yes (yes, you)",
    category: "consonant",
    voicing: "voiced",
    mannerEs: "Aproximante palatal sonora",
    placeEs: "Lengua alta al frente hacia el paladar",
    lipShape: "spread",
    tonguePosition: "high-front",
    jawOpening: "narrow",
    vocalCordsVibrate: true,
    visualCueEs: "Empieza con la lengua casi tocando el paladar duro en posición de 'i' y deslízala suavemente hacia la vocal.",
  },
  "/h/": {
    symbol: "/h/",
    nameEs: "h aspirada (hat, house)",
    category: "consonant",
    voicing: "voiceless",
    mannerEs: "Fricativa glotal sorda",
    placeEs: "Soplo suave desde la garganta",
    lipShape: "neutral",
    tonguePosition: "glottal",
    jawOpening: "medium",
    vocalCordsVibrate: false,
    visualCueEs: "Un suspiro o soplo cálido desde la garganta (como empañando un espejo), sin carraspear como la 'j' española.",
  },
};

/** Normalizes any input format like "/iː/", "iː", "/i/", "i" to canonical key. */
export function getArticulationGuide(symbolOrIpa: string): PhonemeArticulationGuide | null {
  const trimmed = symbolOrIpa.trim();
  const withSlashes = trimmed.startsWith("/") && trimmed.endsWith("/") ? trimmed : `/${trimmed.replace(/^\/|\/$/g, "")}/`;

  if (ARTICULATION_GUIDE_MAP[withSlashes]) {
    return ARTICULATION_GUIDE_MAP[withSlashes];
  }

  // Fallback match without length marks or colons
  const stripped = withSlashes.replace(/ː/g, "");
  for (const [key, val] of Object.entries(ARTICULATION_GUIDE_MAP)) {
    if (key.replace(/ː/g, "") === stripped) {
      return val;
    }
  }

  return null;
}
