/**
 * High-frequency English irregulars (A2-B1). base → every accepted surface form
 * (including the base). Consulted before suffix rules in variant expansion so
 * irregular targets aren't spuriously rejected by word-boundary matching.
 * Not exhaustive — covers the ~150 forms a learner at this level actually meets.
 */
export const IRREGULAR_FORMS: Record<string, string[]> = {
  go: ['go', 'goes', 'went', 'gone', 'going'],
  buy: ['buy', 'buys', 'bought', 'buying'],
  run: ['run', 'runs', 'ran', 'running'],
  child: ['child', 'children'],
  person: ['person', 'people'],
  man: ['man', 'men'],
  woman: ['woman', 'women'],
  foot: ['foot', 'feet'],
  tooth: ['tooth', 'teeth'],
  be: ['be', 'is', 'am', 'are', 'was', 'were', 'been', 'being'],
  have: ['have', 'has', 'had', 'having'],
  do: ['do', 'does', 'did', 'done', 'doing'],
  say: ['say', 'says', 'said', 'saying'],
  make: ['make', 'makes', 'made', 'making'],
  take: ['take', 'takes', 'took', 'taken', 'taking'],
  come: ['come', 'comes', 'came', 'coming'],
  see: ['see', 'sees', 'saw', 'seen', 'seeing'],
  know: ['know', 'knows', 'knew', 'known', 'knowing'],
  get: ['get', 'gets', 'got', 'gotten', 'getting'],
  give: ['give', 'gives', 'gave', 'given', 'giving'],
  find: ['find', 'finds', 'found', 'finding'],
  think: ['think', 'thinks', 'thought', 'thinking'],
  tell: ['tell', 'tells', 'told', 'telling'],
  become: ['become', 'becomes', 'became', 'becoming'],
  leave: ['leave', 'leaves', 'left', 'leaving'],
  feel: ['feel', 'feels', 'felt', 'feeling'],
  bring: ['bring', 'brings', 'brought', 'bringing'],
  begin: ['begin', 'begins', 'began', 'begun', 'beginning'],
  keep: ['keep', 'keeps', 'kept', 'keeping'],
  hold: ['hold', 'holds', 'held', 'holding'],
  write: ['write', 'writes', 'wrote', 'written', 'writing'],
  stand: ['stand', 'stands', 'stood', 'standing'],
  hear: ['hear', 'hears', 'heard', 'hearing'],
  let: ['let', 'lets', 'letting'],
  mean: ['mean', 'means', 'meant', 'meaning'],
  meet: ['meet', 'meets', 'met', 'meeting'],
  pay: ['pay', 'pays', 'paid', 'paying'],
  sit: ['sit', 'sits', 'sat', 'sitting'],
  speak: ['speak', 'speaks', 'spoke', 'spoken', 'speaking'],
  lose: ['lose', 'loses', 'lost', 'losing'],
  send: ['send', 'sends', 'sent', 'sending'],
  build: ['build', 'builds', 'built', 'building'],
  understand: ['understand', 'understands', 'understood', 'understanding'],
  draw: ['draw', 'draws', 'drew', 'drawn', 'drawing'],
  break: ['break', 'breaks', 'broke', 'broken', 'breaking'],
  eat: ['eat', 'eats', 'ate', 'eaten', 'eating'],
  fall: ['fall', 'falls', 'fell', 'fallen', 'falling'],
  drive: ['drive', 'drives', 'drove', 'driven', 'driving'],
  read: ['read', 'reads', 'reading'],
  wear: ['wear', 'wears', 'wore', 'worn', 'wearing'],
  sleep: ['sleep', 'sleeps', 'slept', 'sleeping'],
  win: ['win', 'wins', 'won', 'winning'],
  sing: ['sing', 'sings', 'sang', 'sung', 'singing'],
  swim: ['swim', 'swims', 'swam', 'swum', 'swimming'],
  fly: ['fly', 'flies', 'flew', 'flown', 'flying'],
  catch: ['catch', 'catches', 'caught', 'catching'],
  teach: ['teach', 'teaches', 'taught', 'teaching'],
  // …extend toward ~150 high-frequency A2-B1 forms as content grows.
}
