/**
 * Canonical full titles for standalone grammar and chunk decks that are not
 * embedded directly in COURSE_PATH_CURRICULUM levels.
 *
 * Generated from authored deck meta ({title} + {titleEmphasis}).
 */
export const STANDALONE_DECK_TITLES: Record<string, string> = {
  "biz-code-review": "Inglés para code review",
  "biz-conversaciones-trabajo": "Conversaciones de negocios",
  "biz-desarrollo-profesional": "Desarrollo profesional",
  "biz-elementos-trabajo": "Elementos de trabajo",
  "biz-entrevistas-trabajo": "Inglés para entrevistas",
  "biz-expresiones-idiomaticas-negocios": "Expresiones idiomáticas de negocios",
  "biz-negocios-managers": "Negocios para managers",
  "biz-viajes-negocios": "Viajes de negocios",
  "biz-vocabulario-trabajo": "Vocabulario para el trabajo",
  "chunk-300-english-from-day-1": "300 Chunks to Speak English From Day 1",
  "chunk-basico-vs-natural-1": "Básico vs natural: Ánimo y Opiniones",
  "chunk-basico-vs-natural-2": "Básico vs natural: Decisiones y Contacto",
  "chunk-basico-vs-natural-3": "Básico vs natural: Trabajo y Tiempo",
  "chunk-basico-vs-natural-4": "Básico vs natural: Dinero y Retos",
  "chunk-basico-vs-natural-5": "Básico vs natural: Reacciones y Cierres",
  "chunk-collocations": "Colocaciones naturales en inglés",
  "chunk-daily-standup": "Tu Daily Standup en inglés",
  "chunk-discourse-markers": "Marcadores del discurso y conectores",
  "chunk-expresiones-clave-1": "Expresiones clave del día a día (Parte 1)",
  "chunk-expresiones-clave-2": "Expresiones clave del día a día (Parte 2)",
  "chunk-expresiones-multiuso": "Verbos con usos figurados",
  "chunk-hablar-de-mi": "Hablar de mí con soltura",
  "chunk-idioms": "Modismos y expresiones idiomáticas",
  "chunk-language-functions": "Funciones comunicativas con tacto",
  "chunk-light-verbs-get-set-put-go": "Light Verbs: Get, Set, Put y Go",
  "chunk-palabras-doble-significado": "Palabras con doble significado",
  "chunk-phrasal-verbs": "Phrasal Verbs de uso diario",
  "chunk-programacion": "Chunks de programación",
  "chunk-sentence-frames": "Plantillas de oraciones (Sentence Frames)",
  "chunk-social-small-talk": "Small Talk y conexión social",
  "chunk-speaking-frameworks": "Frameworks para hablar sin traducir",
  "chunk-the-9-verbs-strategy": "La estrategia de los 9 verbos ligeros",
  "chunk-ux-ui": "Chunks de diseño UX y UI",
  "chunk-vida-cotidiana": "Chunks para la vida cotidiana",
  "cs-assimilation": "Habla conectada: asimilación",
  "cs-elision": "Habla conectada: elisión",
  "cs-linking": "Habla conectada: enlace de sonidos",
  "cs-reductions": "Habla conectada: reducciones",
  "ff-comunicacion-argumentacion": "Falsos amigos en comunicación y estudio",
  "ff-esenciales-a1-a2": "Falsos amigos esenciales",
  "ff-trabajo-negocios": "Falsos amigos en el trabajo y oficina",
  "ff-vida-cotidiana": "Falsos amigos en la vida cotidiana",
  "tech-ingles-chatgpt": "Inglés práctico con ChatGPT",
  "tech-ingles-ciberseguridad": "Inglés para ciberseguridad",
  "tech-ingles-inteligencia-artificial": "Inglés para inteligencia artificial",
  "tech-ingles-marketing": "Inglés para marketing",
  "tech-ingles-programadores": "Inglés para programadores",
  "tech-ingles-servicio-cliente": "Servicio al cliente",
  "tech-ingles-startups": "Inglés para startups",
  "tech-ingles-ventas": "Inglés para ventas",
  "tech-preparacion-ielts": "Preparación IELTS",
  "tech-preparacion-toefl": "Preparación TOEFL",
  "the-add-on-strategy": "The Add-On Strategy Trees vs. Trains",
};
