"use client";

import type { WordCategoryIndex } from "./domain-profile";

// public/lexicon/word-index.json: `{ wordId: categoryId[] }`, generated by
// scripts/build-lexicon-word-index.mjs. A static asset fetch, not an API
// call — no auth, cacheable, ~24KB. This is the client-side counterpart to
// lib/lexicon/categories.ts, which uses `fs` and cannot run in the browser.

let cached: Promise<WordCategoryIndex> | null = null;

/** Fetches and caches (module-lifetime) the word-id -> category-id index. */
export function getWordCategoryIndex(): Promise<WordCategoryIndex> {
  if (!cached) {
    cached = fetch("/lexicon/word-index.json")
      .then((res) => {
        if (!res.ok) throw new Error(`word-index.json ${res.status}`);
        return res.json() as Promise<Record<string, string[]>>;
      })
      .then((raw) => new Map(Object.entries(raw)))
      .catch(() => new Map<string, string[]>());
  }
  return cached;
}
