// Client-side loader for the slim per-level index (public/core-1000/level-index.json).
//
// Rendering per-CEFR-level progress needs only `word` and `cefr_level`, so this
// fetches a ~45KB projection instead of the ~932KB full dataset. Falls back to
// the full dataset if the index is missing, so an un-regenerated deploy degrades
// instead of breaking.
//
// Generated by scripts/core-1000/generate-level-index.mjs.

import { z } from "zod";
import { fetchCoreWords } from "./client";
import { CEFR_LEVELS, type CefrLevel } from "./types";
import type { LevelTallyWord } from "./level-progress";

let cache: LevelTallyWord[] | null = null;
let pending: Promise<LevelTallyWord[]> | null = null;

const LevelIndexSchema = z.object({
  version: z.literal(1),
  entries: z.array(z.tuple([z.string(), z.enum(CEFR_LEVELS as readonly [CefrLevel, ...CefrLevel[]])])).nonempty(),
});

async function loadIndex(): Promise<LevelTallyWord[] | null> {
  const res = await fetch("/core-1000/level-index.json");
  if (res.status === 404) return null;
  if (!res.ok) {
    throw new Error(`[core-1000] level index returned ${res.status}`);
  }

  const parsed = LevelIndexSchema.safeParse(await res.json());
  if (!parsed.success) {
    console.error("[core-1000] invalid level index", parsed.error);
    return null;
  }

  return parsed.data.entries.map(([word, cefr_level]) => ({ word, cefr_level }));
}

/**
 * Words projected to the fields per-level tallying needs. Prefers the slim
 * index; falls back to the full dataset when it is absent or malformed.
 */
export async function fetchLevelIndex(): Promise<LevelTallyWord[]> {
  if (cache) return cache;
  if (pending) return pending;

  pending = (async () => {
    const words = (await loadIndex()) ?? (await fetchCoreWords());
    cache = words;
    return words;
  })().finally(() => {
    pending = null;
  });

  return pending;
}

/** Solo para tests. */
export function __resetLevelIndexCache(): void {
  cache = null;
  pending = null;
}
