import { LegalPage } from "@/components/legal/LegalPage";

export const metadata = {
  title: "Terms of Service — English Journal",
  description: "Terms for using English Journal.",
};

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" updated="June 20, 2026">
      <p>
        By using English Journal (Pronunciation Journal), you agree to these
        terms. The app is a free, personal learning project — not a commercial
        service.
      </p>

      <h2 className="md-h2">The service</h2>
      <p>
        English Journal helps you practice English pronunciation, vocabulary, and
        grammar. Features may change, break, or be removed at any time as the
        project evolves. There is no paid tier and no guarantee of uptime.
      </p>

      <h2 className="md-h2">Your account</h2>
      <ul>
        <li>You are responsible for activity on your account.</li>
        <li>Do not share your credentials or misuse sign-in features.</li>
        <li>
          You may use guest mode without an account; progress may be stored only
          on your device.
        </li>
      </ul>

      <h2 className="md-h2">Acceptable use</h2>
      <p>Please do not:</p>
      <ul>
        <li>Attempt to break, scrape, or overload the app or its APIs.</li>
        <li>Use the app for unlawful purposes.</li>
        <li>Submit abusive, harmful, or misleading content through AI features.</li>
      </ul>

      <h2 className="md-h2">AI-generated content</h2>
      <p>
        Some exercises and feedback are generated by AI (Google Gemini). AI
        output may be inaccurate. Use it as a study aid, not as professional
        language instruction or certified assessment.
      </p>

      <h2 className="md-h2">Disclaimer</h2>
      <p>
        English Journal is provided &quot;as is&quot; without warranties of any
        kind. The operator is not liable for any loss or damage arising from use
        of the app, including data loss, service interruptions, or reliance on
        AI-generated content.
      </p>

      <h2 className="md-h2">Intellectual property</h2>
      <p>
        The app, its design, and original content belong to the project owner.
        Lesson content, audio, and third-party assets remain subject to their
        respective licenses. You may not copy or redistribute the app for
        commercial purposes without permission.
      </p>

      <h2 className="md-h2">Termination</h2>
      <p>
        You may stop using the app at any time. The operator may suspend or
        remove access if these terms are violated or if the project is
        discontinued.
      </p>

      <h2 className="md-h2">Contact</h2>
      <p>
        Questions about these terms? Email{" "}
        <a href="mailto:karlavagraze@gmail.com">karlavagraze@gmail.com</a>.
      </p>

      <p>
        See also our <a href="/privacy">Privacy Policy</a>.
      </p>
    </LegalPage>
  );
}
