// miniLessons.ts
// 50 mini lessons for English Journal — Basic → Advanced
// Each lesson maps to a day (1–50), but you can rotate by date or user progress.

export type LessonLevel = "basic" | "intermediate" | "advanced";
export type LessonCategory =
  | "pronunciation"
  | "grammar"
  | "vocabulary"
  | "listening"
  | "speaking"
  | "writing"
  | "idioms"
  | "collocations";

export interface MiniLesson {
  id: number;
  slug: string;
  level: LessonLevel;
  category: LessonCategory;
  duration: number; // minutes
  title: string;
  subtitle: string;
  body: string;
  examples: { word: string; ipa?: string; translation?: string }[];
  tip?: string;
  href: string;
}

export const miniLessons: MiniLesson[] = [
  // ─── BASIC (1–18) ───────────────────────────────────────────────────────────
  {
    id: 1,
    slug: "schwa-sound",
    level: "basic",
    category: "pronunciation",
    duration: 5,
    title: "When to use the schwa /ə/",
    subtitle: "Theory of the day",
    body: "The most common vowel sound in English. It appears in unstressed syllables — mastering it is the single biggest unlock for sounding natural.",
    examples: [
      { word: "banana", ipa: "/bəˈnɑː.nə/", translation: "plátano" },
      { word: "about", ipa: "/əˈbaʊt/", translation: "sobre, acerca de" },
    ],
    tip: "If a syllable isn't stressed, try replacing its vowel with /ə/ — you'll often be right.",
    href: "/courses/schwa-sound",
  },
  {
    id: 2,
    slug: "present-simple-vs-continuous",
    level: "basic",
    category: "grammar",
    duration: 5,
    title: "Present Simple vs. Present Continuous",
    subtitle: "Grammar of the day",
    body: "Use Present Simple for habits and facts. Use Present Continuous for actions happening right now or temporary situations.",
    examples: [
      { word: "I drink coffee every morning.", translation: "hábito" },
      { word: "I'm drinking coffee right now.", translation: "en este momento" },
    ],
    tip: "Stative verbs (know, like, believe) almost never use the continuous form.",
    href: "/courses/present-simple-continuous",
  },
  {
    id: 3,
    slug: "silent-letters",
    level: "basic",
    category: "pronunciation",
    duration: 4,
    title: "Silent letters you're probably pronouncing",
    subtitle: "Pronunciation of the day",
    body: "English is full of letters that are written but never spoken. These silent letters are relics of older pronunciations.",
    examples: [
      { word: "knife", ipa: "/naɪf/", translation: "cuchillo — la K es muda" },
      { word: "island", ipa: "/ˈaɪ.lənd/", translation: "isla — la S es muda" },
      { word: "know", ipa: "/noʊ/", translation: "saber — la K es muda" },
    ],
    href: "/courses/silent-letters",
  },
  {
    id: 4,
    slug: "articles-a-an-the",
    level: "basic",
    category: "grammar",
    duration: 5,
    title: "A, An, The — when to use each",
    subtitle: "Grammar of the day",
    body: "Use 'a/an' when introducing something for the first time or when it's one of many. Use 'the' when both speaker and listener know which one you mean.",
    examples: [
      { word: "I saw a dog. The dog was huge.", translation: "primera mención → referencia conocida" },
      { word: "She's a doctor.", translation: "profesión — no usamos 'the'" },
    ],
    href: "/courses/articles",
  },
  {
    id: 5,
    slug: "common-contractions",
    level: "basic",
    category: "speaking",
    duration: 4,
    title: "Contractions: sound more natural instantly",
    subtitle: "Speaking of the day",
    body: "Native speakers almost always use contractions in spoken English. Avoiding them makes you sound stiff or overly formal.",
    examples: [
      { word: "I am → I'm", ipa: "/aɪm/" },
      { word: "do not → don't", ipa: "/doʊnt/" },
      { word: "they are → they're", ipa: "/ðɛr/" },
    ],
    href: "/courses/contractions",
  },
  {
    id: 6,
    slug: "th-sounds",
    level: "basic",
    category: "pronunciation",
    duration: 5,
    title: "Voiced vs. voiceless /θ/ and /ð/",
    subtitle: "Pronunciation of the day",
    body: "English has two 'th' sounds. Both require the tongue between or just behind the teeth — the difference is whether you vibrate your vocal cords.",
    examples: [
      { word: "think", ipa: "/θɪŋk/", translation: "voiceless — sin vibración" },
      { word: "this", ipa: "/ðɪs/", translation: "voiced — con vibración" },
      { word: "bath / bathe", ipa: "/bæθ/ · /beɪð/", translation: "par mínimo" },
    ],
    href: "/courses/th-sounds",
  },
  {
    id: 7,
    slug: "countable-uncountable",
    level: "basic",
    category: "grammar",
    duration: 5,
    title: "Countable vs. uncountable nouns",
    subtitle: "Grammar of the day",
    body: "Countable nouns can be counted and have a plural form. Uncountable nouns are treated as a mass and take singular verbs.",
    examples: [
      { word: "apple → apples", translation: "contable" },
      { word: "water, information, advice", translation: "incontable — no decimos 'an advice'" },
    ],
    tip: "When in doubt, ask: can I say 'one ___'? If yes, it's countable.",
    href: "/courses/countable-uncountable",
  },
  {
    id: 8,
    slug: "linking-words-basic",
    level: "basic",
    category: "writing",
    duration: 4,
    title: "Linking words: and, but, so, because",
    subtitle: "Writing of the day",
    body: "These four connectors are the backbone of basic English sentences. Knowing when to use each prevents run-ons and choppy writing.",
    examples: [
      { word: "I was tired, but I finished the task.", translation: "contraste" },
      { word: "It rained, so we stayed inside.", translation: "resultado" },
    ],
    href: "/courses/linking-words-basic",
  },
  {
    id: 9,
    slug: "question-tags",
    level: "basic",
    category: "speaking",
    duration: 5,
    title: "Question tags: isn't it? didn't you?",
    subtitle: "Speaking of the day",
    body: "Question tags are mini questions added to the end of a statement to confirm or check information. They're extremely common in British English.",
    examples: [
      { word: "It's cold, isn't it?", translation: "confirmar algo que crees que es verdad" },
      { word: "You didn't call, did you?", translation: "confirmar algo negativo" },
    ],
    tip: "Positive statement → negative tag. Negative statement → positive tag.",
    href: "/courses/question-tags",
  },
  {
    id: 10,
    slug: "word-stress-basics",
    level: "basic",
    category: "pronunciation",
    duration: 5,
    title: "Word stress: which syllable is louder?",
    subtitle: "Pronunciation of the day",
    body: "English is a stress-timed language. Getting word stress wrong can make you harder to understand, even if every sound is correct.",
    examples: [
      { word: "PHOtograph · phoTOgraphy · photoGRAPHic", ipa: "el acento cambia con el sufijo" },
      { word: "PREsent (n.) · preSENT (v.)", translation: "mismo spelling, diferente significado" },
    ],
    href: "/courses/word-stress",
  },
  {
    id: 11,
    slug: "past-simple-irregular",
    level: "basic",
    category: "grammar",
    duration: 5,
    title: "Irregular past tense verbs",
    subtitle: "Grammar of the day",
    body: "The 50 most common English verbs are irregular in the past tense. There's no shortcut — but there are patterns to spot.",
    examples: [
      { word: "go → went · come → came · see → saw" },
      { word: "buy → bought · think → thought · bring → brought", translation: "grupo '-ought'" },
    ],
    href: "/courses/irregular-past",
  },
  {
    id: 12,
    slug: "prepositions-time",
    level: "basic",
    category: "grammar",
    duration: 4,
    title: "In, On, At — prepositions of time",
    subtitle: "Grammar of the day",
    body: "These three prepositions follow a simple rule based on how specific the time reference is.",
    examples: [
      { word: "in 2024 · in March · in the morning", translation: "períodos largos" },
      { word: "on Monday · on my birthday", translation: "días y fechas específicas" },
      { word: "at 3pm · at midnight · at noon", translation: "horas exactas" },
    ],
    href: "/courses/prepositions-time",
  },
  {
    id: 13,
    slug: "some-any",
    level: "basic",
    category: "grammar",
    duration: 4,
    title: "Some vs. Any",
    subtitle: "Grammar of the day",
    body: "Use 'some' in affirmative sentences and offers. Use 'any' in questions and negatives — though there are exceptions worth knowing.",
    examples: [
      { word: "I have some milk.", translation: "afirmativo" },
      { word: "Do you have any questions?", translation: "pregunta" },
      { word: "Would you like some coffee?", translation: "oferta — usamos 'some'" },
    ],
    href: "/courses/some-any",
  },
  {
    id: 14,
    slug: "basic-phrasal-verbs",
    level: "basic",
    category: "vocabulary",
    duration: 5,
    title: "5 essential phrasal verbs",
    subtitle: "Vocabulary of the day",
    body: "Phrasal verbs are verb + particle combinations that mean something different from the literal words. These 5 appear every day.",
    examples: [
      { word: "give up", translation: "rendirse" },
      { word: "find out", translation: "descubrir" },
      { word: "look up", translation: "buscar (en diccionario/internet)" },
      { word: "turn off", translation: "apagar" },
      { word: "run out of", translation: "quedarse sin algo" },
    ],
    href: "/courses/basic-phrasal-verbs",
  },
  {
    id: 15,
    slug: "modal-verbs-ability",
    level: "basic",
    category: "grammar",
    duration: 5,
    title: "Can, Could, Be able to — expressing ability",
    subtitle: "Grammar of the day",
    body: "All three express ability, but each has specific uses based on tense and formality.",
    examples: [
      { word: "I can swim.", translation: "habilidad presente" },
      { word: "I could swim when I was 5.", translation: "habilidad pasada" },
      { word: "I was able to finish on time.", translation: "habilidad pasada — logro específico" },
    ],
    href: "/courses/modal-ability",
  },
  {
    id: 16,
    slug: "vowel-length",
    level: "basic",
    category: "pronunciation",
    duration: 4,
    title: "Short vs. long vowels",
    subtitle: "Pronunciation of the day",
    body: "English distinguishes words purely by vowel length. Getting this wrong changes the word entirely.",
    examples: [
      { word: "ship / sheep", ipa: "/ʃɪp/ · /ʃiːp/" },
      { word: "full / fool", ipa: "/fʊl/ · /fuːl/" },
      { word: "bit / beat", ipa: "/bɪt/ · /biːt/" },
    ],
    href: "/courses/vowel-length",
  },
  {
    id: 17,
    slug: "frequency-adverbs",
    level: "basic",
    category: "grammar",
    duration: 4,
    title: "Adverbs of frequency",
    subtitle: "Grammar of the day",
    body: "These adverbs tell how often something happens. Their position in the sentence is fixed — a common mistake for Spanish speakers.",
    examples: [
      { word: "I always drink coffee. ✓", translation: "va después del sujeto, antes del verbo" },
      { word: "I drink always coffee. ✗" },
      { word: "always → usually → often → sometimes → rarely → never" },
    ],
    href: "/courses/frequency-adverbs",
  },
  {
    id: 18,
    slug: "basic-listening-reductions",
    level: "basic",
    category: "listening",
    duration: 5,
    title: "Why you can't understand fast English",
    subtitle: "Listening of the day",
    body: "Native speakers reduce, link, and swallow sounds in speech. The written word looks nothing like what's actually said.",
    examples: [
      { word: "'What are you doing?' sounds like →", ipa: "/wʌd͡ʒə ˈduːɪŋ/", translation: "whadja doing?" },
      { word: "'I don't know' sounds like →", ipa: "/aɪ doʊnə/", translation: "I dunno" },
    ],
    href: "/courses/listening-reductions",
  },

  // ─── INTERMEDIATE (19–36) ────────────────────────────────────────────────────
  {
    id: 19,
    slug: "present-perfect-vs-past",
    level: "intermediate",
    category: "grammar",
    duration: 6,
    title: "Present Perfect vs. Simple Past",
    subtitle: "Grammar of the day",
    body: "This is one of the most common mistakes Spanish speakers make. The key is whether the time is specified or still relevant to now.",
    examples: [
      { word: "I've seen that movie.", translation: "experiencia de vida — tiempo no importa" },
      { word: "I saw that movie last Friday.", translation: "tiempo específico → past simple" },
    ],
    tip: "If you can answer 'when?', use Simple Past. If 'when?' is irrelevant, use Present Perfect.",
    href: "/courses/present-perfect-past",
  },
  {
    id: 20,
    slug: "sentence-stress",
    level: "intermediate",
    category: "pronunciation",
    duration: 5,
    title: "Sentence stress changes meaning",
    subtitle: "Pronunciation of the day",
    body: "In English, shifting stress to a different word in the same sentence creates a completely different implication.",
    examples: [
      { word: "I didn't say she stole the money.", translation: "7 meanings — one per stressed word" },
      { word: "I DIDN'T say she stole the money.", translation: "alguien más lo dijo" },
      { word: "I didn't say SHE stole the money.", translation: "alguien más lo robó" },
    ],
    href: "/courses/sentence-stress",
  },
  {
    id: 21,
    slug: "conditionals-zero-first",
    level: "intermediate",
    category: "grammar",
    duration: 6,
    title: "Zero & First Conditionals",
    subtitle: "Grammar of the day",
    body: "Zero conditional is for universal truths. First conditional is for real, likely future situations.",
    examples: [
      { word: "If you heat water to 100°C, it boils.", translation: "zero conditional — verdad científica" },
      { word: "If it rains, I'll stay home.", translation: "first conditional — situación probable" },
    ],
    href: "/courses/conditionals-zero-first",
  },
  {
    id: 22,
    slug: "collocations-make-do",
    level: "intermediate",
    category: "collocations",
    duration: 5,
    title: "Make vs. Do — the collocations that matter",
    subtitle: "Collocations of the day",
    body: "Spanish speakers often mix these up. There's no perfect rule, but there are patterns: 'make' tends to involve creating; 'do' tends to involve tasks.",
    examples: [
      { word: "make a decision · make a mistake · make money" },
      { word: "do homework · do research · do your best" },
    ],
    href: "/courses/make-do",
  },
  {
    id: 23,
    slug: "passive-voice-intro",
    level: "intermediate",
    category: "grammar",
    duration: 6,
    title: "The passive voice — when and why",
    subtitle: "Grammar of the day",
    body: "Use passive when the action is more important than who did it, or when the agent is unknown or obvious.",
    examples: [
      { word: "The report was written by Ana.", translation: "pasiva con agente" },
      { word: "My phone was stolen.", translation: "agente desconocido" },
      { word: "English is spoken worldwide.", translation: "agente obvio" },
    ],
    href: "/courses/passive-voice",
  },
  {
    id: 24,
    slug: "intonation-questions",
    level: "intermediate",
    category: "pronunciation",
    duration: 5,
    title: "Rising vs. falling intonation",
    subtitle: "Pronunciation of the day",
    body: "Intonation patterns signal whether you're asking, concluding, or leaving something open. Getting it wrong can make you sound rude.",
    examples: [
      { word: "Yes/No questions → rising ↗", translation: "'Are you coming?'" },
      { word: "Wh- questions → falling ↘", translation: "'Where are you going?'" },
      { word: "Lists → rising until last item ↘", translation: "'Coffee, tea, or water?'" },
    ],
    href: "/courses/intonation",
  },
  {
    id: 25,
    slug: "reported-speech",
    level: "intermediate",
    category: "grammar",
    duration: 6,
    title: "Reported speech: backshifting tenses",
    subtitle: "Grammar of the day",
    body: "When reporting what someone said, verbs shift one tense back in time. This is called backshifting.",
    examples: [
      { word: "'I am tired.' → She said she was tired.", translation: "am → was" },
      { word: "'I will call you.' → He said he would call me.", translation: "will → would" },
    ],
    href: "/courses/reported-speech",
  },
  {
    id: 26,
    slug: "get-collocations",
    level: "intermediate",
    category: "collocations",
    duration: 5,
    title: "'Get' — the most versatile word in English",
    subtitle: "Vocabulary of the day",
    body: "'Get' has over 20 distinct meanings in common use. These are the ones you need first.",
    examples: [
      { word: "get tired", translation: "volverse / llegar a un estado" },
      { word: "get a job", translation: "obtener" },
      { word: "get home", translation: "llegar" },
      { word: "get the joke", translation: "entender" },
    ],
    href: "/courses/get-collocations",
  },
  {
    id: 27,
    slug: "second-conditional",
    level: "intermediate",
    category: "grammar",
    duration: 6,
    title: "Second Conditional — hypothetical present",
    subtitle: "Grammar of the day",
    body: "Use the second conditional for imaginary or unlikely situations in the present or future. The key: past tense in the if-clause, would in the result.",
    examples: [
      { word: "If I had a million dollars, I'd travel the world.", translation: "irreal — no tengo un millón" },
      { word: "If I were you, I'd apologize.", translation: "consejo — nota: 'were' para todas las personas" },
    ],
    href: "/courses/second-conditional",
  },
  {
    id: 28,
    slug: "discourse-markers",
    level: "intermediate",
    category: "speaking",
    duration: 5,
    title: "Discourse markers that buy you time",
    subtitle: "Speaking of the day",
    body: "Native speakers use these phrases constantly to organize their thoughts, signal transitions, and avoid awkward silence.",
    examples: [
      { word: "Having said that…", translation: "introduce un contraste" },
      { word: "As a matter of fact…", translation: "introduce información sorprendente" },
      { word: "Come to think of it…", translation: "algo que acabas de recordar" },
    ],
    href: "/courses/discourse-markers",
  },
  {
    id: 29,
    slug: "noun-verb-pairs",
    level: "intermediate",
    category: "vocabulary",
    duration: 5,
    title: "Nouns that become verbs — and vice versa",
    subtitle: "Vocabulary of the day",
    body: "English is unusually flexible: many words can be both nouns and verbs without any change in form. Context and stress are the only signals.",
    examples: [
      { word: "a REcord (n.) · to reCORD (v.)", translation: "stress shift" },
      { word: "to email · to Google · to text", translation: "nouns converted to verbs" },
    ],
    href: "/courses/noun-verb-conversion",
  },
  {
    id: 30,
    slug: "modals-deduction",
    level: "intermediate",
    category: "grammar",
    duration: 6,
    title: "Modals for deduction: must, might, can't",
    subtitle: "Grammar of the day",
    body: "These modals express how certain you are about something in the present. They're essential for natural-sounding speculation.",
    examples: [
      { word: "She must be exhausted.", translation: "casi seguro — lógico concluirlo" },
      { word: "He might be at the gym.", translation: "posible — no estás seguro" },
      { word: "That can't be right.", translation: "imposible — contradice la evidencia" },
    ],
    href: "/courses/modals-deduction",
  },
  {
    id: 31,
    slug: "relative-clauses",
    level: "intermediate",
    category: "grammar",
    duration: 6,
    title: "Defining vs. non-defining relative clauses",
    subtitle: "Grammar of the day",
    body: "Both use who/which/that, but non-defining clauses add extra info that can be removed — shown by commas.",
    examples: [
      { word: "The book that changed my life is long.", translation: "defining — sin comas, necesaria" },
      { word: "My sister, who lives in London, is visiting.", translation: "non-defining — con comas, extra info" },
    ],
    href: "/courses/relative-clauses",
  },
  {
    id: 32,
    slug: "connected-speech",
    level: "intermediate",
    category: "pronunciation",
    duration: 6,
    title: "Connected speech: linking, elision, assimilation",
    subtitle: "Pronunciation of the day",
    body: "Words in a sentence don't sound isolated — they flow together. Three processes shape how native English actually sounds.",
    examples: [
      { word: "linking: 'an apple' → /ə ˈnæp.əl/", translation: "consonant + vowel se unen" },
      { word: "elision: 'next day' → /nɛks deɪ/", translation: "sonido desaparece" },
      { word: "assimilation: 'ten boys' → /ˈtem bɔɪz/", translation: "/n/ se convierte en /m/" },
    ],
    href: "/courses/connected-speech",
  },
  {
    id: 33,
    slug: "hedging-language",
    level: "intermediate",
    category: "writing",
    duration: 5,
    title: "Hedging — how to sound less absolute",
    subtitle: "Writing of the day",
    body: "Academic and professional English avoids strong claims. Hedging language makes your writing sound more credible and careful.",
    examples: [
      { word: "This suggests that…", translation: "más débil que 'this proves'" },
      { word: "It seems likely that…" },
      { word: "The data tend to indicate…" },
    ],
    href: "/courses/hedging",
  },
  {
    id: 34,
    slug: "false-friends",
    level: "intermediate",
    category: "vocabulary",
    duration: 5,
    title: "False friends: Spanish–English false cognates",
    subtitle: "Vocabulary of the day",
    body: "These words look like Spanish but mean something completely different in English — a reliable source of embarrassing mistakes.",
    examples: [
      { word: "embarrassed ≠ embarazada", translation: "'embarrassed' = avergonzado/a" },
      { word: "actually ≠ actualmente", translation: "'actually' = en realidad" },
      { word: "library ≠ librería", translation: "'library' = biblioteca" },
    ],
    href: "/courses/false-friends",
  },
  {
    id: 35,
    slug: "aspect-perfect-continuous",
    level: "intermediate",
    category: "grammar",
    duration: 6,
    title: "Present Perfect Continuous",
    subtitle: "Grammar of the day",
    body: "Use this tense for actions that started in the past and are still ongoing — especially when you want to emphasize the duration or a visible result.",
    examples: [
      { word: "I've been studying for 3 hours.", translation: "énfasis en la duración" },
      { word: "She's been crying.", translation: "resultado visible — ojos rojos" },
    ],
    href: "/courses/present-perfect-continuous",
  },
  {
    id: 36,
    slug: "idioms-time",
    level: "intermediate",
    category: "idioms",
    duration: 5,
    title: "Time idioms every intermediate speaker should know",
    subtitle: "Idioms of the day",
    body: "These idioms about time appear constantly in everyday speech, podcasts, and writing.",
    examples: [
      { word: "in the nick of time", translation: "justo a tiempo" },
      { word: "once in a blue moon", translation: "muy raramente" },
      { word: "against the clock", translation: "con prisa, con el tiempo encima" },
    ],
    href: "/courses/idioms-time",
  },

  // ─── ADVANCED (37–50) ────────────────────────────────────────────────────────
  {
    id: 37,
    slug: "third-conditional",
    level: "advanced",
    category: "grammar",
    duration: 7,
    title: "Third Conditional & mixed conditionals",
    subtitle: "Grammar of the day",
    body: "Third conditional expresses regret about the past. Mixed conditionals combine time frames — a mark of truly fluent English.",
    examples: [
      { word: "If I had studied, I would have passed.", translation: "past unreal — arrepentimiento" },
      { word: "If I had slept, I wouldn't be tired now.", translation: "mixed: pasado → presente" },
    ],
    href: "/courses/third-conditional",
  },
  {
    id: 38,
    slug: "inversion-emphasis",
    level: "advanced",
    category: "grammar",
    duration: 7,
    title: "Inversion for emphasis",
    subtitle: "Grammar of the day",
    body: "Inversion — placing the auxiliary before the subject — creates strong emphasis and is common in formal writing and dramatic speech.",
    examples: [
      { word: "Never have I seen such bravery.", translation: "negativo al inicio → inversión" },
      { word: "Not only did she win, she broke a record.", translation: "'not only' al inicio" },
      { word: "Rarely does he make mistakes.", translation: "adverbio negativo al inicio" },
    ],
    href: "/courses/inversion",
  },
  {
    id: 39,
    slug: "register-formal-informal",
    level: "advanced",
    category: "writing",
    duration: 7,
    title: "Register: choosing the right level of formality",
    subtitle: "Writing of the day",
    body: "The same idea can be expressed at every register. Advanced speakers switch fluidly — this is what separates B2 from C1.",
    examples: [
      { word: "Can you help me? (informal)", translation: "conversacional" },
      { word: "I was wondering if you could assist me. (formal)" },
      { word: "I would be grateful if you could provide assistance. (very formal)" },
    ],
    href: "/courses/register",
  },
  {
    id: 40,
    slug: "cleft-sentences",
    level: "advanced",
    category: "grammar",
    duration: 7,
    title: "Cleft sentences for focus",
    subtitle: "Grammar of the day",
    body: "Cleft sentences split a simple sentence to highlight one element. 'It was X that…' and 'What I want is…' are the two main types.",
    examples: [
      { word: "It was Maria who called.", translation: "énfasis en María, no en otra persona" },
      { word: "What I need is more time.", translation: "énfasis en 'más tiempo'" },
    ],
    href: "/courses/cleft-sentences",
  },
  {
    id: 41,
    slug: "participle-clauses",
    level: "advanced",
    category: "grammar",
    duration: 7,
    title: "Participle clauses",
    subtitle: "Grammar of the day",
    body: "Participle clauses condense two sentences into one, showing the relationship between actions without repeating the subject.",
    examples: [
      { word: "Having finished the report, she left.", translation: "acción completada antes que la principal" },
      { word: "Written in 1984, the book still feels relevant.", translation: "pasado — describe el sujeto" },
    ],
    href: "/courses/participle-clauses",
  },
  {
    id: 42,
    slug: "advanced-collocations",
    level: "advanced",
    category: "collocations",
    duration: 6,
    title: "Collocations with 'raise' and 'rise'",
    subtitle: "Collocations of the day",
    body: "'Raise' is transitive — it needs an object. 'Rise' is intransitive — it never takes an object. This distinction trips up advanced learners.",
    examples: [
      { word: "raise a question · raise awareness · raise funds", translation: "raise + objeto" },
      { word: "prices rise · temperatures rise · he rose to fame", translation: "rise — sin objeto" },
    ],
    href: "/courses/raise-rise",
  },
  {
    id: 43,
    slug: "pragmatics-politeness",
    level: "advanced",
    category: "speaking",
    duration: 7,
    title: "Pragmatics: what English speakers really mean",
    subtitle: "Speaking of the day",
    body: "Advanced fluency requires understanding pragmatic meaning — what's implied, not just what's said. English often relies on indirectness.",
    examples: [
      { word: "'It's a bit warm in here…'", translation: "implicación: ¿puedes abrir la ventana?" },
      { word: "'That's an interesting idea.'", translation: "puede significar: no estoy convencido" },
    ],
    href: "/courses/pragmatics",
  },
  {
    id: 44,
    slug: "subjunctive",
    level: "advanced",
    category: "grammar",
    duration: 7,
    title: "The subjunctive in English",
    subtitle: "Grammar of the day",
    body: "The English subjunctive is subtle and mostly appears in formal writing. It uses the base form of the verb regardless of subject.",
    examples: [
      { word: "I suggest that she be promoted.", translation: "formal — no 'is'" },
      { word: "It's vital that he attend the meeting.", translation: "no 'attends'" },
      { word: "If I were taller… (were, not was)", translation: "subjunctive en condicionales" },
    ],
    href: "/courses/subjunctive",
  },
  {
    id: 45,
    slug: "ellipsis-substitution",
    level: "advanced",
    category: "grammar",
    duration: 6,
    title: "Ellipsis and substitution",
    subtitle: "Grammar of the day",
    body: "Native speakers omit predictable words (ellipsis) and replace repeated phrases with shorter ones (substitution) to avoid repetition.",
    examples: [
      { word: "'Can you come?' 'I might [be able to come].'", translation: "ellipsis — omisión" },
      { word: "'I want a coffee.' 'So do I.'", translation: "substitution con 'so'" },
    ],
    href: "/courses/ellipsis",
  },
  {
    id: 46,
    slug: "advanced-idioms",
    level: "advanced",
    category: "idioms",
    duration: 6,
    title: "Idioms that sound native at C1",
    subtitle: "Idioms of the day",
    body: "These idioms are less common than basics but mark a speaker as genuinely fluent — they appear in journalism, literature, and conversation.",
    examples: [
      { word: "to bite the bullet", translation: "aguantar algo difícil" },
      { word: "to throw caution to the wind", translation: "arriesgarse sin precaución" },
      { word: "to be on the fence", translation: "estar indeciso" },
    ],
    href: "/courses/advanced-idioms",
  },
  {
    id: 47,
    slug: "academic-writing-cohesion",
    level: "advanced",
    category: "writing",
    duration: 8,
    title: "Cohesion devices in academic writing",
    subtitle: "Writing of the day",
    body: "Cohesion is how sentences and paragraphs connect to form a unified text. It's the difference between a list of ideas and an argument.",
    examples: [
      { word: "lexical chains: water → liquid → fluid → hydration", translation: "variación semántica" },
      { word: "reference: 'this phenomenon' / 'such findings'", translation: "referencia anafórica" },
    ],
    href: "/courses/academic-cohesion",
  },
  {
    id: 48,
    slug: "phonemic-awareness-advanced",
    level: "advanced",
    category: "pronunciation",
    duration: 7,
    title: "Phonemic pairs that confuse advanced learners",
    subtitle: "Pronunciation of the day",
    body: "Even advanced speakers struggle with these minimal pairs. The problem isn't individual sounds — it's perception and muscle memory.",
    examples: [
      { word: "collar / caller", ipa: "/ˈkɒl.ər/ · /ˈkɔː.lər/" },
      { word: "cot / caught", ipa: "/kɒt/ · /kɔːt/", translation: "merger en algunos dialectos americanos" },
    ],
    href: "/courses/phonemic-pairs",
  },
  {
    id: 49,
    slug: "discourse-analysis",
    level: "advanced",
    category: "listening",
    duration: 8,
    title: "How to follow complex spoken discourse",
    subtitle: "Listening of the day",
    body: "At advanced level, the challenge isn't words — it's tracking the argument structure across a long audio. These strategies help.",
    examples: [
      { word: "'On the one hand… on the other…'", translation: "señal de contraste que viene" },
      { word: "'What I'm really trying to say is…'", translation: "señal de resumen / clarificación" },
    ],
    href: "/courses/discourse-analysis",
  },
  {
    id: 50,
    slug: "style-voice",
    level: "advanced",
    category: "writing",
    duration: 8,
    title: "Developing your voice in English",
    subtitle: "Writing of the day",
    body: "Fluency is more than accuracy. Voice is the consistent set of choices — rhythm, diction, sentence length — that make your writing recognizably yours.",
    examples: [
      { word: "short sentences create urgency.", translation: "impacto" },
      { word: "longer sentences, by contrast, allow ideas to unfold at a more deliberate pace.", translation: "elaboración" },
    ],
    tip: "Read one paragraph aloud. Does it sound like you? That's the test.",
    href: "/courses/writing-voice",
  },
];

// ─── Helper: get today's lesson based on day of year ─────────────────────────
export function getTodaysLesson(): MiniLesson {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const diff = now.getTime() - start.getTime();
  const dayOfYear = Math.floor(diff / (1000 * 60 * 60 * 24));
  const index = (dayOfYear - 1) % miniLessons.length;
  return miniLessons[index];
}

// ─── Helper: get lesson by level ─────────────────────────────────────────────
export function getLessonsByLevel(level: LessonLevel): MiniLesson[] {
  return miniLessons.filter((l) => l.level === level);
}

// ─── Helper: get lesson by category ──────────────────────────────────────────
export function getLessonsByCategory(category: LessonCategory): MiniLesson[] {
  return miniLessons.filter((l) => l.category === category);
}