import { buildLevel } from "./buildCurriculum";
import type { CoursePathCurriculum } from "./types";

export const COURSE_PATH_CURRICULUM: CoursePathCurriculum = {
  levels: [
    {
      ...buildLevel(
        "a1",
        "A1",
        "Principiante",
        "Inglés Básico A1",
        "20 h",
        [
          { t: "Estrategias para Aprender Inglés en Línea", p: 1, g: "a1-estrategias-aprender-ingles" },
          { t: "Inglés A1 para Principiantes", p: 1, g: "a1-ingles-principiantes" },
          { t: "Verbo To Be", p: 1, g: "a1-verbo-to-be" },
          { t: "Presente Simple", p: 1, g: "a1-presente-simple" },
          { t: "Verbos Comunes", p: 1, g: "a1-verbos-comunes" },
          { t: "Construcción de Oraciones (parts of speech)", p: 1, g: "a1-construccion-oraciones" },
          { t: "Pronunciación Básica", p: 1, s: true, g: "a1-pronunciacion-basica" },
          { t: "La R Americana /ɹ/", p: 1, s: true, g: "a1-sonido-r-americano" },
          { t: "Vocales /æ/ y /ʌ/", p: 1, s: true, g: "a1-vocales-ae-ua" },
          { t: "Pronombres Objeto", p: 1, g: "a1-pronombres-objeto" },
          { t: "El Imperativo", p: 1, g: "a1-imperativo" },
          { t: "Alfabeto y Deletreo", p: 0, g: "a1-alfabeto-deletreo" },
          { t: "Inglés por Teléfono", p: 0, g: "a1-ingles-telefonico" },
          { t: "Fechas, Horas y Descripciones", p: 0, g: "a1-fechas-horas-descripciones" },
          { t: "Preferencias y Habilidades", p: 0, g: "a1-preferencias-habilidades" },
          { t: "Vocabulario y Expresiones básicas", p: 0, g: "a1-vocabulario-expresiones-basicas" },
          { t: "Escritura Básica", p: 0, g: "a1-escritura-basica" },
          { t: "Práctico: Familia", p: 0, g: "a1-practico-familia" },
          { t: "Práctico: Elementos de Trabajo", p: 0, g: "a1-practico-elementos-trabajo" },
          { t: "Audio: Preposiciones", p: 0, s: true, g: "a1-audio-preposiciones" },
          { t: "Audio: Inglés para Viajes", p: 0, s: true, g: "a1-audio-ingles-viajes" },
        ]
      ),
      realLife: [
        {
          id: "a1-restaurant",
          title: "At a restaurant",
          emoji: "🍽️",
          phrases: [
            "A table for two, please.",
            "Can I see the menu?",
            "I'd like the chicken, please.",
            "Can we get the bill?",
          ],
          vocab: [
            { word: "menu", meaning: "lista de comidas y precios" },
            { word: "bill", meaning: "la cuenta" },
            { word: "tip", meaning: "propina" },
            { word: "waiter", meaning: "mesero" },
          ],
        },
        {
          id: "a1-introduction",
          title: "Your first introduction",
          emoji: "👋",
          phrases: [
            "Nice to meet you, I'm [name].",
            "What do you do?",
            "I'm a [job]. And you?",
            "Where are you from?",
          ],
          vocab: [
            { word: "nice to meet you", meaning: "mucho gusto" },
            { word: "work", meaning: "trabajo / trabajar" },
            { word: "hobby", meaning: "pasatiempo" },
            { word: "from", meaning: "de (origen)" },
          ],
        },
        {
          id: "a1-daily-routine",
          title: "Talking about your day",
          emoji: "☀️",
          phrases: [
            "I usually wake up at seven.",
            "I have breakfast at home.",
            "I go to work by bus.",
            "I go to bed early.",
          ],
          vocab: [
            { word: "usually", meaning: "normalmente" },
            { word: "wake up", meaning: "despertar" },
            { word: "routine", meaning: "rutina" },
            { word: "tired", meaning: "cansado/a" },
          ],
        },
      ],
    },
    {
      ...buildLevel(
        "a2",
        "A2",
        "Elemental",
        "Inglés Básico A2",
        "19 h",
        [
          { t: "Preguntas y Respuestas Comunes", p: 1, g: "a2-preguntas-respuestas" },
          { t: "Experiencias Pasadas y Planes", p: 1, g: "a2-experiencias-pasadas-planes" },
          { t: "Infinitivos y Presente Continuo", p: 1, g: "a2-infinitivos-presente-continuo" },
          { t: "Sustantivos e Intenciones Futuras", p: 1, g: "a2-sustantivos-intenciones-futuras" },
          { t: "Obligación y Prohibición", p: 1, g: "a2-obligacion-prohibicion" },
          { t: "Verbos que se Confunden", p: 1, g: "a2-verbos-confusos" },
          { t: "Orden de los Adjetivos", p: 1, g: "a2-orden-adjetivos" },
          { t: "Audio Historia: Aventura en la Ciudad", p: 1, s: true, g: "a2-audio-aventura-ciudad" },
          { t: "Adverbios y Expresiones de Tiempo", p: 0, g: "a2-adverbios-expresiones-tiempo" },
          { t: "So y Such", p: 0, g: "a2-so-such" },
          { t: "Each, Every, All, Both, Either, Neither", p: 0, g: "a2-determinantes" },
          { t: "Propuestas y Permisos", p: 0, g: "a2-propuestas-permisos" },
          { t: "Cuantificadores y Superlativos", p: 0, g: "a2-cuantificadores-superlativos" },
          { t: "Conjunciones y Verbos", p: 0, g: "a2-conjunciones-verbos" },
          { t: "Descripciones y Comparaciones", p: 0, g: "a2-descripciones-comparaciones" },
          { t: "Práctico: Compras", p: 0, g: "a2-practico-compras" },
          { t: "Práctico: Cocina", p: 0, g: "a2-practico-cocina" },
          { t: "Práctico: Viajes de Turismo", p: 0, g: "a2-practico-viajes-turismo" },
          { t: "Práctico: Partes del Cuerpo", p: 0, g: "a2-practico-partes-cuerpo" },
        ]
      ),
      realLife: [
        {
          id: "a2-shopping",
          title: "Shopping",
          emoji: "🛍️",
          phrases: [
            "How much does this cost?",
            "Do you have this in another size?",
            "I'll take it.",
            "Can I pay by card?",
          ],
          vocab: [
            { word: "price", meaning: "precio" },
            { word: "receipt", meaning: "recibo / ticket" },
            { word: "size", meaning: "talla / tamaño" },
            { word: "cash", meaning: "efectivo" },
          ],
        },
        {
          id: "a2-making-plans",
          title: "Making plans",
          emoji: "📅",
          phrases: [
            "Are you free on Saturday?",
            "What do you want to do?",
            "Let's meet at six.",
            "Sorry, I can't. Maybe next time.",
          ],
          vocab: [
            { word: "free", meaning: "libre / disponible" },
            { word: "plans", meaning: "planes" },
            { word: "meet up", meaning: "quedar / encontrarse" },
            { word: "next time", meaning: "la próxima vez" },
          ],
        },
        {
          id: "a2-directions",
          title: "Asking for directions",
          emoji: "🗺️",
          phrases: [
            "Excuse me, where is the bank?",
            "Turn left at the traffic light.",
            "It's next to the supermarket.",
            "How far is it?",
          ],
          vocab: [
            { word: "turn left / right", meaning: "girar a la izquierda / derecha" },
            { word: "straight ahead", meaning: "todo recto" },
            { word: "corner", meaning: "esquina" },
            { word: "far", meaning: "lejos" },
          ],
        },
      ],
    },
    {
      ...buildLevel(
        "b1",
        "B1",
        "Intermedio",
        "Inglés Intermedio B1",
        "28 h",
        [
          { t: "Presente Perfecto y Preposiciones", p: 1, g: "b1-presente-perfecto-preposiciones" },
          { t: "Primer Condicional y Pasado Continuo", p: 1, g: "b1-primer-condicional-pasado-continuo" },
          { t: "Comparativos y Planes Futuros", p: 1, g: "b1-comparativos-planes-futuros" },
          { t: "Pronombres y Cláusulas Relativas", p: 1, g: "b1-pronombres-clausulas-relativas" },
          { t: "Voz Pasiva y Consejos", p: 1, g: "b1-voz-pasiva-consejos" },
          { t: "Tipos de Phrasal Verbs", p: 1, g: "b1-phrasal-verbs-tipos" },
          { t: "Audio Historia: Misterios sin Resolver", p: 1, s: true, g: "b1-audio-misterios-sin-resolver" },
          { t: "Expresiones de Tiempo y Cantidad", p: 0, g: "b1-expresiones-tiempo-cantidad" },
          { t: "Emociones y Estados de Ánimo", p: 0, g: "b1-emociones-estados-animo" },
          { t: "Finanzas Personales", p: 0, g: "b1-finanzas-personales" },
          { t: "Estrategias de Escucha", p: 0, g: "b1-estrategias-escucha" },
          { t: "Conectores y Preferencias", p: 0, g: "b1-conectores-preferencias" },
          { t: "Adjetivos y Preguntas Indirectas", p: 0, g: "b1-adjetivos-preguntas-indirectas" },
          { t: "Confirmación y Posibilidades", p: 0, g: "b1-confirmacion-posibilidades" },
          { t: "Solicitudes y Pronombres Reflexivos", p: 0, g: "b1-solicitudes-pronombres-reflexivos" },
          { t: "Palabras Interrogativas y Propósitos", p: 0, g: "b1-palabras-interrogativas-propositos" },
          { t: "Preguntas Negativas y Recomendaciones", p: 0, g: "b1-preguntas-negativas-recomendaciones" },
          { t: "Práctico: Viajes de Negocios", p: 0, g: "b1-practico-viajes-negocios" },
          { t: "Práctico: Música y Arte", p: 0, g: "b1-practico-musica-arte" },
          { t: "Práctico: Consultas Médicas", p: 0, g: "b1-practico-consultas-medicas" },
          { t: "Práctico: Nutrición y Fitness", p: 0, g: "b1-practico-nutricion-fitness" },
        ]
      ),
      realLife: [
        {
          id: "b1-doctor",
          title: "At the doctor's",
          emoji: "🏥",
          phrases: [
            "I've had a headache for two days.",
            "It hurts when I move it.",
            "I've been feeling really tired lately.",
            "Should I take anything for it?",
          ],
          vocab: [
            { word: "symptoms", meaning: "síntomas" },
            { word: "prescription", meaning: "receta médica" },
            { word: "follow up", meaning: "cita de seguimiento" },
            { word: "dizzy", meaning: "mareado/a" },
          ],
        },
        {
          id: "b1-storytelling",
          title: "Telling a story",
          emoji: "📖",
          phrases: [
            "So what happened was…",
            "I couldn't believe it.",
            "Eventually, everything worked out.",
            "You're not going to believe this, but…",
          ],
          vocab: [
            { word: "suddenly", meaning: "de repente" },
            { word: "eventually", meaning: "finalmente / con el tiempo" },
            { word: "meanwhile", meaning: "mientras tanto" },
            { word: "turn out", meaning: "resultar (que)" },
          ],
        },
        {
          id: "b1-work-email",
          title: "Writing a work email",
          emoji: "✉️",
          phrases: [
            "I'm writing to follow up on…",
            "Please let me know if you need anything else.",
            "I'd appreciate a response by Friday.",
            "Looking forward to hearing from you.",
          ],
          vocab: [
            { word: "follow up", meaning: "dar seguimiento" },
            { word: "regarding", meaning: "con respecto a" },
            { word: "attached", meaning: "adjunto" },
            { word: "appreciate", meaning: "agradecer / valorar" },
          ],
        },
      ],
    },
    {
      ...buildLevel(
        "b2",
        "B2",
        "Int. alto",
        "Inglés Intermedio Alto B2",
        "21 h",
        [
          { t: "Inglés Práctico y Conversacional", p: 1, g: "b2-ingles-practico-conversacional" },
          { t: "Phrasal Verbs Comunes", p: 1, g: "b2-phrasal-verbs-comunes" },
          { t: "Conversaciones de Trabajo", p: 1, g: "b2-conversaciones-trabajo" },
          { t: "Pronunciación Intermedia", p: 1, s: true, g: "b2-pronunciacion-intermedia" },
          { t: "Pasado Perfecto y Frases Adverbiales", p: 1, g: "b2-pasado-perfecto-frases-adverbiales" },
          { t: "Discurso Indirecto y Condicionales", p: 1, g: "b2-discurso-indirecto-condicionales" },
          { t: "Causativo: Have y Get Done", p: 1, g: "b2-causativo" },
          { t: "Deseos y Arrepentimientos", p: 1, g: "b2-deseos-arrepentimientos" },
          { t: "Modales en el Pasado", p: 1, g: "b2-modales-pasado" },
          { t: "Audio Historia: Atrapados en la Tecnología", p: 1, s: true, g: "b2-audio-atrapados-tecnologia" },
          { t: "Audio Historia: Origen del Idioma", p: 0, s: true, g: "b2-audio-origen-idioma" },
          { t: "Futuro Perfecto y Continuo", p: 0, g: "b2-futuro-perfecto-continuo" },
          { t: "Tiempos Narrativos Integrados", p: 0, g: "b2-narracion-integrada" },
          { t: "Contar Anécdotas", p: 0, g: "b2-contar-anecdotas" },
          { t: "Suposiciones e Instrucciones", p: 0, g: "b2-suposiciones-instrucciones" },
          { t: "Comentarios y Opiniones", p: 0, g: "b2-comentarios-opiniones" },
          { t: "Hábitos y Aproximaciones", p: 0, g: "b2-habitos-aproximaciones" },
          { t: "Vocabulario y Expresiones intermedio", p: 0, g: "b2-vocabulario-expresiones-intermedio" },
          { t: "Escritura Intermedia", p: 0, g: "b2-escritura-intermedia" },
          { t: "Ortografía y Puntuación", p: 0, g: "b2-ortografia-puntuacion" },
        ]
      ),
      realLife: [
        {
          id: "b2-opinions",
          title: "Giving your opinion",
          emoji: "💬",
          phrases: [
            "I'd argue that…",
            "To be honest, I think…",
            "It's a valid point, but…",
            "From my perspective…",
          ],
          vocab: [
            { word: "perspective", meaning: "perspectiva" },
            { word: "valid point", meaning: "punto válido" },
            { word: "nuance", meaning: "matiz" },
            { word: "argue", meaning: "argumentar / sostener" },
          ],
        },
        {
          id: "b2-anecdote",
          title: "Telling an anecdote",
          emoji: "😄",
          phrases: [
            "I was just about to leave when…",
            "The thing is, I had no idea that…",
            "Looking back on it now, I realize…",
            "It was one of those moments where…",
          ],
          vocab: [
            { word: "just about to", meaning: "estar a punto de" },
            { word: "looking back", meaning: "mirando atrás" },
            { word: "realize", meaning: "darse cuenta" },
            { word: "end up", meaning: "terminar / acabar haciendo algo" },
          ],
        },
        {
          id: "b2-negotiation",
          title: "Negotiating at work",
          emoji: "🤝",
          phrases: [
            "I understand your position, however…",
            "Could we find a middle ground?",
            "I'd be willing to if you could…",
            "Let's revisit this next week.",
          ],
          vocab: [
            { word: "middle ground", meaning: "punto intermedio" },
            { word: "willing", meaning: "dispuesto/a" },
            { word: "revisit", meaning: "retomar / volver a ver" },
            { word: "trade-off", meaning: "concesión mutua" },
          ],
        },
      ],
    },
    {
      ...buildLevel(
        "c1",
        "C1",
        "Avanzado",
        "Inglés Avanzado C1",
        "15 h",
        [
          { t: "Conectores y Contracciones Informales (reducciones)", p: 1, s: true, g: "c1-conectores-contracciones-informales" },
          { t: "Pronunciación Avanzada", p: 1, s: true, g: "c1-pronunciacion-avanzada" },
          { t: "Lenguaje Coloquial y Habitual", p: 1, g: "c1-lenguaje-coloquial-habitual" },
          { t: "Recursos Conversacionales y Lingüísticos", p: 1, g: "c1-recursos-conversacionales" },
          { t: "Argumentos y Discusiones", p: 1, g: "c1-argumentos-discusiones" },
          { t: "Presentaciones y Expresión Oral", p: 1, g: "c1-presentaciones-expresion-oral" },
          { t: "Humor e Ironía", p: 0, g: "c1-humor-ironia" },
          { t: "Nominalización", p: 0, g: "c1-nominalizacion" },
          { t: "Comunicación Persuasiva y Efectiva", p: 0, g: "c1-comunicacion-persuasiva-efectiva" },
          { t: "Vocabulario y Expresiones avanzado", p: 0, g: "c1-vocabulario-expresiones-avanzado" },
          { t: "Escritura Avanzada", p: 0, g: "c1-escritura-avanzada" },
          { t: "Expresiones Idiomáticas de Negocios", p: 0, g: "c1-expresiones-idiomaticas-negocios" },
        ]
      ),
      realLife: [
        {
          id: "c1-ambiguity",
          title: "Navigating ambiguity",
          emoji: "🌫️",
          phrases: [
            "I see where you're coming from, but…",
            "That depends on how you look at it.",
            "There's more to it than meets the eye.",
            "It's a bit of a grey area.",
          ],
          vocab: [
            { word: "implication", meaning: "implicación / consecuencia sobreentendida" },
            { word: "subtext", meaning: "subtexto / lo que no se dice" },
            { word: "grey area", meaning: "zona gris / no claro" },
            { word: "nuanced", meaning: "matizado / con muchos ángulos" },
          ],
        },
        {
          id: "c1-humor",
          title: "Humor and irony",
          emoji: "😏",
          phrases: [
            "Oh, obviously that went exactly as planned.",
            "Well, that was fun. Said no one ever.",
            "Right, because that makes total sense.",
            "I'm sure that'll go brilliantly.",
          ],
          vocab: [
            { word: "understatement", meaning: "decir menos de lo que se siente (ironía suave)" },
            { word: "sarcasm", meaning: "sarcasmo" },
            { word: "deadpan", meaning: "humor seco / sin expresión" },
            { word: "tongue-in-cheek", meaning: "irónico / no completamente en serio" },
          ],
        },
        {
          id: "c1-persuasion",
          title: "Persuading subtly",
          emoji: "🎯",
          phrases: [
            "You might want to consider…",
            "It's worth bearing in mind that…",
            "One could make the case that…",
            "I'd be remiss not to mention…",
          ],
          vocab: [
            { word: "hedging", meaning: "suavizar afirmaciones para sonar menos directo" },
            { word: "softener", meaning: "expresión que mitiga el impacto" },
            { word: "conviction", meaning: "convicción / certeza firme" },
            { word: "remiss", meaning: "negligente / que falla en su deber" },
          ],
        },
      ],
    },
  ],
  electiveTracks: [
    buildLevel(
      "purposes",
      "Tech",
      "Especialización",
      "Propósitos Específicos",
      "14 h",
      [
        { t: "Inglés para Programadores", p: 2, g: "tech-ingles-programadores" },
        { t: "Inglés para Inteligencia Artificial", p: 1, g: "tech-ingles-inteligencia-artificial" },
        { t: "Inglés Práctico con ChatGPT", p: 1, g: "tech-ingles-chatgpt" },
        { t: "Inglés para Ciberseguridad", p: 0, g: "tech-ingles-ciberseguridad" },
        { t: "Inglés para Servicio al Cliente", p: 0, g: "tech-ingles-servicio-cliente" },
        { t: "Inglés para Marketing", p: 0, g: "tech-ingles-marketing" },
        { t: "Inglés para Ventas", p: 0, g: "tech-ingles-ventas" },
        { t: "Inglés para Startups", p: 0, g: "tech-ingles-startups" },
        { t: "Preparación TOEFL", p: 0, g: "tech-preparacion-toefl" },
        { t: "Preparación IELTS", p: 0, g: "tech-preparacion-ielts" },
      ],
      { isElective: true, spineIcon: "laptop" }
    ),
    buildLevel(
      "business",
      "Biz",
      "Profesional",
      "Inglés de Negocios",
      "9 h",
      [
        { t: "Inglés para Entrevistas de Trabajo", p: 2, g: "biz-entrevistas-trabajo" },
        { t: "Conversaciones de Trabajo", p: 1, g: "biz-conversaciones-trabajo" },
        { t: "Desarrollo Profesional", p: 1, g: "biz-desarrollo-profesional" },
        { t: "Vocabulario para el Trabajo", p: 0, g: "biz-vocabulario-trabajo" },
        { t: "Elementos de Trabajo", p: 0, g: "biz-elementos-trabajo" },
        { t: "Viajes de Negocios", p: 0, g: "biz-viajes-negocios" },
        { t: "Negocios para Managers", p: 0, g: "biz-negocios-managers" },
        { t: "Expresiones Idiomáticas de Negocios", p: 0, g: "biz-expresiones-idiomaticas-negocios" },
      ],
      { isElective: true, spineIcon: "briefcase" }
    ),
    buildLevel(
      "connected-speech",
      "CS",
      "Puente",
      "Connected Speech · Puente al Sound Lab",
      "4 h",
      [
        { t: "Reducciones: gonna, wanna, 'll", p: 2, s: true, g: "cs-reductions" },
        { t: "Enlace de sonidos", p: 2, s: true, g: "cs-linking" },
        { t: "Elisión: sonidos que caen", p: 1, s: true, g: "cs-elision" },
        { t: "Asimilación: doncha, didja", p: 1, s: true, g: "cs-assimilation" },
      ],
      { isElective: true, spineIcon: "mic" }
    ),
  ],
  legend: [
    { icon: "priority-max", description: "Máxima prioridad (meta laboral)" },
    { icon: "priority", description: "Ruta crítica (avanzar rápido)" },
    { icon: "sound-lab", description: "Conecta con Sound Lab" },
    { icon: "optional", description: "Currículo amplio · para después" },
  ],
  why: {
    title: "How this connects to Sound Lab",
    paragraphs: [
      "Grammar and pronunciation run on parallel tracks. Courses marked with a microphone icon unlock sections of your Sound Lab at matching difficulty levels.",
      "Unstarred courses at each level are extended curriculum: useful, but tackle the starred spine first.",
    ],
  },
};
