import { buildLevelFromPlatzi } from "./buildCurriculum";
import type { CoursePathCurriculum } from "./types";

/** Platzi English Academy curriculum (curated), lines 128–231 of reference HTML */
export const COURSE_PATH_CURRICULUM: CoursePathCurriculum = {
  levels: [
    buildLevelFromPlatzi(
      "a1",
      "A1",
      "Principiante",
      "Inglés Básico A1",
      "20 h",
      [
        { t: "Estrategias para Aprender Inglés en Línea", p: 1, g: "a1-estrategias-aprender-ingles" },
        { t: "Inglés A1 para Principiantes", p: 1, g: "a1-ingles-principiantes" },
        { t: "Verbo To Be", p: 1, g: "a1-verbo-to-be" },
        { t: "Presente Simple", p: 1, g: "a1-presente-simple" },
        { t: "Verbos Comunes", p: 1, g: "a1-verbos-comunes" },
        { t: "Construcción de Oraciones (parts of speech)", p: 1, g: "a1-construccion-oraciones" },
        { t: "Pronunciación Básica", p: 1, s: true, g: "a1-pronunciacion-basica" },
        { t: "Fechas, Horas y Descripciones", p: 0 },
        { t: "Preferencias y Habilidades", p: 0 },
        { t: "Vocabulario y Expresiones básicas", p: 0 },
        { t: "Escritura Básica", p: 0 },
        { t: "Práctico: Familia", p: 0 },
        { t: "Práctico: Elementos de Trabajo", p: 0 },
        { t: "Audio: Preposiciones", p: 0, s: true },
        { t: "Audio: Inglés para Viajes", p: 0, s: true },
      ]
    ),
    buildLevelFromPlatzi(
      "a2",
      "A2",
      "Elemental",
      "Inglés Básico A2",
      "19 h",
      [
        { t: "Preguntas y Respuestas Comunes", p: 1, g: "a2-preguntas-respuestas" },
        { t: "Experiencias Pasadas y Planes", p: 1, g: "a2-experiencias-pasadas-planes" },
        { t: "Infinitivos y Presente Continuo", p: 1, g: "a2-infinitivos-presente-continuo" },
        { t: "Sustantivos e Intenciones Futuras", p: 1, g: "a2-sustantivos-intenciones-futuras" },
        { t: "Audio Historia: Aventura en la Ciudad", p: 1, s: true, g: "a2-audio-aventura-ciudad" },
        { t: "Adverbios y Expresiones de Tiempo", p: 0 },
        { t: "Propuestas y Permisos", p: 0 },
        { t: "Cuantificadores y Superlativos", p: 0 },
        { t: "Conjunciones y Verbos", p: 0 },
        { t: "Descripciones y Comparaciones", p: 0 },
        { t: "Práctico: Compras", p: 0 },
        { t: "Práctico: Cocina", p: 0 },
        { t: "Práctico: Viajes de Turismo", p: 0 },
        { t: "Práctico: Partes del Cuerpo", p: 0 },
      ]
    ),
    buildLevelFromPlatzi(
      "b1",
      "B1",
      "Intermedio",
      "Inglés Intermedio B1",
      "28 h",
      [
        { t: "Presente Perfecto y Preposiciones", p: 1, g: "b1-presente-perfecto-preposiciones" },
        { t: "Primer Condicional y Pasado Continuo", p: 1, g: "b1-primer-condicional-pasado-continuo" },
        { t: "Comparativos y Planes Futuros", p: 1, g: "b1-comparativos-planes-futuros" },
        { t: "Pronombres y Cláusulas Relativas", p: 1, g: "b1-pronombres-clausulas-relativas" },
        { t: "Voz Pasiva y Consejos", p: 1, g: "b1-voz-pasiva-consejos" },
        { t: "Audio Historia: Misterios sin Resolver", p: 1, s: true, g: "b1-audio-misterios-sin-resolver" },
        { t: "Expresiones de Tiempo y Cantidad", p: 0 },
        { t: "Conectores y Preferencias", p: 0 },
        { t: "Adjetivos y Preguntas Indirectas", p: 0 },
        { t: "Confirmación y Posibilidades", p: 0 },
        { t: "Solicitudes y Pronombres Reflexivos", p: 0 },
        { t: "Palabras Interrogativas y Propósitos", p: 0 },
        { t: "Preguntas Negativas y Recomendaciones", p: 0 },
        { t: "Práctico: Viajes de Negocios", p: 0 },
        { t: "Práctico: Música y Arte", p: 0 },
        { t: "Práctico: Consultas Médicas", p: 0 },
        { t: "Práctico: Nutrición y Fitness", p: 0 },
      ]
    ),
    buildLevelFromPlatzi(
      "b2",
      "B2",
      "Int. alto",
      "Inglés Intermedio Alto B2",
      "21 h",
      [
        { t: "Inglés Práctico y Conversacional", p: 1 },
        { t: "Phrasal Verbs Comunes", p: 1 },
        { t: "Conversaciones de Trabajo", p: 1 },
        { t: "Pronunciación Intermedia", p: 1, s: true },
        { t: "Pasado Perfecto y Frases Adverbiales", p: 1 },
        { t: "Discurso Indirecto y Condicionales", p: 1 },
        { t: "Audio Historia: Atrapados en la Tecnología", p: 1, s: true },
        { t: "Audio Historia: Origen del Idioma", p: 0, s: true },
        { t: "Suposiciones e Instrucciones", p: 0 },
        { t: "Comentarios y Opiniones", p: 0 },
        { t: "Hábitos y Aproximaciones", p: 0 },
        { t: "Vocabulario y Expresiones intermedio", p: 0 },
        { t: "Escritura Intermedia", p: 0 },
        { t: "Ortografía y Puntuación", p: 0 },
      ]
    ),
    buildLevelFromPlatzi(
      "c1",
      "C1",
      "Avanzado",
      "Inglés Avanzado C1",
      "15 h",
      [
        { t: "Conectores y Contracciones Informales (reducciones)", p: 1, s: true },
        { t: "Pronunciación Avanzada", p: 1, s: true },
        { t: "Lenguaje Coloquial y Habitual", p: 1 },
        { t: "Recursos Conversacionales y Lingüísticos", p: 1 },
        { t: "Argumentos y Discusiones", p: 1 },
        { t: "Presentaciones y Expresión Oral", p: 1 },
        { t: "Comunicación Persuasiva y Efectiva", p: 0 },
        { t: "Vocabulario y Expresiones avanzado", p: 0 },
        { t: "Escritura Avanzada", p: 0 },
        { t: "Expresiones Idiomáticas de Negocios", p: 0 },
      ]
    ),
  ],
  electiveTracks: [
    buildLevelFromPlatzi(
      "purposes",
      "Tech",
      "Especialización",
      "Propósitos Específicos",
      "14 h",
      [
        { t: "Inglés para Programadores", p: 2 },
        { t: "Inglés para Inteligencia Artificial", p: 1 },
        { t: "Inglés Práctico con ChatGPT", p: 1 },
        { t: "Inglés para Ciberseguridad", p: 0 },
        { t: "Inglés para Servicio al Cliente", p: 0 },
        { t: "Inglés para Marketing", p: 0 },
        { t: "Inglés para Ventas", p: 0 },
        { t: "Inglés para Startups", p: 0 },
        { t: "Preparación TOEFL", p: 0 },
        { t: "Preparación IELTS", p: 0 },
      ],
      { isElective: true, spineIcon: "laptop" }
    ),
    buildLevelFromPlatzi(
      "business",
      "Biz",
      "Profesional",
      "Inglés de Negocios",
      "9 h",
      [
        { t: "Inglés para Entrevistas de Trabajo", p: 2 },
        { t: "Conversaciones de Trabajo", p: 1 },
        { t: "Desarrollo Profesional", p: 1 },
        { t: "Vocabulario para el Trabajo", p: 0 },
        { t: "Elementos de Trabajo", p: 0 },
        { t: "Viajes de Negocios", p: 0 },
        { t: "Negocios para Managers", p: 0 },
        { t: "Expresiones Idiomáticas de Negocios", p: 0 },
      ],
      { isElective: true, spineIcon: "briefcase" }
    ),
  ],
  legend: [
    { icon: "priority-max", description: "Máxima prioridad (meta laboral)" },
    { icon: "priority", description: "Ruta crítica (avanzar rápido)" },
    { icon: "sound-lab", description: "Conecta con Sound Lab" },
    { icon: "optional", description: "Currículo amplio · para después" },
  ],
  why: {
    title: "Cómo se cruza con tu Sound Lab",
    paragraphs: [
      "La gramática y la pronunciación son dos pistas paralelas. Los cursos con icono de micrófono desbloquean tramos de tu Sound Lab por nivel de dificultad.",
      "Lo sin estrella en cada nivel es currículo amplio: útil, pero después de la columna vertebral prioritaria.",
    ],
  },
};
