import fs from "node:fs";
import path from "node:path";
import { COURSE_PATH_CURRICULUM } from "../lib/courses/curriculum";
import { CANONICAL_SOUNDS } from "../lib/sounds/inventory";
import type { ContentItem } from "../lib/search/contentIndex";

const root = process.cwd();
const lexiconDir = path.join(root, "public", "lexicon");
const miniLessonsDir = path.join(root, "public", "mini-lessons");

function readJson<T>(filePath: string): T {
  return JSON.parse(fs.readFileSync(filePath, "utf8")) as T;
}

function titleCase(value: string) {
  return value.replace(/-/g, " ").replace(/\b\w/g, (char) => char.toUpperCase());
}

function createIndex(): ContentItem[] {
  const categories = readJson<Array<{ id: string; name: string; domain?: string }>>(
    path.join(lexiconDir, "index.json"),
  );
  const lexiconCategories = categories.map((category) => ({
    id: `lexicon:${category.id}`,
    type: "lexicon" as const,
    title: category.name,
    tags: ["Lexicon", "Diccionario", ...(category.domain ? [category.domain] : [])],
    description: `Vocabulario de ${category.name}.`,
    path: `/lexicon/${category.id}`,
  }));
  const lexiconWords = categories.flatMap((category) => readJson<Array<{
    id: string; word: string; definition: string; translation?: string; tags: string[];
  }>>(path.join(lexiconDir, `${category.id}.json`)).map((word) => ({
    id: `lexicon-word:${word.id}`,
    type: "lexicon" as const,
    title: word.word,
    tags: ["Lexicon", "Diccionario", category.name, ...word.tags],
    description: word.translation ? `${word.definition} · ${word.translation}` : word.definition,
    path: `/lexicon/${category.id}`,
  })));

  const lessons = fs.readdirSync(miniLessonsDir)
    .filter((file) => file.endsWith(".json"))
    .map((file) => readJson<{
      slug: string; title: string; subtitle: string; body: string; category: string; level: string; href: string;
    }>(path.join(miniLessonsDir, file)))
    .map((lesson) => ({
      id: `lesson:${lesson.slug}`,
      type: "lesson" as const,
      title: lesson.title,
      tags: ["Mini lecciones", titleCase(lesson.category), titleCase(lesson.level)],
      description: lesson.subtitle || lesson.body,
      path: lesson.href,
    }));

  const sounds = CANONICAL_SOUNDS.map((sound) => ({
    id: `sound:${sound.rawSymbol}`,
    type: "sound" as const,
    title: `${sound.symbol} — ${sound.name}`,
    tags: ["Sound Lab", sound.type, sound.category, ...sound.examples],
    description: sound.description,
    path: "/practice/sounds?openIPA=1",
  }));

  const routes = [...COURSE_PATH_CURRICULUM.levels, ...COURSE_PATH_CURRICULUM.electiveTracks]
    .flatMap((level) => level.units.flatMap((unit) => unit.lessons.map((lesson) => ({
      id: `route:${level.id}:${lesson.id}`,
      type: "route" as const,
      title: lesson.title,
      tags: ["Ruta", level.title, level.spineSubtitle, unit.label],
      cefr: (["a1", "a2", "b1", "b2", "c1"] as const).includes(level.id as "a1")
        ? level.id.toUpperCase() as ContentItem["cefr"]
        : undefined,
      description: `${unit.label} de ${level.title}.`,
      path: `/courses/study/${lesson.number}?level=${level.id}`,
    }))));

  return [...lexiconCategories, ...lexiconWords, ...lessons, ...sounds, ...routes];
}

const serializedIndex = JSON.stringify(createIndex());
const output = `import type { ContentItem } from "./contentIndex";\n\n// Generated by scripts/generate-content-index.ts. Do not edit manually.\nexport const CONTENT_INDEX = JSON.parse(${JSON.stringify(serializedIndex)}) as ContentItem[];\n`;
fs.writeFileSync(path.join(root, "lib", "search", "generated-content-index.ts"), output);
