import type { DeckSpec } from "./generate-grammar-pattern-decks";

export const A1_DECK_SPECS: DeckSpec[] = [
  {
    slug: "a1-pronombres-sujeto",
    eyebrow: "A1 · Pronombres",
    title: "Pronombres",
    emphasis: "sujeto",
    goal: "Ya puedes usar I, you, he, she, it, we y they como sujeto de una oración.",
    conceptRows: [
      { key: "I", value: "yo · I am a student.", highlights: ["I"] },
      { key: "you", value: "tú / usted / ustedes · You are here.", highlights: ["You"] },
      { key: "he / she / it", value: "él / ella / objeto o animal · She works.", highlights: ["She"] },
      { key: "we / they", value: "nosotros / ellos · They live here.", highlights: ["They"] },
    ],
    structureRows: [
      { key: "Afirmativo", value: "Sujeto + Verbo · I study English.", highlights: ["I study"] },
      { key: "Negativo", value: "Sujeto + don't/doesn't + Verbo · She does not like tea.", highlights: ["She does not"] },
      { key: "Interrogativo", value: "Auxiliar + Sujeto + Verbo? · Do you speak Spanish?", highlights: ["Do you"] },
    ],
    contextExamples: [
      { key: "Presentación", value: "Hi! I am Alex and she is Sarah." },
      { key: "Rutina diaria", value: "We live in Madrid and they work together." },
      { key: "Clima y lugar", value: "It is cold today, but it is a nice day." },
      { key: "Profesión", value: "He is a doctor and works at the city hospital." },
    ],
    contrastColumns: [
      { label: "I / She / They (Sujeto)", rule: "Realiza la acción antes del verbo", examples: ["I called Maria yesterday."] },
      { label: "me / her / them (Objeto)", rule: "Recibe la acción después del verbo", examples: ["Maria called me yesterday."] },
    ],
    quickReferenceRows: [
      { key: "Sujeto obligatorio", value: "Nunca omitas el pronombre en inglés (ej. It is warm, no Is warm)." },
      { key: "Mayúscula", value: "El pronombre 'I' (yo) siempre se escribe en mayúscula." },
      { key: "You", value: "Sirve tanto para singular (tú/usted) como para plural (ustedes)." },
      { key: "It", value: "Reemplaza cosas, animales, lugares o clima en singular." },
    ],
    mistake: { bad: "Is raining today.", good: "It is raining today.", note: "el sujeto 'It' es obligatorio para el clima" },
    quiz: [
      { q: "___ lives in London with her family.", options: ["She", "Her"], answer: 0, explain: "Antes del verbo va el pronombre sujeto 'She'." },
      { q: "¿Cuál oración es gramaticalmente correcta en inglés?", options: ["Is very warm today.", "It is very warm today."], answer: 1, explain: "En inglés las oraciones sobre el clima requieren el pronombre sujeto 'It'." },
      { q: "___ always study together on weekends.", options: ["We", "Us"], answer: 0, explain: "'We' es el pronombre sujeto correspondiente a 'nosotros'." },
    ],
  },
  {
    slug: "a1-demostrativos",
    eyebrow: "A1 · Demostrativos",
    title: "Demostrativos",
    emphasis: "this, that, these, those",
    goal: "Ya puedes señalar cosas cerca o lejos con this, that, these y those.",
    conceptRows: [
      { key: "this", value: "singular cerca · this book", highlights: ["this"] },
      { key: "that", value: "singular lejos · that car", highlights: ["that"] },
      { key: "these", value: "plural cerca · these shoes", highlights: ["these"] },
      { key: "those", value: "plural lejos · those houses", highlights: ["those"] },
    ],
    structureRows: [
      { key: "Singular + Cerca", value: "This is my key.", highlights: ["This is"] },
      { key: "Singular + Lejos", value: "That is your car over there.", highlights: ["That is"] },
      { key: "Plural + Cerca", value: "These shoes fit me well.", highlights: ["These"] },
      { key: "Plural + Lejos", value: "Those buildings are very old.", highlights: ["Those"] },
    ],
    contextExamples: [
      { key: "En una tienda", value: "How much are these apples in my hand?" },
      { key: "Distante", value: "Look at that bird on top of the tree." },
      { key: "Presentación", value: "This is my friend Marco." },
      { key: "Cosas lejanas", value: "Who owns those bicycles across the street?" },
    ],
    contrastColumns: [
      { label: "This / These (Cerca)", rule: "Objetos que puedes tocar o muy próximos a ti", examples: ["This shirt / These books"] },
      { label: "That / Those (Lejos)", rule: "Objetos alejados o en otra ubicación", examples: ["That star / Those cars"] },
    ],
    quickReferenceRows: [
      { key: "Singular + Cerca", value: "This (Este / Esta / Esto)" },
      { key: "Singular + Lejos", value: "That (Ese / Aquel / Eso)" },
      { key: "Plural + Cerca", value: "These (Estos / Estas)" },
      { key: "Plural + Lejos", value: "Those (Esos / Aquellos)" },
    ],
    mistake: { bad: "This books are new.", good: "These books are new.", note: "books es plural → exige these" },
    quiz: [
      { q: "Can you pass me ___ book on the table over there?", options: ["that", "this"], answer: 0, explain: "El libro está lejos ('over there') y es singular, corresponde 'that'." },
      { q: "___ keys in my hand belong to the office.", options: ["These", "This"], answer: 0, explain: "'keys' es plural y están en la mano (cerca), corresponde 'These'." },
      { q: "¿Cuál frase es correcta al señalar personas a lo lejos?", options: ["Those people are waiting.", "This people are waiting."], answer: 0, explain: "'people' es sustantivo plural y están alejados → 'Those'." },
    ],
  },
  {
    slug: "a1-genitivo-sajon",
    eyebrow: "A1 · Posesión",
    title: "Genitivo sajón",
    emphasis: "'s",
    goal: "Ya puedes expresar posesión con 's: Maria's phone, my brother's car.",
    conceptRows: [
      { key: "persona + 's", value: "Maria's phone · my brother's car", highlights: ["'s"] },
      { key: "plural en -s", value: "the students' books (solo apóstrofo)", highlights: ["students'"] },
      { key: "plural irregular", value: "the children's toys (+ 's)", highlights: ["children's"] },
    ],
    structureRows: [
      { key: "Singular + 's", value: "Paul's car is blue.", highlights: ["Paul's"] },
      { key: "Plural en -s + '", value: "My parents' house is big.", highlights: ["parents'"] },
      { key: "Plural irregular + 's", value: "The children's room is clean.", highlights: ["children's"] },
    ],
    contextExamples: [
      { key: "Familia", value: "My sister's husband is a lawyer." },
      { key: "Pertenencias", value: "Is this David's laptop on the desk?" },
      { key: "Lugares", value: "We met at my uncle's house yesterday." },
      { key: "Plurales", value: "The girls' bedroom is painted blue." },
    ],
    contrastColumns: [
      { label: "Personas / Animales ('s)", rule: "Se añade 's o apóstrofo final", examples: ["John's car / My cat's food"] },
      { label: "Objetos inanimados (of the)", rule: "Se prefiere la construcción con of", examples: ["The leg of the table"] },
    ],
    quickReferenceRows: [
      { key: "Singular", value: "Nombre + 's (Maria's phone)" },
      { key: "Plural regular", value: "Sustantivo en -s + ' (the students' books)" },
      { key: "Plural irregular", value: "Sustantivo plural + 's (the men's coats)" },
      { key: "Pronombres", value: "Los pronombres posesivos no llevan apóstrofo (its, yours, hers)" },
    ],
    mistake: { bad: "The book of Maria.", good: "Maria's book.", note: "en inglés cotidiano de personas se usa siempre 's" },
    quiz: [
      { q: "Where is ___ handbag?", options: ["Sarah's", "Sarah"], answer: 0, explain: "Para indicar posesión de Sarah se añade 's." },
      { q: "This is the ___ playground.", options: ["children's", "childrens'"], answer: 0, explain: "'children' es plural irregular, su posesivo es 'children's'." },
      { q: "¿Cuál opción traduce mejor 'El carro de mi hermano'?", options: ["My brother's car", "The car of my brother"], answer: 0, explain: "'My brother's car' es la forma idiomática en inglés." },
    ],
  },
  {
    slug: "a1-palabras-interrogativas",
    eyebrow: "A1 · Preguntas",
    title: "Palabras",
    emphasis: "interrogativas",
    goal: "Ya puedes preguntar con what, who, where, when, why y how.",
    conceptRows: [
      { key: "What", value: "¿Qué? / ¿Cuál? · What is this?", highlights: ["What"] },
      { key: "Who", value: "¿Quién? · Who is she?", highlights: ["Who"] },
      { key: "Where", value: "¿Dónde? · Where do you live?", highlights: ["Where"] },
      { key: "When / Why / How", value: "¿Cuándo? / ¿Por qué? / ¿Cómo?", highlights: ["When", "Why", "How"] },
    ],
    structureRows: [
      { key: "Estructura general", value: "Wh- Word + Auxiliar + Sujeto + Verbo?", highlights: ["Wh- Word + Auxiliar"] },
      { key: "Con Verbo To Be", value: "Wh- Word + is/are + Sujeto?", highlights: ["Wh- Word + is/are"] },
      { key: "Con Can", value: "Wh- Word + can + Sujeto + Verbo?", highlights: ["Wh- Word + can"] },
    ],
    contextExamples: [
      { key: "Información", value: "What is your favorite food?" },
      { key: "Lugar", value: "Where do you live?" },
      { key: "Tiempo", value: "When does the store open?" },
      { key: "Razón", value: "Why are you learning English?" },
    ],
    contrastColumns: [
      { label: "Who (Persona)", rule: "Pregunta por quién realiza o recibe algo", examples: ["Who is your teacher?"] },
      { label: "What (Cosa / Actividad)", rule: "Pregunta por objetos, datos o acciones", examples: ["What is your plan?"] },
    ],
    quickReferenceRows: [
      { key: "What", value: "Qué / Cuál (cosas o datos)" },
      { key: "Where", value: "Dónde (lugares)" },
      { key: "When", value: "Cuándo (tiempo)" },
      { key: "Who", value: "Quién (personas)" },
      { key: "Why", value: "Por qué (motivos)" },
      { key: "How", value: "Cómo (forma o estado)" },
    ],
    mistake: { bad: "Where you live?", good: "Where do you live?", note: "pregunta con do/does + sujeto + verbo base" },
    quiz: [
      { q: "___ is your English class? - At 9:00 AM.", options: ["When", "Where"], answer: 0, explain: "La respuesta indica la hora (tiempo), corresponde 'When'." },
      { q: "___ is that boy standing near the door?", options: ["Who", "What"], answer: 0, explain: "Se pregunta por una persona ('that boy'), corresponde 'Who'." },
      { q: "¿Cuál pregunta está correctamente estructurada?", options: ["Where does your friend live?", "Where your friend lives?"], answer: 0, explain: "Sigue la fórmula: Wh- word + Auxiliar (does) + Sujeto + Verbo." },
    ],
  },
  {
    slug: "a1-cuanto-cuantos",
    eyebrow: "A1 · Cantidad",
    title: "¿Cuánto?",
    emphasis: "how much / how many",
    goal: "Ya distingues How much (incontable) y How many (contable).",
    conceptRows: [
      { key: "How many", value: "+ plural contable · How many apples?", highlights: ["How many"] },
      { key: "How much", value: "+ incontable · How much water?", highlights: ["How much"] },
      { key: "Precio", value: "How much is this jacket?", highlights: ["How much is"] },
    ],
    structureRows: [
      { key: "How many + Contable", value: "How many books do you read?", highlights: ["How many"] },
      { key: "How much + Incontable", value: "How much sugar do we need?", highlights: ["How much"] },
      { key: "Preguntar Precio", value: "How much is / How much are...?", highlights: ["How much is"] },
    ],
    contextExamples: [
      { key: "Objetos", value: "How many chairs are in the dining room?" },
      { key: "Ingredientes", value: "How much sugar should I put in the coffee?" },
      { key: "Tienda", value: "How much is this leather jacket?" },
      { key: "Tiempo", value: "How much time do we have before the flight?" },
    ],
    contrastColumns: [
      { label: "How many (Contables)", rule: "Para elementos contables en plural", examples: ["How many cars / How many dollars"] },
      { label: "How much (Incontables)", rule: "Para líquidos, masas o conceptos abstractos", examples: ["How much water / How much money"] },
    ],
    quickReferenceRows: [
      { key: "How many", value: "+ sustantivos contables en plural (books, days, cars)" },
      { key: "How much", value: "+ sustantivos incontables (water, rice, time, money)" },
      { key: "Precio", value: "How much is this? / How much are these?" },
      { key: "Respuestas", value: "A lot, a few (contables), a little (incontables)" },
    ],
    mistake: { bad: "How much books?", good: "How many books?", note: "books es contable → many" },
    quiz: [
      { q: "___ milk is left in the fridge?", options: ["How much", "How many"], answer: 0, explain: "'milk' es sustantivo incontable, se pregunta con 'How much'." },
      { q: "___ rooms are there in your apartment?", options: ["How many", "How much"], answer: 0, explain: "'rooms' es plural contable, corresponde 'How many'." },
      { q: "¿Cómo se pregunta el precio de un objeto en una tienda?", options: ["How much is this?", "How many is this?"], answer: 0, explain: "Para preguntar el costo o precio siempre se usa 'How much'." },
    ],
  },
  {
    slug: "a1-presente-continuo",
    eyebrow: "A1 · Presente",
    title: "Presente",
    emphasis: "continuo",
    goal: "Ya puedes describir acciones que pasan ahora con am/is/are + -ing.",
    conceptRows: [
      { key: "I am", value: "I am working right now", highlights: ["am working"] },
      { key: "He / She / It", value: "She is reading a book", highlights: ["is reading"] },
      { key: "We / You / They", value: "They are playing football", highlights: ["are playing"] },
    ],
    structureRows: [
      { key: "Afirmativa", value: "Sujeto + am/is/are + Verbo-ing", highlights: ["am/is/are + -ing"] },
      { key: "Negativa", value: "Sujeto + am not/isn't/aren't + Verbo-ing", highlights: ["isn't/aren't"] },
      { key: "Interrogativa", value: "Am/Is/Are + Sujeto + Verbo-ing?", highlights: ["Am/Is/Are"] },
    ],
    contextExamples: [
      { key: "En casa", value: "I am cooking dinner right now." },
      { key: "Teléfono", value: "Sorry, I can't talk. I am driving." },
      { key: "Trabajo", value: "The manager is meeting with a client at the moment." },
      { key: "Clima", value: "Look outside, it is raining heavily!" },
    ],
    contrastColumns: [
      { label: "Present Continuous (Ahora)", rule: "Acciones sucediendo en este preciso momento", examples: ["I am eating breakfast now."] },
      { label: "Present Simple (Rutina)", rule: "Hábitos y costumbres cotidianas", examples: ["I eat breakfast at 8 every day."] },
    ],
    quickReferenceRows: [
      { key: "I", value: "am + verbo-ing (I am studying)" },
      { key: "He / She / It", value: "is + verbo-ing (He is working)" },
      { key: "We / You / They", value: "are + verbo-ing (We are waiting)" },
      { key: "Señales", value: "now, right now, at the moment, currently" },
    ],
    mistake: { bad: "I working now.", good: "I am working now.", note: "falta el verbo to be antes de -ing" },
    quiz: [
      { q: "Listen! The baby ___ right now.", options: ["is crying", "cries"], answer: 0, explain: "'Listen!' y 'right now' indican una acción sucediendo en el momento → Present Continuous." },
      { q: "What ___ you ___ at the moment?", options: ["are / doing", "do / do"], answer: 0, explain: "Para preguntar por la acción en progreso se usa 'are + sujeto + doing'." },
      { q: "Selecciona la oración correcta:", options: ["They are watching a movie.", "They watching a movie."], answer: 0, explain: "La estructura requiere el auxiliar 'are' antes del verbo en -ing." },
    ],
  },
  {
    slug: "a1-conjunciones-basicas",
    eyebrow: "A1 · Conectores",
    title: "Conjunciones",
    emphasis: "and, but, or, so",
    goal: "Ya puedes unir ideas con and, but, or y so en frases simples.",
    conceptRows: [
      { key: "and", value: "suma de ideas · tea and coffee", highlights: ["and"] },
      { key: "but", value: "contraste · cheap but good", highlights: ["but"] },
      { key: "or", value: "opción · tea or coffee?", highlights: ["or"] },
      { key: "so", value: "consecuencia · tired, so I slept", highlights: ["so"] },
    ],
    structureRows: [
      { key: "Suma (and)", value: "I like apples and oranges.", highlights: ["and"] },
      { key: "Contraste (but)", value: "He is tired, but he keeps working.", highlights: ["but"] },
      { key: "Opción (or)", value: "Would you like tea or coffee?", highlights: ["or"] },
      { key: "Resultado (so)", value: "It was raining, so I took an umbrella.", highlights: ["so"] },
    ],
    contextExamples: [
      { key: "Suma", value: "I love coffee and cake in the morning." },
      { key: "Contraste", value: "She studied hard, but she didn't pass." },
      { key: "Opción", value: "We can walk or take a taxi." },
      { key: "Consecuencia", value: "I was hungry, so I cooked some pasta." },
    ],
    contrastColumns: [
      { label: "but (Contraste)", rule: "Muestra una limitación o diferencia entre dos ideas", examples: ["I want to go, but I am busy."] },
      { label: "so (Resultado)", rule: "Muestra la consecuencia directa de la primera idea", examples: ["I am busy, so I cannot go."] },
    ],
    quickReferenceRows: [
      { key: "and", value: "Añade información adicional" },
      { key: "but", value: "Introduce un contraste o excepción" },
      { key: "or", value: "Presenta una elección entre opciones" },
      { key: "so", value: "Indica el resultado o efecto de algo" },
    ],
    mistake: { bad: "I like tea, and but I prefer coffee.", good: "I like tea, but I prefer coffee.", note: "no combines and con but" },
    quiz: [
      { q: "She was feeling sick, ___ she went to see a doctor.", options: ["so", "but"], answer: 0, explain: "'so' expresa la consecuencia directa de sentirse enferma." },
      { q: "I want to buy a new phone, ___ I don't have enough money.", options: ["but", "or"], answer: 0, explain: "Hay un contraste u obstáculo, corresponde 'but'." },
      { q: "¿Cuál oración es gramaticalmente correcta?", options: ["You can take the bus or walk.", "You can take the bus and but walk."], answer: 0, explain: "Se ofrece una opción limpia entre dos cosas con 'or'." },
    ],
  },
  {
    slug: "a1-contables-incontables",
    eyebrow: "A1 · Sustantivos",
    title: "Contables e",
    emphasis: "incontables",
    goal: "Ya distingues sustantivos que puedes contar de los que van en masa.",
    conceptRows: [
      { key: "Contables", value: "an apple, two apples, many apples", highlights: ["apples"] },
      { key: "Incontables", value: "water, rice, money (sin plural)", highlights: ["water"] },
      { key: "Artículos", value: "a/an con contables singular · some con incontables", highlights: ["some"] },
    ],
    structureRows: [
      { key: "Contable singular", value: "a book / an apple", highlights: ["a/an"] },
      { key: "Contable plural", value: "two books / many apples", highlights: ["-s"] },
      { key: "Incontable", value: "some water / some advice", highlights: ["some"] },
    ],
    contextExamples: [
      { key: "Comida contable", value: "Can I have two eggs and an apple?" },
      { key: "Líquidos", value: "We need to buy some milk and juice." },
      { key: "Información", value: "He gave me useful information about the city." },
      { key: "Conceptos", value: "Money doesn't guarantee happiness." },
    ],
    contrastColumns: [
      { label: "Contables (Plural en -s)", rule: "Tienen forma singular y plural", examples: ["one dollar -> five dollars"] },
      { label: "Incontables (Sin -s)", rule: "No se cuentan con números directos, usan 'some'", examples: ["some money (NUNCA moneys)"] },
    ],
    quickReferenceRows: [
      { key: "Contables", value: "a/an en singular, plural con -s (apples, cars)" },
      { key: "Incontables", value: "usan 'some' en afirmativo, no llevan a/an (water, bread)" },
      { key: "Incontables comunes", value: "water, coffee, bread, money, advice, information" },
      { key: "Medidas", value: "a cup of coffee, a glass of water, a piece of advice" },
    ],
    mistake: { bad: "I need an informations.", good: "I need some information.", note: "information es incontable, usa some" },
    quiz: [
      { q: "Could you give me some ___ about the project?", options: ["information", "informations"], answer: 0, explain: "'information' es incontable y no lleva -s en plural." },
      { q: "We need to buy ___ loaf of bread and some cheese.", options: ["a", "an"], answer: 0, explain: "'loaf' empieza por sonido consonántico, corresponde el artículo 'a'." },
      { q: "Indica cuál grupo contiene SOLO sustantivos incontables:", options: ["Water, rice, money, advice", "Book, car, apple, water"], answer: 0, explain: "Water, rice, money y advice son sustantivos incontables en masa." },
    ],
  },
  {
    slug: "a1-adverbios-frecuencia",
    eyebrow: "A1 · Adverbios",
    title: "Adverbios de",
    emphasis: "frecuencia",
    goal: "Ya colocas always, usually, sometimes y never en la posición correcta.",
    conceptRows: [
      { key: "Frecuencia", value: "always (100%) → usually → often → sometimes → never (0%)", highlights: ["always"] },
      { key: "Verbo normal", value: "I always drink coffee. (antes del verbo)", highlights: ["always drink"] },
      { key: "Verbo To Be", value: "She is always late. (después de be)", highlights: ["is always"] },
    ],
    structureRows: [
      { key: "Verbo ordinario", value: "Sujeto + Adverbio + Verbo", highlights: ["Adverbio + Verbo"] },
      { key: "Verbo To Be", value: "Sujeto + am/is/are + Adverbio", highlights: ["am/is/are + Adverbio"] },
      { key: "Sin doble negativo", value: "I never smoke. (sin don't)", highlights: ["never"] },
    ],
    contextExamples: [
      { key: "Rutina", value: "I usually wake up at 7:00 AM." },
      { key: "Trabajo", value: "He is never late for meetings." },
      { key: "Pasatiempos", value: "We sometimes go to the cinema on Fridays." },
      { key: "Salud", value: "They always drink water after exercising." },
    ],
    contrastColumns: [
      { label: "Antes del verbo ordinario", rule: "Ubicación estándar para la mayoría de los verbos", examples: ["I always eat breakfast."] },
      { label: "Después del verbo To Be", rule: "Ubicación especial obligatoria con am/is/are", examples: ["I am always ready."] },
    ],
    quickReferenceRows: [
      { key: "Escala", value: "Always (100%) > Usually (80%) > Often (60%) > Sometimes (40%) > Never (0%)" },
      { key: "Verbos ordinarios", value: "Colócalo ANTES del verbo (She often calls)" },
      { key: "Verbo To Be", value: "Colócalo DESPUÉS de am/is/are (He is always on time)" },
      { key: "Never", value: "'Never' ya es negativo, no añadas don't/doesn't" },
    ],
    mistake: { bad: "I drink always coffee.", good: "I always drink coffee.", note: "el adverbio va antes del verbo principal" },
    quiz: [
      { q: "Choose the correct sentence:", options: ["She is always happy.", "She always is happy."], answer: 0, explain: "Con el verbo 'to be', el adverbio de frecuencia va DESPUÉS ('is always')." },
      { q: "I ___ eat breakfast before going to work.", options: ["usually", "am usually"], answer: 0, explain: "Con verbos ordinarios ('eat'), el adverbio va antes del verbo." },
      { q: "¿Cuál oración contiene un doble negativo incorrecto?", options: ["I don't never go there.", "I never go there."], answer: 0, explain: "'Never' ya es negativo por sí mismo, no debe combinarse con 'don't'." },
    ],
  },
  {
    slug: "a1-articulos-basicos",
    eyebrow: "A1 · Artículos",
    title: "Artículos básicos",
    emphasis: "a, an y the",
    goal: "Ya distingues cuándo usar a, an, the o ningún artículo.",
    conceptRows: [
      { key: "a", value: "sonido consonántico · a book, a house", highlights: ["a"] },
      { key: "an", value: "sonido vocálico · an apple, an hour", highlights: ["an"] },
      { key: "the", value: "objeto específico o único · the sun, the door", highlights: ["the"] },
    ],
    structureRows: [
      { key: "a + consonante", value: "a book / a university", highlights: ["a"] },
      { key: "an + vocal", value: "an apple / an honest man", highlights: ["an"] },
      { key: "the + específico", value: "the president / the keys on the table", highlights: ["the"] },
    ],
    contextExamples: [
      { key: "Indefinido inicial", value: "I bought a laptop yesterday." },
      { key: "Definido", value: "The laptop is very fast!" },
      { key: "Sonido vocálico", value: "She is an engineer at a tech firm." },
      { key: "Objeto único", value: "The moon looks beautiful tonight." },
    ],
    contrastColumns: [
      { label: "a / an (Cualquiera / Indefinido)", rule: "Se habla de un elemento no especificado por primera vez", examples: ["I need a pen."] },
      { label: "the (Específico / Definido)", rule: "Se habla de algo concreto o ya conocido por ambos", examples: ["Give me the blue pen."] },
    ],
    quickReferenceRows: [
      { key: "a", value: "Sonido consonántico inicial (a dog, a university)" },
      { key: "an", value: "Sonido vocálico inicial (an egg, an hour)" },
      { key: "the", value: "Objeto específico, único o mencionado antes (the sun, the door)" },
      { key: "Sin artículo", value: "Plurales y conceptos generales (I like cats, Water is essential)" },
    ],
    mistake: { bad: "She is a engineer.", good: "She is an engineer.", note: "engineer empieza por sonido vocálico → an" },
    quiz: [
      { q: "He has been waiting for ___ hour.", options: ["an", "a"], answer: 0, explain: "'hour' comienza con sonido vocálico (/aʊər/), por lo que lleva 'an'." },
      { q: "Look at ___ sky, it is going to rain.", options: ["the", "a"], answer: 0, explain: "El cielo es único y específico en este contexto, corresponde 'the'." },
      { q: "¿En cuál opción se usa correctamente el artículo 'a'?", options: ["a university", "an university"], answer: 0, explain: "'University' comienza con el sonido consonántico /j/ ('yoo'), por lo que lleva 'a'." },
    ],
  },
  {
    slug: "a1-can-capacidad-permiso",
    eyebrow: "A1 · Modales",
    title: "Capacidad y permiso",
    emphasis: "can y can't",
    goal: "Ya usas can y can't para expresar habilidad, posibilidad y permiso.",
    conceptRows: [
      { key: "can + verbo", value: "habilidad o permiso · I can swim", highlights: ["can"] },
      { key: "can't + verbo", value: "incapacidad o prohibición · She can't drive", highlights: ["can't"] },
      { key: "Can...?", value: "petición o permiso · Can you help me?", highlights: ["Can"] },
    ],
    structureRows: [
      { key: "Afirmativa", value: "Sujeto + can + Verbo base", highlights: ["can + verbo"] },
      { key: "Negativa", value: "Sujeto + can't + Verbo base", highlights: ["can't + verbo"] },
      { key: "Interrogativa", value: "Can + Sujeto + Verbo base?", highlights: ["Can + Sujeto"] },
    ],
    contextExamples: [
      { key: "Habilidad", value: "He can play the guitar very well." },
      { key: "Permiso", value: "Can I open the window, please?" },
      { key: "Incapacidad", value: "I'm sorry, I can't come to the party tonight." },
      { key: "Petición cortés", value: "Can you repeat that sentence, please?" },
    ],
    contrastColumns: [
      { label: "Can (Habilidad / Permiso)", rule: "Expresa lo que se puede o sabe hacer", examples: ["I can speak English."] },
      { label: "Can't (Imposibilidad / Prohibición)", rule: "Expresa lo que no se puede hacer", examples: ["I can't fly."] },
    ],
    quickReferenceRows: [
      { key: "Sin 'to'", value: "Can va directamente con el verbo base (can speak, no can to speak)" },
      { key: "Sin '-s'", value: "Nunca añade '-s' en tercera persona (He can, no He cans)" },
      { key: "Negativo", value: "can't / cannot" },
      { key: "Pregunta", value: "Can + Sujeto + Verbo base?" },
    ],
    mistake: { bad: "She can to drive.", good: "She can drive.", note: "después de can no se usa to" },
    quiz: [
      { q: "My brother ___ speak three languages fluently.", options: ["can", "cans"], answer: 0, explain: "'can' no añade '-s' en tercera persona." },
      { q: "I'm busy now, so I ___ help you with your homework.", options: ["can't", "can"], answer: 0, explain: "Estar ocupado implica una imposibilidad → 'can't'." },
      { q: "¿Cuál oración tiene una estructura correcta?", options: ["Can you speak slower?", "Can you to speak slower?"], answer: 0, explain: "'Can' se combina directamente con el verbo base sin 'to'." },
    ],
  },
  {
    slug: "a1-plurales",
    eyebrow: "A1 · Sustantivos",
    title: "Sustantivos plurales",
    emphasis: "regulares e irregulares",
    goal: "Ya puedes formar el plural de los sustantivos en inglés correctamente.",
    conceptRows: [
      { key: "+ s", value: "regla general · book → books", highlights: ["books"] },
      { key: "+ es", value: "terminación en -s, -sh, -ch, -x · box → boxes", highlights: ["boxes"] },
      { key: "-ies", value: "consonante + y · city → cities", highlights: ["cities"] },
      { key: "irregulares", value: "cambian de forma · child → children, person → people", highlights: ["children"] },
    ],
    structureRows: [
      { key: "Regla general (+s)", value: "cat → cats / dog → dogs", highlights: ["+s"] },
      { key: "Terminados en -ch/-sh/-x (+es)", value: "watch → watches / bus → buses", highlights: ["+es"] },
      { key: "Consonante + y (-ies)", value: "baby → babies / family → families", highlights: ["-ies"] },
      { key: "Irregulares", value: "man → men / woman → women / person → people", highlights: ["forma propia"] },
    ],
    contextExamples: [
      { key: "Plural regular", value: "I have three cats and two dogs." },
      { key: "Terminados en -es", value: "Put the glasses into the boxes." },
      { key: "Terminados en -ies", value: "There are many big cities in Europe." },
      { key: "Irregulares", value: "The children are playing happily in the park." },
    ],
    contrastColumns: [
      { label: "Plurales regulares", rule: "Forman el plural añadiendo -s, -es o -ies", examples: ["dog -> dogs / box -> boxes"] },
      { label: "Plurales irregulares", rule: "Cambian su raíz y no llevan -s al final", examples: ["child -> children / foot -> feet"] },
    ],
    quickReferenceRows: [
      { key: "Normal", value: "Añade -s (key → keys)" },
      { key: "-es", value: "Palabras terminadas en -s, -sh, -ch, -x (watch → watches)" },
      { key: "-ies", value: "Palabras en consonante + y (city → cities)" },
      { key: "Irregulares clave", value: "child → children, person → people, man → men, woman → women" },
    ],
    mistake: { bad: "There are four persons.", good: "There are four people.", note: "el plural natural de person es people" },
    quiz: [
      { q: "There are many ___ studying at this school.", options: ["children", "childs"], answer: 0, explain: "El plural de 'child' es irregular: 'children'." },
      { q: "She bought two new ___ for her living room.", options: ["watches", "watchs"], answer: 0, explain: "Palabras terminadas en '-ch' forman plural añadiendo '-es'." },
      { q: "¿Cuál de estos pares muestra un plural irregular correcto?", options: ["person → people", "person → persons"], answer: 0, explain: "El plural habitual e idiomático de 'person' es 'people'." },
    ],
  },
  {
    slug: "a1-posesivos",
    eyebrow: "A1 · Posesión",
    title: "Posesivos",
    emphasis: "adjetivos y pronombres",
    goal: "Ya distingues entre adjetivos posesivos (my car) y pronombres (mine).",
    conceptRows: [
      { key: "Adjetivos", value: "my, your, his, her, its, our, their (+ sustantivo)", highlights: ["my"] },
      { key: "Pronombres", value: "mine, yours, his, hers, ours, theirs (van solos)", highlights: ["mine"] },
    ],
    structureRows: [
      { key: "Adjetivo Posesivo + Sustantivo", value: "This is my house.", highlights: ["my house"] },
      { key: "Pronombre Posesivo (solo)", value: "This house is mine.", highlights: ["is mine"] },
    ],
    contextExamples: [
      { key: "Adjetivos", value: "Her father is a doctor and their house is big." },
      { key: "Pronombres", value: "Is this pen yours or mine?" },
      { key: "Objetos / Animales", value: "The dog is eating its food." },
      { key: "Identificación", value: "That red coat isn't hers; it's ours." },
    ],
    contrastColumns: [
      { label: "Adjetivos posesivos (my, your...)", rule: "Van acompañados del sustantivo que poseen", examples: ["This is my book."] },
      { label: "Pronombres posesivos (mine, yours...)", rule: "Reemplazan al sustantivo y van solos", examples: ["This book is mine."] },
    ],
    quickReferenceRows: [
      { key: "my → mine", value: "mi / mío" },
      { key: "your → yours", value: "tu / tuyo" },
      { key: "his → his / her → hers", value: "su / suyo (de él / de ella)" },
      { key: "our → ours / their → theirs", value: "nuestro / suyo (de ellos)" },
    ],
    mistake: { bad: "This house is my.", good: "This house is mine.", note: "my necesita sustantivo; al final va mine" },
    quiz: [
      { q: "Whose jacket is this? - It's ___.", options: ["mine", "my"], answer: 0, explain: "Al no haber sustantivo después del espacio, corresponde el pronombre posesivo 'mine'." },
      { q: "They forgot ___ passports at the hotel.", options: ["their", "theirs"], answer: 0, explain: "Acompaña al sustantivo 'passports', exige el adjetivo posesivo 'their'." },
      { q: "Elige la opción que complete correctamente: 'That car is not ours, it is ___.'", options: ["hers", "her"], answer: 0, explain: "Al no llevar el sustantivo 'car' después, se requiere el pronombre 'hers'." },
    ],
  },
  {
    slug: "a1-preguntas-do-does",
    eyebrow: "A1 · Preguntas",
    title: "Preguntas en presente",
    emphasis: "do y does",
    goal: "Ya puedes formular preguntas en presente con do y does correctamente.",
    conceptRows: [
      { key: "Do", value: "con I / you / we / they · Do you work here?", highlights: ["Do"] },
      { key: "Does", value: "con he / she / it · Does she live nearby?", highlights: ["Does"] },
      { key: "Verbo base", value: "el verbo principal no lleva -s tras does", highlights: ["verbo base"] },
    ],
    structureRows: [
      { key: "Do + Sujeto + Verbo", value: "Do you like coffee?", highlights: ["Do you"] },
      { key: "Does + Sujeto + Verbo", value: "Does he work on Saturdays?", highlights: ["Does he"] },
      { key: "Respuestas cortas", value: "Yes, I do. / No, she doesn't.", highlights: ["Yes, I do"] },
    ],
    contextExamples: [
      { key: "Hábitos", value: "Do you drink coffee every morning?" },
      { key: "Tercera persona", value: "Does your brother work on Saturdays?" },
      { key: "Idiomas", value: "Do they speak English fluently?" },
      { key: "Información", value: "Where does your family live?" },
    ],
    contrastColumns: [
      { label: "Do (I / You / We / They)", rule: "Auxiliar para primera persona y plurales", examples: ["Do you know the answer?"] },
      { label: "Does (He / She / It)", rule: "Auxiliar para tercera persona singular", examples: ["Does he know the answer?"] },
    ],
    quickReferenceRows: [
      { key: "Do", value: "I, you, we, they" },
      { key: "Does", value: "he, she, it" },
      { key: "Verbo principal", value: "Siempre en FORMA BASE (sin -s ni -ing)" },
      { key: "Respuestas cortas", value: "Yes, I do / No, he doesn't" },
    ],
    mistake: { bad: "Does she works here?", good: "Does she work here?", note: "después de does el verbo pierde la -s" },
    quiz: [
      { q: "___ your sister like classical music?", options: ["Does", "Do"], answer: 0, explain: "'your sister' equivale a 'she', exige el auxiliar 'Does'." },
      { q: "Does he ___ to the gym every day?", options: ["go", "goes"], answer: 0, explain: "Con el auxiliar 'Does', el verbo principal vuelve a su forma base ('go')." },
      { q: "¿Cuál respuesta corta es correcta para 'Do you live in Spain?'?", options: ["Yes, I do.", "Yes, I live."], answer: 0, explain: "La respuesta corta estándar en inglés utiliza el auxiliar: 'Yes, I do'." },
    ],
  },
  {
    slug: "a1-preposiciones-lugar-tiempo",
    eyebrow: "A1 · Preposiciones",
    title: "Lugar y tiempo",
    emphasis: "preposiciones básicas in, on, at",
    goal: "Ya usas in, on y at para indicar tiempo y ubicación correctamente.",
    conceptRows: [
      { key: "at", value: "horas y puntos específicos · at 8:00, at home", highlights: ["at"] },
      { key: "on", value: "días, fechas y superficies · on Monday, on the table", highlights: ["on"] },
      { key: "in", value: "meses, años y dentro de espacios · in May, in Madrid", highlights: ["in"] },
    ],
    structureRows: [
      { key: "at + hora / punto", value: "at 8:30 AM / at the door / at night", highlights: ["at"] },
      { key: "on + día / fecha", value: "on Tuesday / on May 5th / on the wall", highlights: ["on"] },
      { key: "in + mes / año / lugar", value: "in August / in 2026 / in the room", highlights: ["in"] },
    ],
    contextExamples: [
      { key: "Horarios", value: "The train leaves at 8:30 AM." },
      { key: "Días y fechas", value: "Our test is on Tuesday morning." },
      { key: "Espacios cerrados", value: "She is waiting in the kitchen." },
      { key: "Meses y países", value: "We are going to travel to Canada in August." },
    ],
    contrastColumns: [
      { label: "at (Punto específico)", rule: "Horas exactas y ubicaciones puntuales", examples: ["at 9:00 AM / at the bus stop"] },
      { label: "in (Espacio / Período amplio)", rule: "Dentro de ciudades, países, meses o años", examples: ["in London / in July"] },
    ],
    quickReferenceRows: [
      { key: "at", value: "horas (at 5:00), at night, at home, at work" },
      { key: "on", value: "días de la semana (on Monday), fechas, superficies" },
      { key: "in", value: "meses, años, estaciones, partes del día (in the morning)" },
    ],
    mistake: { bad: "I will see you in Monday.", good: "I will see you on Monday.", note: "los días de la semana llevan la preposición on" },
    quiz: [
      { q: "Our English class starts ___ 9:00 AM.", options: ["at", "in"], answer: 0, explain: "Para horas específicas se usa la preposición 'at'." },
      { q: "They are getting married ___ June.", options: ["in", "on"], answer: 0, explain: "Para meses del año sin un día concreto se utiliza 'in'." },
      { q: "Selecciona la oración con el uso correcto de preposiciones:", options: ["I was born on July 14th.", "I was born in July 14th."], answer: 0, explain: "Al incluir la fecha completa con el día (July 14th), corresponde 'on'." },
    ],
  },
  {
    slug: "a1-there-is-there-are",
    eyebrow: "A1 · Existencia",
    title: "Existencia y lugar",
    emphasis: "there is y there are",
    goal: "Ya expresas la presencia de objetos y personas con there is y there are.",
    conceptRows: [
      { key: "there is", value: "singular o incontable · There is a table", highlights: ["there is"] },
      { key: "there are", value: "plural · There are two chairs", highlights: ["there are"] },
      { key: "negativo", value: "There isn't a bank / There aren't any eggs", highlights: ["isn't / aren't"] },
    ],
    structureRows: [
      { key: "There is + singular", value: "There is a computer on the desk.", highlights: ["There is a"] },
      { key: "There is + incontable", value: "There is some milk in the fridge.", highlights: ["There is some"] },
      { key: "There are + plural", value: "There are three apples in the basket.", highlights: ["There are"] },
    ],
    contextExamples: [
      { key: "Singular en habitación", value: "There is a large mirror in the bathroom." },
      { key: "Plural en la ciudad", value: "There are many nice cafes in this neighborhood." },
      { key: "Incontable", value: "There is some cold water in the fridge." },
      { key: "Pregunta por servicios", value: "Is there a pharmacy near here?" },
    ],
    contrastColumns: [
      { label: "There is (Singular / Incontable)", rule: "Para 1 solo objeto o masa incontable", examples: ["There is a cat / There is milk"] },
      { label: "There are (Plural)", rule: "Para 2 o más objetos contables", examples: ["There are two cats"] },
    ],
    quickReferenceRows: [
      { key: "There is + a/an", value: "Singular (There is a car)" },
      { key: "There is + some", value: "Incontable (There is some water)" },
      { key: "There are + plural", value: "Plural (There are five books)" },
      { key: "Preguntas", value: "Is there...? / Are there...?" },
    ],
    mistake: { bad: "There is two cars in the garage.", good: "There are two cars in the garage.", note: "plural exige there are" },
    quiz: [
      { q: "___ any apples left in the basket?", options: ["Are there", "Is there"], answer: 0, explain: "'apples' es plural, por lo que la pregunta requiere 'Are there'." },
      { q: "___ a huge park near my new house.", options: ["There is", "There are"], answer: 0, explain: "'a huge park' es singular, se expresa con 'There is'." },
      { q: "Elige la opción que corrige 'Is there two banks on this street?'", options: ["Are there two banks on this street?", "There is two banks on this street?"], answer: 0, explain: "'two banks' es plural y es una pregunta, la forma correcta es 'Are there'." },
    ],
  },
];
