import type { DeckSpec } from "./generate-grammar-pattern-decks";

export const C1_C2_DECK_SPECS: DeckSpec[] = [
  {
    slug: "c1-comparativos-dobles",
    eyebrow: "C1 · Comparativos",
    title: "Comparativos",
    emphasis: "dobles (the … the …)",
    goal: "Expresa relaciones proporcionales de causa-efecto con 'the + comparativo, the + comparativo' (cuanto más X, más Y).",
    conceptRows: [
      { key: "Proporción simple", value: "The older I get, the wiser I become.", highlights: ["The older", "the wiser"] },
      { key: "Con adverbio", value: "The sooner we leave, the better we will feel.", highlights: ["The sooner", "the better"] },
      { key: "Con sustantivo", value: "The more effort you put in, the more progress you make.", highlights: ["The more effort", "the more progress"] },
      { key: "Estructura corta", value: "The bigger, the better.", highlights: ["The bigger", "the better"] },
    ],
    structureRows: [
      { key: "Afirmativa", value: "The + comparativo + sujeto + verbo, the + comparativo + sujeto + verbo · The faster we run, the earlier we arrive.", highlights: ["The faster", "the earlier"] },
      { key: "Negativa", value: "The less you worry, the fewer problems you will encounter.", highlights: ["The less", "the fewer"] },
      { key: "Interrogativa", value: "Is it true that the more you practice, the easier it gets?", highlights: ["the more", "the easier"] },
    ],
    contextExamples: [
      { key: "Desarrollo profesional", value: "The more senior your role becomes, the greater responsibility you carry." },
      { key: "Planificación de viajes", value: "The earlier you book the flights, the cheaper the tickets are." },
      { key: "Toma de decisiones", value: "The longer we hesitate on this strategy, the higher the risk grows." },
      { key: "Salud y bienestar", value: "The more sleep you get during peak stress, the better your focus remains." },
    ],
    contrastColumns: [
      {
        label: "Proporcional (The... the...)",
        rule: "Vincula el cambio progresivo de dos variables",
        examples: ["The higher the demand, the steeper the price."],
      },
      {
        label: "Comparativo estándar (as... as)",
        rule: "Compara dos elementos en un punto fijo de igualdad",
        examples: ["This product is as expensive as the market leader."],
      },
    ],
    quickReferenceRows: [
      { key: "1. Artículo obligatorio", value: "Ambas cláusulas deben comenzar con 'the'." },
      { key: "2. Formas de comparativo", value: "Usa adjetivos en -er, 'more' o 'less' según el tipo de palabra." },
      { key: "3. Orden de palabras", value: "Mantén el orden de sujeto + verbo tras la frase comparativa." },
      { key: "4. Expresiones elípticas", value: "Fórmulas cortas como 'The more, the merrier' son comunes en habla informal." },
    ],
    mistake: { bad: "More you study, more you learn.", good: "The more you study, the more you learn.", note: "Ambas cláusulas requieren 'the' antes del comparativo." },
    quiz: [
      { q: "___ earlier we start the presentation, ___ sooner we can answer questions.", options: ["The / the", "More / more", "As / as", "So / so"], answer: 0, explain: "La estructura de proporcionalidad requiere 'the' en ambas partes del comparativo." },
      { q: "Elige la opción que mejor expresa 'cuanto menos hables, menos errores cometerás':", options: ["The less you speak, the fewer mistakes you will make.", "Less you speak, less mistakes you make.", "The lower you speak, the minor mistakes you do.", "The least you speak, the least mistakes you make."], answer: 0, explain: "'The less' (adverbio) contrasta con 'the fewer' (para sustantivos contables en plural como mistakes)." },
      { q: "¿Cuál es la estructura gramatical correcta para una oración comparativa doble?", options: ["The + comparativo + sujeto + verbo, the + comparativo + sujeto + verbo", "The + sujeto + comparativo, the + verbo + comparativo", "Comparativo + the + sujeto, comparativo + the + verbo", "More + adjetivo + sujeto, less + adjetivo + verbo"], answer: 0, explain: "La regla establece poner 'the' seguido inmediatamente del término comparativo al inicio de cada cláusula." },
    ],
  },
  {
    slug: "c1-relativas-complejas",
    eyebrow: "C1 · Relativas",
    title: "Estructuras",
    emphasis: "relativas complejas",
    goal: "Empaqueta información densa mediante relativas reducidas, preposición inicial (fronting) y relativas subordinadas encajadas.",
    conceptRows: [
      { key: "Relativa reducida (pasiva)", value: "The audit conducted last month revealed several discrepancies.", highlights: ["conducted"] },
      { key: "Relativa reducida (activa)", value: "Engineers working on the project need clear instructions.", highlights: ["working"] },
      { key: "Preposición inicial (formal)", value: "The client to whom we addressed the proposal accepted the terms.", highlights: ["to whom"] },
      { key: "Cuantificador + of which/whom", value: "We reviewed ten applications, three of which met all criteria.", highlights: ["three of which"] },
    ],
    structureRows: [
      { key: "Afirmativa (Preposición inicial)", value: "Sujeto + preposición + whom/which + sujeto + verbo... · The vehicle in which they traveled was inspected.", highlights: ["in which"] },
      { key: "Negativa (Participio reducido)", value: "Products not meeting safety standards will be recalled.", highlights: ["not meeting"] },
      { key: "Interrogativa (Formal)", value: "Is this the framework to which you were referring during the debate?", highlights: ["to which"] },
    ],
    contextExamples: [
      { key: "Informes ejecutivos", value: "The guidelines published by the regulator require full compliance by Q4." },
      { key: "Negociaciones comerciales", value: "The firm with which we partnered has expanded into international markets." },
      { key: "Académico", value: "Research conducted across five universities demonstrates a strong correlation." },
      { key: "Gestión de proyectos", value: "We identified four major risks, all of which can be mitigated." },
    ],
    contrastColumns: [
      {
        label: "Preposición al inicio (Formal / C1)",
        rule: "La preposición va antes de 'whom' o 'which', eliminando informalidades",
        examples: ["The person with whom I negotiated the contract was extremely thorough."],
      },
      {
        label: "Preposición pospuesta (Informal / B1-B2)",
        rule: "La preposición queda al final de la cláusula de relativo",
        examples: ["The person I negotiated the contract with was very friendly."],
      },
    ],
    quickReferenceRows: [
      { key: "1. Pronombres de objeto", value: "Usa 'whom' para personas tras preposición ('to whom', 'with whom'). NUNCA 'to who'." },
      { key: "2. Omisión de que/quien", value: "En cláusulas reducidas se omite 'who is/which was' dejando solo el participio (-ing / -ed)." },
      { key: "3. Sin repetición de pronombre", value: "No repitas el pronombre objeto (ej. 'the man who I saw him')." },
      { key: "4. Cuantificadores", value: "Estructuras como 'some of which', 'neither of whom' aportan precisión cuantitativa." },
    ],
    mistake: { bad: "The manager who I talked to him yesterday approved the vacation.", good: "The manager to whom I talked yesterday approved the vacation.", note: "No dupliques el pronombre objeto ('him') en una oración relativa." },
    quiz: [
      { q: "The policy ___ last year has significantly reduced operating costs.", options: ["implemented", "implementing", "which implemented it", "that being implemented"], answer: 0, explain: "'Implemented' es una cláusula relativa reducida pasiva (abreviación de 'which was implemented')." },
      { q: "We interviewed five candidates, two of ___ had extensive experience abroad.", options: ["whom", "who", "which", "them"], answer: 0, explain: "Tras la preposición 'of' al referirse a personas se requiere 'whom'." },
      { q: "¿Qué opción es la más apropiada para un registro académico formal?", options: ["The subjects to which we turned our attention were highly complex.", "The subjects which we turned our attention to them were hard.", "The subjects that we turned our attention to were hard.", "The subjects where we turned our attention were complex."], answer: 0, explain: "La estructura 'preposición + which' evita terminar la frase con preposición y elimina pronombres redundantes." },
    ],
  },
  {
    slug: "c1-verbos-delexicales",
    eyebrow: "C1 · Colocaciones",
    title: "Verbos",
    emphasis: "delexicales",
    goal: "Utiliza verbos delexicales (make, do, take, have, give, pay) combinados con sustantivos para expresar acciones de forma natural.",
    conceptRows: [
      { key: "make (crear/decidir)", value: "make a recommendation · make progress · make a decision", highlights: ["make"] },
      { key: "do (ejecutar/trabajar)", value: "do research · do business · do an assignment", highlights: ["do"] },
      { key: "take (adoptar/asumir)", value: "take measures · take responsibility · take a stance", highlights: ["take"] },
      { key: "have & give (acciones)", value: "have an impact on · give priority to · pay attention to", highlights: ["have", "give", "pay"] },
    ],
    structureRows: [
      { key: "Afirmativa", value: "Sujeto + verbo delexical + sustantivo + complemento · The board made a strategic decision.", highlights: ["made a strategic decision"] },
      { key: "Negativa", value: "They did not take any precautions prior to the system update.", highlights: ["take any precautions"] },
      { key: "Interrogativa", value: "Has the team done research on market trends?", highlights: ["done research"] },
    ],
    contextExamples: [
      { key: "Liderazgo corporativo", value: "Executives must take full responsibility for corporate compliance." },
      { key: "Investigación científica", value: "Our team is doing extensive research into renewable energy sources." },
      { key: "Consultoría estratégica", value: "We made a formal recommendation to restructure the department." },
      { key: "Análisis de mercado", value: "The new tax regulation will have a direct impact on small businesses." },
    ],
    contrastColumns: [
      {
        label: "Make vs. Do",
        rule: "'Make' se enfoca en decisiones, planes y resultados; 'Do' en tareas, obligaciones y estudios",
        examples: ["make an arrangement", "do a thorough analysis"],
      },
      {
        label: "Verbo simple vs. Delexical",
        rule: "El verbo delexical enfatiza la naturaleza de la acción mediante un adjetivo modificador",
        examples: ["decide vs. make a firm decision"],
      },
    ],
    quickReferenceRows: [
      { key: "1. Colocaciones fijas", value: "Los verbos delexicales pierden su significado literal y forman un núcleo idiomático con el sustantivo." },
      { key: "2. Modificación adjetival", value: "Permiten añadir adjetivos fácilmente (ej. 'take immediate action' en lugar de 'act immediately')." },
      { key: "3. 'Make' para acuerdos", value: "Usado para 'make a decision', 'make an offer', 'make a complaint'." },
      { key: "4. 'Do' para tareas", value: "Usado para 'do research', 'do business', 'do damage'." },
    ],
    mistake: { bad: "The committee did a decision after hours of debate.", good: "The committee made a decision after hours of debate.", note: "'Decision' se combina exclusivamente con 'make', no con 'do'." },
    quiz: [
      { q: "The government decided to ___ immediate action to curb inflation.", options: ["take", "make", "do", "perform"], answer: 0, explain: "'Take action' (tomar medidas/acción) es la colocación delexical correcta." },
      { q: "Our analysts have ___ substantial research into consumer trends.", options: ["done", "made", "taken", "given"], answer: 0, explain: "'Research' se combina con el verbo 'do' (do research)." },
      { q: "¿Cuál de las siguientes oraciones utiliza una colocación delexical natural?", options: ["The new policy will have a profound effect on productivity.", "The new policy will make a profound effect on productivity.", "The new policy will do a profound effect on productivity.", "The new policy will perform a profound effect on productivity."], answer: 0, explain: "'Have an effect / impact on' es la estructura fija delexical idónea." },
    ],
  },
  {
    slug: "c1-marcadores-discurso",
    eyebrow: "C1 · Discurso",
    title: "Marcadores",
    emphasis: "del discurso",
    goal: "Estructura argumentos complejos y transiciones académicas usando marcadores avanzados (notwithstanding, in so far as, conversely).",
    conceptRows: [
      { key: "Concesión formal", value: "Notwithstanding the economic downturn, investment remained high.", highlights: ["Notwithstanding"] },
      { key: "Limitación / Alcance", value: "In so far as budget allows, we will expand the team.", highlights: ["In so far as"] },
      { key: "Reformulación", value: "To put it another way, we are shifting our focus to retention.", highlights: ["To put it another way"] },
      { key: "Contraste directo", value: "Conversely, secondary markets demonstrated unexpected growth.", highlights: ["Conversely"] },
    ],
    structureRows: [
      { key: "Afirmativa (Concesión)", value: "Marcador + sustantivo / cláusula, sujeto + verbo · Notwithstanding initial delays, the project succeeded.", highlights: ["Notwithstanding"] },
      { key: "Afirmativa (Alcance)", value: "In so far as + sujeto + verbo, la consecuencia lógica procede.", highlights: ["In so far as"] },
      { key: "Afirmativa (Reformulación)", value: "Cláusula principal. Marcador de reformulación, síntesis aclaratoria.", highlights: ["To put it another way"] },
    ],
    contextExamples: [
      { key: "Ensayos y publicaciones", value: "Conversely, earlier studies suggested that the phenomenon was temporary." },
      { key: "Informes de gestión", value: "In so far as we can ascertain from the data, the strategy is working." },
      { key: "Reuniones estratégicas", value: "To put it another way, failing to innovate will cost us market share." },
      { key: "Debates formales", value: "Notwithstanding your objections, the board has approved the budget." },
    ],
    contrastColumns: [
      {
        label: "Notwithstanding vs. Although",
        rule: "'Notwithstanding' es formal y admite sustantivos directos o cláusulas; 'Although' introduce cláusulas completas",
        examples: ["Notwithstanding the heavy rain...", "Although it rained heavily..."],
      },
      {
        label: "Conversely vs. However",
        rule: "'Conversely' señala una inversión opuesta o simétrica; 'However' introduce cualquier tipo de salvedad o matiz",
        examples: ["Imports fell; conversely, exports rose.", "The plan is solid. However, costs are high."],
      },
    ],
    quickReferenceRows: [
      { key: "1. Posición oracional", value: "La mayoría de marcadores avanzados se separan con coma al inicio de la oración." },
      { key: "2. Registro formal", value: "Reserva 'notwithstanding' y 'conversely' para redacción profesional, académica o presentaciones." },
      { key: "3. Evitar redundancias", value: "No uses dos conectores de concesión juntos (ej. 'Notwithstanding this, but...')." },
      { key: "4. Claridad en la voz", value: "'To put it another way' simplifica conceptos complejos para la audiencia." },
    ],
    mistake: { bad: "Notwithstanding the failure, but we learned valuable lessons.", good: "Notwithstanding the failure, we learned valuable lessons.", note: "No combines 'notwithstanding' con 'but' en la misma oración." },
    quiz: [
      { q: "___ the challenges in supply chain, sales exceeded expectations.", options: ["Notwithstanding", "In order to", "Unless", "As long as"], answer: 0, explain: "'Notwithstanding' funciona como preposición formal equivalente a 'a pesar de'." },
      { q: "The first experiment failed; ___, the second trial produced outstanding results.", options: ["conversely", "whereas", "in order that", "so as to"], answer: 0, explain: "'Conversely' vincula dos resultados simétricamente opuestos." },
      { q: "¿Qué marcador expresa una reformulación explicativa para aclarar un punto previo?", options: ["To put it another way", "Notwithstanding this", "In so far as", "Conversely"], answer: 0, explain: "'To put it another way' se utiliza para refrasear o clarificar una idea." },
    ],
  },
  {
    slug: "c1-anteposicion-enfasis",
    eyebrow: "C1 · Énfasis",
    title: "Anteposición",
    emphasis: "para énfasis",
    goal: "Mueve complementos directos o adverbiales al inicio de la oración (fronting) para generar relieve temático o contraste dramático.",
    conceptRows: [
      { key: "Anteposición de complemento", value: "This final clause, we cannot accept under any circumstance.", highlights: ["This final clause"] },
      { key: "Anteposición adverbial negativa", value: "Under no circumstances should confidential files be shared.", highlights: ["Under no circumstances"] },
      { key: "Anteposición adjetival", value: "Talented though she is, she still requires ongoing coaching.", highlights: ["Talented though she is"] },
      { key: "Contraste temático", value: "The hardware we can replace; the lost data is gone forever.", highlights: ["The hardware"] },
    ],
    structureRows: [
      { key: "Afirmativa (Sin inversión)", value: "Objeto/Complemento + Sujeto + Verbo · Excellent results they produced.", highlights: ["Excellent results", "they produced"] },
      { key: "Afirmativa (Con inversión negativa)", value: "Expresión negativa + Auxiliar + Sujeto + Verbo principal · Rarely have I seen such dedication.", highlights: ["Rarely have I seen"] },
      { key: "Interrogativa enfática", value: "On no account must any user disclose their credentials?", highlights: ["On no account must"] },
    ],
    contextExamples: [
      { key: "Discursos y presentaciones", value: "Not a single detail did the auditor overlook during the inspection." },
      { key: "Negociaciones exigentes", value: "Such conditions we have never agreed to in past contracts." },
      { key: "Redacción periodística", value: "Hard work it was, but the team persevered until final delivery." },
      { key: "Comunicación corporativa", value: "The financial risk we anticipated; the regulatory change caught us off guard." },
    ],
    contrastColumns: [
      {
        label: "Fronting directo (Sin inversión)",
        rule: "Trae el objeto al inicio manteniendo orden Sujeto + Verbo para destacar el tema",
        examples: ["All these proposals we have carefully evaluated."],
      },
      {
        label: "Fronting negativo (Con inversión)",
        rule: "Expresiones restrictivas/negativas fuerzan el orden Auxiliar + Sujeto + Verbo",
        examples: ["Under no circumstances can we evaluate those proposals."],
      },
    ],
    quickReferenceRows: [
      { key: "1. Regla de inversión", value: "Si el elemento antepuesto es negativo ('Never', 'Seldom', 'Under no circumstances'), requiere inversión." },
      { key: "2. Sin pronombres extra", value: "No repitas el objeto con un pronombre (ej. 'This document we signed it')." },
      { key: "3. Uso con 'though / as'", value: "Estructuras como 'Difficult as it was' mueven el adjetivo al inicio." },
      { key: "4. Impacto retórico", value: "Utilízalo con moderación para resaltar contrastes clave en discursos formales." },
    ],
    mistake: { bad: "This proposal we cannot accept it.", good: "This proposal we cannot accept.", note: "Al anteponer el objeto ('This proposal'), elimina el pronombre redundante ('it')." },
    quiz: [
      { q: "___ should employee data be modified without authorization.", options: ["On no account", "In spite of", "With a view to", "As a matter of fact"], answer: 0, explain: "'On no account' al inicio desencadena inversión del auxiliar y expresa prohibición estricta." },
      { q: "The initial investment we managed; the recurring fees ___.", options: ["we could not afford", "could not afford we", "we could not afford them", "afforded we not"], answer: 0, explain: "La anteposición del complemento conserva el orden sujeto + verbo ('we could not afford') sin pronombre redundante." },
      { q: "Selecciona la oración con la anteposición y concordancia correctas:", options: ["Rarely has the company faced such stiff competition.", "Rarely the company has faced such stiff competition.", "Rarely has faced the company such stiff competition.", "Rarely faced the company such stiff competition."], answer: 0, explain: "'Rarely' exige auxiliar antes del sujeto ('has the company faced')." },
    ],
  },
  {
    slug: "c1-futuro-en-pasado",
    eyebrow: "C1 · Tiempo",
    title: "Futuro",
    emphasis: "en el pasado",
    goal: "Describe planes, intenciones o eventos que eran futuros desde una perspectiva del pasado usando 'was/were going to', 'would' y 'was to'.",
    conceptRows: [
      { key: "Intención no cumplida", value: "I was going to call you, but my battery died.", highlights: ["was going to call"] },
      { key: "Predicción / Destino", value: "Little did they know that this decision would change the industry.", highlights: ["would change"] },
      { key: "Acuerdo / Plan formal", value: "The signing was to take place on Monday, but was delayed.", highlights: ["was to take place"] },
      { key: "A punto de suceder", value: "The meeting was about to start when the alarm went off.", highlights: ["was about to start"] },
    ],
    structureRows: [
      { key: "Afirmativa (Plan)", value: "Sujeto + was/were going to + verbo base · We were going to launch in May.", highlights: ["were going to launch"] },
      { key: "Negativa (Predicción)", value: "Sujeto + would not + verbo base · They believed prices would not increase.", highlights: ["would not increase"] },
      { key: "Interrogativa (Discurso indirecto)", value: "Did she mention when the train was to arrive?", highlights: ["was to arrive"] },
    ],
    contextExamples: [
      { key: "Gestión de imprevistos", value: "We were going to release the feature today, but identified a critical bug." },
      { key: "Narrativa estratégica", value: "He knew the venture would involve risk, yet he pursued it relentlessly." },
      { key: "Revisión de proyectos", value: "The contract was to be signed last week, but legal required amendments." },
      { key: "Eventos inminentes", value: "I was about to submit the report when new data arrived." },
    ],
    contrastColumns: [
      {
        label: "Was/Were going to",
        rule: "Se usa para intenciones o planes pasados que a menudo se vieron interrumpidos o cambiaron",
        examples: ["I was going to travel, but I fell ill."],
      },
      {
        label: "Would",
        rule: "Se usa para predicciones o eventos futuros vistos desde una perspectiva pasada (estilo indirecto)",
        examples: ["She promised she would deliver the final report by Friday."],
      },
    ],
    quickReferenceRows: [
      { key: "1. 'Going to' para planes", value: "Indica una intención previa que con frecuencia no llegó a realizarse." },
      { key: "2. 'Would' para certezas/futuro", value: "Funciona como el futuro del pasado en narrativas y estilo indirecto." },
      { key: "3. 'Was/Were to'", value: "Indica planes formales o eventos predeterminados en registros oficiales." },
      { key: "4. 'Was about to'", value: "Resalta la inminencia de una acción justo antes de ser interrumpida." },
    ],
    mistake: { bad: "I was going to called him yesterday.", good: "I was going to call him yesterday.", note: "Tras 'was going to', el verbo debe permanecer en su forma base infinitiva." },
    quiz: [
      { q: "We ___ to announce the merger yesterday, but the board requested more time.", options: ["were going", "would", "are going", "will"], answer: 0, explain: "Para planes o intenciones pasadas interrumpidas se usa 'were going to'." },
      { q: "She assured us that the shipment ___ arrive before the weekend.", options: ["would", "was going", "is to", "will be"], answer: 0, explain: "En estilo indirecto sobre una promesa futura desde el pasado se emplea 'would'." },
      { q: "¿Qué estructura formal indica un acuerdo o plan institucional pasado?", options: ["The ceremony was to begin at noon.", "The ceremony will begin at noon.", "The ceremony was going begin at noon.", "The ceremony would to begin at noon."], answer: 0, explain: "'Was/Were to + infinitivo' expresa compromisos u órdenes organizadas en el pasado." },
    ],
  },
  {
    slug: "c1-matices-modales",
    eyebrow: "C1 · Modales",
    title: "Matices",
    emphasis: "modales",
    goal: "Domina usos avanzados de auxiliares modales para expresar hábitos típicos (will/would) y concesiones/especulación (may/might).",
    conceptRows: [
      { key: "Will (Tendencia / Hábito presente)", value: "She will spend hours analyzing spreadsheets without taking a break.", highlights: ["will spend"] },
      { key: "Would (Hábito característico pasado)", value: "My old mentor would always double-check every figure.", highlights: ["would always double-check"] },
      { key: "May / Might (Concesión)", value: "The price may be steep, but the quality is undeniable.", highlights: ["may be"] },
      { key: "Should (Expectativa / Deducción)", value: "The software update should solve the performance issues.", highlights: ["should solve"] },
    ],
    structureRows: [
      { key: "Afirmativa (Tendencia)", value: "Sujeto + will/would + verbo base · He will insist on reviewing every line.", highlights: ["will insist"] },
      { key: "Negativa (Concesión matizada)", value: "This option might not be cheap, but it offers full coverage.", highlights: ["might not be"] },
      { key: "Interrogativa (Deducción)", value: "Should the package arrive before Friday?", highlights: ["Should the package arrive"] },
    ],
    contextExamples: [
      { key: "Observaciones de comportamiento", value: "Clients will often demand last-minute changes during the final phase." },
      { key: "Reminisciencia profesional", value: "In the early days of the start-up, we would work long into the night." },
      { key: "Análisis de propuestas", value: "That argument may hold true in theory, but in practice it fails." },
      { key: "Proyecciones corporativas", value: "The revised strategy should generate positive returns by next quarter." },
    ],
    contrastColumns: [
      {
        label: "Will/Would (Hábito)",
        rule: "No indica futuro ni condicional, sino una conducta característica o patronal",
        examples: ["He will sit there in silence for hours."],
      },
      {
        label: "May/Might (Concesión)",
        rule: "Admite la veracidad de un punto antes de presentar un contraste determinante",
        examples: ["It may sound risky, but it is necessary."],
      },
    ],
    quickReferenceRows: [
      { key: "1. 'Will' característico", value: "Se enfatiza verbalmente para expresar irritación o patrones de conducta habituales." },
      { key: "2. 'Would' de costumbre", value: "Equivale a 'used to' para acciones repetidas en el pasado (no para estados)." },
      { key: "3. Concesión estratégica", value: "Usa 'may... but...' en debates para validar al interlocutor antes de rebatir." },
      { key: "4. Expectativas lógicas", value: "'Should' expresa la suposición razonable de que algo ocurrirá según lo planeado." },
    ],
    mistake: { bad: "She will to complain whenever we change the schedule.", good: "She will complain whenever we change the schedule.", note: "Los modales como 'will' van seguidos de infinitivo sin 'to'." },
    quiz: [
      { q: "During negotiations, buyers ___ often test your boundaries before making a real offer.", options: ["will", "must to", "ought", "shall to"], answer: 0, explain: "'Will' se utiliza para señalar una tendencia o hábito característico del presente." },
      { q: "The initial investment ___ be substantial, but the long-term ROI justifies it.", options: ["may", "would", "should to", "had to"], answer: 0, explain: "'May' introduce una concesión (reconocer un hecho antes de matizarlo con 'but')." },
      { q: "¿Qué opción describe correctamente un comportamiento repetido en el pasado?", options: ["When we worked together, he would always share his insights.", "When we worked together, he will always share his insights.", "When we worked together, he is used to share his insights.", "When we worked together, he would to share his insights."], answer: 0, explain: "'Would' expresa hábitos recurrentes en el pasado." },
    ],
  },
  {
    slug: "c1-phrasal-verbs-avanzados",
    eyebrow: "C1 · Phrasal verbs",
    title: "Phrasal verbs",
    emphasis: "avanzados",
    goal: "Aplica phrasal verbs de tres partes, inseparables e idiomáticos avanzados en contextos profesionales y de alta precisión.",
    conceptRows: [
      { key: "Tres partes (Inseparable)", value: "come up against stiff competition · run up against obstacle", highlights: ["come up against"] },
      { key: "Afrontar / Tolerar", value: "put up with continuous delays · face up to consequences", highlights: ["put up with", "face up to"] },
      { key: "Reducir / Cancelar", value: "cut back on expenses · call off negotiations", highlights: ["cut back on", "call off"] },
      { key: "Surgir / Proponer", value: "come up with an innovative solution · bring about change", highlights: ["come up with", "bring about"] },
    ],
    structureRows: [
      { key: "Afirmativa (3 partículas)", value: "Sujeto + verbo + partícula 1 + partícula 2 + objeto · We need to come up with new ideas.", highlights: ["come up with"] },
      { key: "Negativa (Con pronombre)", value: "They didn't turn it down immediately.", highlights: ["turn it down"] },
      { key: "Interrogativa", value: "How did you manage to get away with such a risky move?", highlights: ["get away with"] },
    ],
    contextExamples: [
      { key: "Gestión presupuestaria", value: "We must cut back on non-essential expenditures during the crisis." },
      { key: "Resolución de problemas", value: "The engineering team came up with a brilliant workaround." },
      { key: "Gestión de clientes", value: "We cannot put up with such poor service quality any longer." },
      { key: "Estrategia corporativa", value: "The new leadership aims to bring about a cultural transformation." },
    ],
    contrastColumns: [
      {
        label: "Separable con pronombre",
        rule: "Si el objeto es un pronombre (it/them), DEBE ir obligatoriamente entre el verbo y la partícula",
        examples: ["We turned down the offer. / We turned it down."],
      },
      {
        label: "Tres partes (Inseparable)",
        rule: "Las tres palabras forman un bloque indivisible; el objeto va siempre al final",
        examples: ["I look forward to your reply. / I look forward to it."],
      },
    ],
    quickReferenceRows: [
      { key: "1. Regla de pronombres", value: "En verbos separables de 2 partes: 'turn it down' (correcto), NO 'turn down it'." },
      { key: "2. Verbos de 3 partes", value: "Nunca separes las partículas de verbos como 'look forward to' o 'put up with'." },
      { key: "3. Estilo profesional", value: "Usa phrasals avanzados para matizar registros sin sonar excesivamente rígido." },
      { key: "4. Gerundio tras preposición", value: "La última partícula es preposición; usa verbo en -ing ('look forward to meeting')." },
    ],
    mistake: { bad: "I look forward to hear from you soon.", good: "I look forward to hearing from you soon.", note: "En 'look forward to', 'to' es una preposición que requiere sustantivo o gerundio (-ing)." },
    quiz: [
      { q: "The legal department decided to ___ the proposal after reviewing the terms.", options: ["turn down", "turn it down to", "turn off to", "turn away with"], answer: 0, explain: "'Turn down' significa rechazar una oferta o propuesta." },
      { q: "It took the committee weeks to ___ a viable strategy for restructuring.", options: ["come up with", "come with up", "come out to", "come in with"], answer: 0, explain: "'Come up with' es un phrasal verb de tres partes inseparable que significa idear o proponer." },
      { q: "¿Cuál es la colocación correcta utilizando el pronombre 'it'?", options: ["We decided to phase it out over two years.", "We decided to phase out it over two years.", "We decided to phase it out of over two years.", "We decided to phase out of it over two years."], answer: 0, explain: "Con verbos separables, los pronombres objeto van entre el verbo y la partícula ('phase it out')." },
    ],
  },
  {
    slug: "c1-subjuntivo-formal",
    eyebrow: "C1 · Subjuntivo",
    title: "Subjuntivo",
    emphasis: "formal",
    goal: "Emplea el subjuntivo mandativo (forma base sin flexión de persona) tras verbos y adjetivos de demanda, insistencia o sugerencia.",
    conceptRows: [
      { key: "Verbos de demanda/sugerencia", value: "suggest · insist · demand · recommend · propose · require", highlights: ["insist", "demand"] },
      { key: "Forma base universal", value: "They insisted that he be present during the audit.", highlights: ["that he be"] },
      { key: "Tercera persona sin -s", value: "The committee recommended that she head the new department.", highlights: ["she head"] },
      { key: "Adjetivos impersonales", value: "It is essential that every member sign the non-disclosure agreement.", highlights: ["It is essential that", "sign"] },
    ],
    structureRows: [
      { key: "Afirmativa", value: "Sujeto + verbo de demanda + that + sujeto + forma base · I propose that he join the board.", highlights: ["that he join"] },
      { key: "Negativa", value: "Sujeto + verbo + that + sujeto + NOT + forma base · She asked that they not discuss the deal.", highlights: ["that they not discuss"] },
      { key: "Pasiva subjuntiva", value: "It is imperative that the guidelines be followed strictly.", highlights: ["be followed"] },
    ],
    contextExamples: [
      { key: "Gobernanza corporativa", value: "The auditors requested that all financial logs be audited independently." },
      { key: "Protocolos de seguridad", value: "It is vital that no unverified personnel enter the laboratory." },
      { key: "Políticas internas", value: "Management insists that every employee attend the compliance workshop." },
      { key: "Contratos formales", value: "The contract mandates that the tenant pay rent on the first of each month." },
    ],
    contrastColumns: [
      {
        label: "Subjuntivo formal (C1 / US / Formal UK)",
        rule: "Usa la forma base del verbo para todas las personas, sin '-s' en 3ª persona ni tiempos pasados",
        examples: ["We demand that he resign immediately."],
      },
      {
        label: "Should + Infinitivo (UK Estándar)",
        rule: "Inserta 'should' antes del verbo principal como alternativa formal",
        examples: ["We demand that he should resign immediately."],
      },
    ],
    quickReferenceRows: [
      { key: "1. Sin conjugación de 3ª persona", value: "NUNCA añadas '-s' al verbo en la cláusula que sigue a 'that' (ej. 'he remain')." },
      { key: "2. Negación con 'not'", value: "La negación se forma simplemente colocando 'not' antes de la forma base ('that he not leave')." },
      { key: "3. Uso del verbo 'to be'", value: "El verbo 'to be' utiliza la forma 'be' para todas las personas ('that I be', 'that he be')." },
      { key: "4. Omisión opcional de 'that'", value: "En contextos sumamente formales se mantiene 'that'; omitirlo resta formalidad." },
    ],
    mistake: { bad: "The manager recommended that she accepts the promotion.", good: "The manager recommended that she accept the promotion.", note: "En el subjuntivo mandativo se utiliza la forma base 'accept', no la tercera persona 'accepts'." },
    quiz: [
      { q: "The board of directors required that the CEO ___ a revised budget by tomorrow.", options: ["submit", "submits", "submitted", "has submitted"], answer: 0, explain: "Tras el verbo de exigencia 'require that' se debe utilizar la forma base 'submit'." },
      { q: "It is crucial that confidential records ___ stored on unsecured servers.", options: ["not be", "be not", "are not", "to not be"], answer: 0, explain: "La negación del subjuntivo se construye situando 'not' antes de la forma base 'be'." },
      { q: "¿Cuál de las siguientes frases representa el subjuntivo formal correcto?", options: ["The judge ordered that the evidence be suppressed.", "The judge ordered that the evidence is suppressed.", "The judge ordered that the evidence was suppressed.", "The judge ordered that the evidence to be suppressed."], answer: 0, explain: "'Be suppressed' es la forma pasiva en subjuntivo (be + participio)." },
    ],
  },
  {
    slug: "c1-pasado-irreal-avanzado",
    eyebrow: "C1 · Pasado irreal",
    title: "Pasado irreal",
    emphasis: "avanzado",
    goal: "Expresa situaciones hipotéticas, deseos o arrepentimientos usando 'wish', 'if only', 'it's time' y 'would rather' con tiempos pasados.",
    conceptRows: [
      { key: "Wish / If only + Past Perfect", value: "I wish we had secured the intellectual property earlier.", highlights: ["had secured"] },
      { key: "Wish + Would (Queja/Cambio)", value: "I wish the regulations would stabilize.", highlights: ["would stabilize"] },
      { key: "It's high time + Past Simple", value: "It's high time the government revised the tax code.", highlights: ["revised"] },
      { key: "Would rather + Past Simple", value: "I'd rather we discussed this matter in private.", highlights: ["we discussed"] },
    ],
    structureRows: [
      { key: "Afirmativa (Arrepentimiento)", value: "Sujeto + wish + (that) + sujeto + past perfect · I wish I had known.", highlights: ["had known"] },
      { key: "Afirmativa (Urgencia social)", value: "It is (high/about) time + sujeto + past simple · It's time we made a decision.", highlights: ["made"] },
      { key: "Afirmativa (Preferencia sobre otros)", value: "Sujeto + would rather + sujeto + past simple · She'd rather he didn't attend.", highlights: ["didn't attend"] },
    ],
    contextExamples: [
      { key: "Análisis de decisiones pasadas", value: "If only we had conducted market validation before launching." },
      { key: "Exigencia de cambio", value: "It's high time the executive board addressed the workplace culture issues." },
      { key: "Preferencia interorganizacional", value: "We'd rather our partners refrained from issuing public statements." },
      { key: "Frustración presente", value: "I wish the supply chain team would communicate delays more transparently." },
    ],
    contrastColumns: [
      {
        label: "Wish + Past Simple",
        rule: "Expresa el deseo de que una situación presente fuera diferente",
        examples: ["I wish we had more resources for this research."],
      },
      {
        label: "Wish + Past Perfect",
        rule: "Expresa lamento o arrepentimiento sobre una acción u omisión en el pasado",
        examples: ["I wish we had hired that specialist last year."],
      },
    ],
    quickReferenceRows: [
      { key: "1. 'It's time' requiere pasado", value: "A pesar de referirse al presente/futuro inmediato, usa Past Simple ('It's time we left')." },
      { key: "2. 'Would rather' con sujeto", value: "Si hay sujeto tras 'would rather', usa Past Simple ('I'd rather you came tomorrow')." },
      { key: "3. 'If only' enfatiza emoción", value: "Funciona igual que 'wish', pero transmite una carga dramática o de lamento superior." },
      { key: "4. 'Wish + would' para conducta", value: "Úsalo para quejarte de acciones de otros que deseas que cambien." },
    ],
    mistake: { bad: "It's high time we start the meeting.", good: "It's high time we started the meeting.", note: "Tras 'It's (high) time + sujeto', la gramática exige el verbo en Past Simple ('started')." },
    quiz: [
      { q: "If only we ___ more attention to the auditor's early warnings last quarter.", options: ["had paid", "have paid", "would pay", "pay"], answer: 0, explain: "El arrepentimiento sobre el pasado requiere Past Perfect ('had paid')." },
      { q: "I'd rather you ___ the client until we have the final contract ready.", options: ["didn't contact", "don't contact", "not contact", "won't contact"], answer: 0, explain: "Cuando 'would rather' lleva un sujeto distinto ('you'), el verbo va en Past Simple negativo ('didn't contact')." },
      { q: "¿Cuál de las siguientes frases expresa una urgencia de actuar en el presente?", options: ["It is high time we updated our security protocols.", "It is high time we update our security protocols.", "It is high time we have updated our security protocols.", "It is high time for updating our security protocols."], answer: 0, explain: "'It's high time + sujeto + Past Simple' es la estructura correcta para urgencia." },
    ],
  },
  {
    slug: "c2-elipsis-sustitucion-avanzada",
    eyebrow: "C2 · Cohesión",
    title: "Elipsis y sustitución",
    emphasis: "avanzadas",
    goal: "Comprime textos densos omitiendo elementos redundantes (elipsis) o reemplazando cláusulas enteras con 'do so', 'so/not' y 'one/ones'.",
    conceptRows: [
      { key: "Sustitución verbal (do so)", value: "The board pledged to reduce carbon emissions and has already done so.", highlights: ["done so"] },
      { key: "Sustitución de cláusula (so/not)", value: "Will market conditions improve? Analysts hope so, but fear not.", highlights: ["hope so", "fear not"] },
      { key: "Elipsis verbal acumulativa", value: "Some experts predicted immediate growth; others, prolonged stagnation.", highlights: ["others, prolonged"] },
      { key: "Sustitución nominal (one/ones)", value: "The old regulations were restrictive, but the new ones are flexible.", highlights: ["new ones"] },
    ],
    structureRows: [
      { key: "Afirmativa (do so)", value: "Sujeto + aux + do so (en el tiempo verbal correspondiente) · She was asked to speak and did so.", highlights: ["did so"] },
      { key: "Negativa (not por cláusula)", value: "Is there any risk of insolvency? I believe not.", highlights: ["believe not"] },
      { key: "Elipsis de infinitivo (to)", value: "You don't have to complete the survey unless you want to.", highlights: ["want to"] },
    ],
    contextExamples: [
      { key: "Análisis corporativo", value: "Companies that fail to digitize will struggle; those that do so will thrive." },
      { key: "Pronósticos de mercado", value: "Will inflation stabilize by Q3? Senior economists certainly hope so." },
      { key: "Debates de política", value: "Primary sources provide raw data; secondary ones, interpretation." },
      { key: "Comunicación concisa", value: "You may decline the offer if you wish to." },
    ],
    contrastColumns: [
      {
        label: "Do so vs. Do it",
        rule: "'Do so' reemplaza acciones delimitadas en registro formal; 'Do it' es más concreto e informal",
        examples: ["Employees are required to register and must do so online."],
      },
      {
        label: "Elipsis vs. Repetición",
        rule: "La elipsis elimina palabras innecesarias sin perder claridad ni significado",
        examples: ["She can manage the team better than he can [manage the team]."],
      },
    ],
    quickReferenceRows: [
      { key: "1. 'Do so' mantiene concordancia", value: "Ajusta la forma de 'do' según el tiempo gramatical ('did so', 'has done so', 'doing so')." },
      { key: "2. 'Hope not' vs 'Don't hope so'", value: "Di 'I hope not' / 'I suspect not' en lugar de 'I don't hope so'." },
      { key: "3. Coma elíptica", value: "En textos formales, la coma reemplaza a un verbo omitido ('John studied law; Mary, medicine')." },
      { key: "4. Infinitivos elípticos", value: "Puedes terminar la frase en la partícula 'to' si el verbo es evidente." },
    ],
    mistake: { bad: "Will the stock rise? I hope no.", good: "Will the stock rise? I hope not.", note: "'Not' sustituye a toda la cláusula subordinada negativa que sigue a verbos de opinión/deseo." },
    quiz: [
      { q: "The company intended to expand into Asia, but lacked the resources to ___.", options: ["do so", "do it so", "make so", "doing so"], answer: 0, explain: "'Do so' sustituye formalmente a la acción 'expand into Asia'." },
      { q: "Are there any hidden fees associated with this account? — I trust ___.", options: ["not", "no", "don't", "none"], answer: 0, explain: "'I trust not' sustituye a la cláusula negativa 'that there are no hidden fees'." },
      { q: "¿Qué opción demuestra una elipsis verbal elegante?", options: ["The director advocated expansion; the CFO, cost retention.", "The director advocated expansion; the CFO advocated cost retention.", "The director advocated expansion; the CFO did so cost retention.", "The director advocated expansion; the CFO advocated it."], answer: 0, explain: "La coma sustituye la repetición del verbo 'advocated'." },
    ],
  },
  {
    slug: "c2-sintagmas-nominales",
    eyebrow: "C2 · Sintaxis",
    title: "Sintagmas",
    emphasis: "nominales complejos",
    goal: "Construye sintagmas nominales densos agrupando premodificadores (adjetivos, sustantivos) y posmodificadores (participios, preposiciones).",
    conceptRows: [
      { key: "Premodificación sustantiva", value: "groundbreaking cross-border supply chain management systems", highlights: ["supply chain management systems"] },
      { key: "Posmodificación participial", value: "the proposals submitted by the foreign delegation", highlights: ["submitted by"] },
      { key: "Posmodificación preposicional", value: "the underlying causes of structural market volatility", highlights: ["causes of structural market volatility"] },
      { key: "Núcleo denso empaquetado", value: "a highly controversial government-backed infrastructure initiative", highlights: ["infrastructure initiative"] },
    ],
    structureRows: [
      { key: "Estructura completa", value: "Determinado + Adverbio/Adj + Sustantivo modificador + NÚCLEO + Posmodificador · A very costly software security flaw reported yesterday.", highlights: ["security flaw"] },
      { key: "Afirmativa", value: "The newly adopted environmental protection laws will impact heavy industry.", highlights: ["environmental protection laws"] },
      { key: "Negativa", value: "No poorly constructed risk assessment models should be approved.", highlights: ["risk assessment models"] },
    ],
    contextExamples: [
      { key: "Redacción académica", value: "Recent peer-reviewed academic studies on climate resilience indicate rapid changes." },
      { key: "Informes financieros", value: "The surprisingly high third-quarter revenue growth surprised institutional investors." },
      { key: "Documentos legales", value: "Any unauthorized disclosure of proprietary trade secrets constitutes a breach." },
      { key: "Estrategia empresarial", value: "Our customer relationship management software upgrade is complete." },
    ],
    contrastColumns: [
      {
        label: "Sintagma nominal denso (C2)",
        rule: "Condensa múltiples conceptos en una sola frase nominal sin recurrir a cláusulas complejas",
        examples: ["The unexpected mid-year budgetary constraints forced project cancellation."],
      },
      {
        label: "Oración desplegada (B2)",
        rule: "Utiliza cláusulas de relativo y conectores para distribuir la información",
        examples: ["The constraints on the budget, which were unexpected and happened mid-year, forced us to cancel."],
      },
    ],
    quickReferenceRows: [
      { key: "1. Identifica el núcleo", value: "En inglés, el sustantivo principal (head noun) se ubica al final de la premodificación." },
      { key: "2. Sustantivos como adjetivos", value: "Los sustantivos que modifican al núcleo van en singular ('risk assessment', NO 'risks assessment')." },
      { key: "3. Uso de guiones", value: "Enlaza adjetivos compuestos antes del sustantivo ('state-of-the-art facility')." },
      { key: "4. Posmodificación concisa", value: "Prefiere cláusulas de participio ('data collected') frente a relativas enteras ('data which was collected')." },
    ],
    mistake: { bad: "The high risk management decisions were questioned.", good: "The high-risk management decisions were questioned.", note: "Usa guion en 'high-risk' para evitar ambigüedad en el sintagma nominal." },
    quiz: [
      { q: "Identify the head noun in: 'the rapidly expanding international digital asset market'.", options: ["market", "asset", "digital", "expanding"], answer: 0, explain: "'Market' es el sustantivo núcleo (head noun) al que modifican todos los términos anteriores." },
      { q: "Which compound modifier is written correctly before a noun?", options: ["well-established protocol", "well established protocol", "well establishing protocol", "protocol well-established"], answer: 0, explain: "Los modificadores compuestos antes del sustantivo llevan guion ('well-established')." },
      { q: "¿Qué opción demuestra la construcción de un sintagma nominal denso y natural?", options: ["The company's long-term strategic growth plan", "The plan of growth strategic long-term of the company", "The company plan of strategic long-term growth", "The long-term plan growth strategic of the company"], answer: 0, explain: "Sigue el orden natural de premodificación en inglés: poseedor + adjetivos compuestos + sustantivo núcleo." },
    ],
  },
  {
    slug: "c2-concesion-avanzada",
    eyebrow: "C2 · Concesión",
    title: "Concesión",
    emphasis: "avanzada",
    goal: "Expresa concesión y contraste sofisticado con 'much as', 'whatever', 'however + adj/adv' y 'adj + as/though + sujeto + verbo'.",
    conceptRows: [
      { key: "Much as (A pesar de cuánto)", value: "Much as I respect his dedication, I cannot support his proposal.", highlights: ["Much as"] },
      { key: "However + Adjetivo", value: "However compelling the evidence may be, doubts persist.", highlights: ["However compelling"] },
      { key: "Adjetivo + as/though", value: "Difficult though the negotiation was, an agreement was reached.", highlights: ["Difficult though"] },
      { key: "Whatever / Whoever", value: "Whatever the outcome, we remain committed to transparency.", highlights: ["Whatever the outcome"] },
    ],
    structureRows: [
      { key: "Afirmativa (Much as)", value: "Much as + sujeto + verbo de sentimiento/opinión, cláusula principal.", highlights: ["Much as"] },
      { key: "Afirmativa (However + Adj)", value: "However + adjetivo/adverbio + sujeto + may/can be, cláusula principal.", highlights: ["However compelling"] },
      { key: "Afirmativa (Adj + as/though)", value: "Adjetivo + as/though + sujeto + verbo, cláusula principal · Qualified as she is, she lacked experience.", highlights: ["Qualified as she is"] },
    ],
    contextExamples: [
      { key: "Debates ejecutivos", value: "Much as we would like to expand immediately, capital constraints prevent it." },
      { key: "Análisis de riesgos", value: "However meticulous our planning might be, unforeseen market shocks occur." },
      { key: "Evaluación de talento", value: "Capable though he is, he struggles under tight deadlines." },
      { key: "Postura institucional", value: "Whatever political pressure we face, our audit will remain independent." },
    ],
    contrastColumns: [
      {
        label: "However + Adjetivo",
        rule: "Funciona como subordinador de concesión al unirse inmediatamente a un adjetivo/adverbio",
        examples: ["However hard we tried, we couldn't meet the deadline."],
      },
      {
        label: "However (Conector independiente)",
        rule: "Conecta dos oraciones independientes mediante una pausa (coma tras 'However')",
        examples: ["We tried hard. However, we couldn't meet the deadline."],
      },
    ],
    quickReferenceRows: [
      { key: "1. 'Much as' con verbo mental", value: "Combínalo con verbos como 'admire', 'respect', 'enjoy', 'like', 'dislike'." },
      { key: "2. Adjetivo antepuesto con 'as'", value: "'Exhausted as they were, they pushed on' equivale a 'Although they were exhausted'." },
      { key: "3. Sin 'but' tras concesión", value: "Al usar 'Much as' o 'However adj', NUNCA agregues 'but' en la segunda cláusula." },
      { key: "4. 'Whatever' con sustantivo", value: "Acepta sustantivos directos ('Whatever the difficulties,...')." },
    ],
    mistake: { bad: "Much as I admire her work, but I disagree with her conclusion.", good: "Much as I admire her work, I disagree with her conclusion.", note: "No incluyas la conjunción 'but' cuando la oración inicia con 'Much as'." },
    quiz: [
      { q: "___ I appreciate your perspective, we must adhere to regulatory guidelines.", options: ["Much as", "Even as", "As much", "In spite"], answer: 0, explain: "'Much as' introduce una cláusula concesiva formal seguida de un verbo de apreciación/sentimiento." },
      { q: "___ the challenge may seem, our research team is prepared to address it.", options: ["Daunting as", "As daunting", "Though daunting", "How daunting"], answer: 0, explain: "La estructura 'Adjetivo + as + sujeto + verbo' ('Daunting as the challenge may seem') expresa concesión." },
      { q: "¿Cuál de las siguientes oraciones utiliza 'however' de manera concesiva avanzada?", options: ["However complex the system is, we can optimize it.", "However, the system is complex and hard to optimize.", "The system is complex, however we can optimize it.", "However the system complex is, we can optimize it."], answer: 0, explain: "'However + adjetivo + sujeto + verbo' es la subordinación concesiva correcta." },
    ],
  },
  {
    slug: "c2-condicionales-idiomaticas",
    eyebrow: "C2 · Condicionales",
    title: "Condicionales",
    emphasis: "idiomáticas",
    goal: "Expresa hipótesis complejas mediante condicionales omitidas e invertidas ('Had I known', 'Were it not for', 'If need be', 'If so/not').",
    conceptRows: [
      { key: "Inversión de 3er condicional", value: "Had we anticipated the demand, we would have doubled production.", highlights: ["Had we anticipated"] },
      { key: "Inversión de 2do condicional", value: "Were the manager to resign, the department would collapse.", highlights: ["Were the manager to resign"] },
      { key: "Condicional de exclusión", value: "Were it not for / But for your intervention, we would have failed.", highlights: ["Were it not for", "But for"] },
      { key: "Fórmulas elípticas", value: "We can deploy additional servers if need be.", highlights: ["if need be"] },
    ],
    structureRows: [
      { key: "Afirmativa (Inversión Had)", value: "Had + sujeto + participio pasado, sujeto + would have + participio · Had I known, I would have acted.", highlights: ["Had I known"] },
      { key: "Afirmativa (Inversión Were)", value: "Were + sujeto + to + verbo base, sujeto + would + verbo base · Were you to ask, I would assist.", highlights: ["Were you to ask"] },
      { key: "Afirmativa (Elíptica)", value: "Are there any updates? If so, notify the team immediately.", highlights: ["If so"] },
    ],
    contextExamples: [
      { key: "Revisión de crisis pasadas", value: "Had the warning systems functioned properly, the disaster would have been averted." },
      { key: "Planificación de contingencias", value: "Were competitors to lower their prices, we would respond with value-added services." },
      { key: "Agradecimiento profesional", value: "But for the legal team's quick response, the firm would have faced heavy fines." },
      { key: "Instrucciones operativas", value: "Check whether the system is responsive. If not, initiate a manual reboot." },
    ],
    contrastColumns: [
      {
        label: "Inversión condicional (C2)",
        rule: "Elimina la conjunción 'if' invirtiendo el auxiliar 'Had' o 'Were' al inicio de la cláusula",
        examples: ["Had I received the report, I would have reviewed it."],
      },
      {
        label: "Condicional estándar con If (B2)",
        rule: "Mantiene la conjunción 'if' y el orden estándar de sujeto + verbo",
        examples: ["If I had received the report, I would have reviewed it."],
      },
    ],
    quickReferenceRows: [
      { key: "1. Sin 'if' en inversión", value: "NUNCA uses 'if' junto a la inversión (ej. 'If had I known' es incorrecto)." },
      { key: "2. 'Were it not for' = sin tu ayuda", value: "Expresa que una circunstancia presente es el único obstáculo o razón." },
      { key: "3. 'Had it not been for'", value: "Es la versión pasada de la exclusión ('Had it not been for your help...')." },
      { key: "4. Fórmulas fijas elípticas", value: "Usa 'if need be' (si es necesario), 'if any' (si los hay), 'if so' (si es así)." },
    ],
    mistake: { bad: "If had I known about the defect, I wouldn't have approved it.", good: "Had I known about the defect, I wouldn't have approved it.", note: "Al invertir el verbo ('Had I known'), la conjunción 'if' debe eliminarse completamente." },
    quiz: [
      { q: "___ it not for your strategic guidance, the project would have run out of funds.", options: ["Were", "Had been", "Had", "Would be"], answer: 0, explain: "'Were it not for' equivale a 'si no fuera por tu orientación estratégica'." },
      { q: "___ we to encounter technical difficulties, our support desk will assist you.", options: ["Were", "Had", "Should", "If"], answer: 0, explain: "'Were + sujeto + to + infinitivo' es la forma invertida del segundo condicional." },
      { q: "Please verify if the documents require notarization. ___, send them to legal.", options: ["If so", "If such", "If yes", "If true"], answer: 0, explain: "'If so' reemplaza elípticamente a la afirmación 'if they require notarization'." },
    ],
  },
  {
    slug: "c2-inversion-literaria",
    eyebrow: "C2 · Inversión",
    title: "Inversión",
    emphasis: "literaria",
    goal: "Crea dramatismo, intensidad y estilo retórico mediante estructuras invertidas con 'So + adjetivo', 'Such + be' y locaciones.",
    conceptRows: [
      { key: "So + Adjetivo + be", value: "So great was the interest that servers crashed within minutes.", highlights: ["So great was"] },
      { key: "Such + be + Sustantivo", value: "Such was the severity of the storm that flights were grounded.", highlights: ["Such was"] },
      { key: "Inversión de lugar / dirección", value: "On the top of the mountain stood an ancient fortress.", highlights: ["stood an ancient fortress"] },
      { key: "Inversión con participio", value: "Enclosed in this envelope is the signed agreement.", highlights: ["Enclosed in this envelope is"] },
    ],
    structureRows: [
      { key: "Afirmativa (So + Adj)", value: "So + adjetivo + verbo be/auxiliar + sujeto + that... · So intense was the competition that prices dropped.", highlights: ["So intense was"] },
      { key: "Afirmativa (Such + be)", value: "Such + be + sujeto/sustantivo + that... · Such was his determination that he succeeded.", highlights: ["Such was"] },
      { key: "Afirmativa (Ubicación)", value: "Preposición de lugar + verbo de posición + sujeto · Next to the station stands the headquarters.", highlights: ["stands the headquarters"] },
    ],
    contextExamples: [
      { key: "Discursos de alto impacto", value: "So profound was his influence that an entire generation adopted his philosophy." },
      { key: "Narrativa histórica", value: "Such was the devastation caused by the fire that rebuilding took decades." },
      { key: "Correspondencia ejecutiva", value: "Attached to this communication are the revised financial forecasts." },
      { key: "Descripciones periodísticas", value: "High above the skyline rose the new architectural landmark." },
    ],
    contrastColumns: [
      {
        label: "Inversión retórica (C2)",
        rule: "Coloca 'So + adjetivo' o 'Such' al inicio invirtiendo el verbo principal para máxima intensidad",
        examples: ["So fierce was the opposition that the law was repealed."],
      },
      {
        label: "Estructura directa (B2)",
        rule: "Mantiene el orden tradicional sujeto + verbo + so/such",
        examples: ["The opposition was so fierce that the law was repealed."],
      },
    ],
    quickReferenceRows: [
      { key: "1. 'So' requiere adjetivo", value: "Usa 'So + adjetivo + be + sujeto' ('So impressive was the demo')." },
      { key: "2. 'Such' requiere sustantivo", value: "Usa 'Such + be + sustantivo' ('Such was the noise that...')." },
      { key: "3. Inversión con verbos de movimiento", value: "Tras adverbios de lugar ('Down came the rain'), el verbo principal antecede al sujeto si es un sustantivo." },
      { key: "4. No invertimos con pronombres", value: "Si el sujeto es un pronombre, no se invierte ('Away he ran', NO 'Away ran he')." },
    ],
    mistake: { bad: "So great the shock was that nobody spoke.", good: "So great was the shock that nobody spoke.", note: "En la inversión con 'So + adjetivo', el verbo 'was' debe preceder al sujeto 'the shock'." },
    quiz: [
      { q: "___ was the urgency of the situation that an emergency meeting was called.", options: ["Such", "So", "Thus", "How"], answer: 0, explain: "'Such + was + sustantivo (the urgency)' expresa la intensidad del sustantivo." },
      { q: "So complex ___ the technical challenges that the project took three years.", options: ["were", "did", "was it", "they were"], answer: 0, explain: "'So + adjetivo (complex)' requiere el verbo de estado en plural 'were' para concordar con 'challenges'." },
      { q: "¿Cuál de las siguientes oraciones presenta la inversión de lugar correcta?", options: ["At the center of the debate lies the question of ethics.", "At the center of the debate the question of ethics lies.", "At the center of the debate does lie the question of ethics.", "At the center of the debate lie it the question of ethics."], answer: 0, explain: "Tras la locación inicial, el verbo de posición ('lies') antecede al sujeto ('the question of ethics')." },
    ],
  },
  {
    slug: "c2-topicalizacion",
    eyebrow: "C2 · Topicalización",
    title: "Orden de palabras",
    emphasis: "marcado",
    goal: "Establece el tema del discurso (topicalización) moviendo elementos informativos clave al inicio de la oración para coordinar el foco temático.",
    conceptRows: [
      { key: "Topicalización de objeto directo", value: "The primary objectives, we have already fulfilled.", highlights: ["The primary objectives"] },
      { key: "Topicalización de complemento", value: "Unreasonable, I would not call their demands.", highlights: ["Unreasonable"] },
      { key: "Contraste de dos temas", value: "The financial aspects we can handle; the ethical concerns remain unresolved.", highlights: ["The financial aspects"] },
      { key: "Cohesión temática de texto", value: "That argument, the court rejected out of hand.", highlights: ["That argument"] },
    ],
    structureRows: [
      { key: "Afirmativa", value: "Elemento topicalizado (Objeto/Adj) + Sujeto + Verbo principal · Most of these problems we solved.", highlights: ["Most of these problems", "we solved"] },
      { key: "Afirmativa (Contraste)", value: "Tema A + sujeto + verbo; Tema B + sujeto + verbo · Cash flow we have; profit we lack.", highlights: ["Cash flow", "profit"] },
      { key: "Negativa", value: "Such inappropriate behavior we will not tolerate in our organization.", highlights: ["Such inappropriate behavior"] },
    ],
    contextExamples: [
      { key: "Debates parlamentarios", value: "That specific amendment, the coalition cannot support." },
      { key: "Análisis de negocios", value: "Market leadership we achieved years ago; sustainable profitability is our new goal." },
      { key: "Discursos persuasivos", value: "His integrity no one can question, but his methodology is flawed." },
      { key: "Escritura de opinión", value: "These long-term risks, the board chose to ignore." },
    ],
    contrastColumns: [
      {
        label: "Topicalización (C2)",
        rule: "Antepone el elemento sin añadir pronombre ni alterar el orden estándar de Sujeto + Verbo",
        examples: ["This milestone we achieved through sheer persistence."],
      },
      {
        label: "Dislocación a la izquierda (Informal)",
        rule: "Antepone el tema pero incluye un pronombre redundante en la posición original",
        examples: ["This milestone, we achieved it through sheer persistence."],
      },
    ],
    quickReferenceRows: [
      { key: "1. Sin cambio de auxiliar", value: "A diferencia de la inversión negativa, la topicalización simple conserva el orden Sujeto + Verbo." },
      { key: "2. Cero pronombres resuntivos", value: "No agregues pronombres como 'it' o 'them' para referirte al tema antepuesto." },
      { key: "3. Uso para contrastes", value: "Es excelente para oponer dos elementos en dos cláusulas consecutivas." },
      { key: "4. Claridad contextual", value: "El elemento topicalizado debe ser información conocida o relevante en el contexto previo." },
    ],
    mistake: { bad: "This software, we have tested it extensively.", good: "This software we have tested extensively.", note: "En la topicalización formal se omite el pronombre redundante ('it')." },
    quiz: [
      { q: "The technical documentation we have thoroughly reviewed; the financial projections ___.", options: ["we have yet to examine", "have we yet to examine", "we have yet to examine them", "did we examine yet"], answer: 0, explain: "Mantiene la estructura de topicalización paralela (Tema + Sujeto + Verbo) sin pronombres extra." },
      { q: "___ no auditor could possibly dispute.", options: ["These figures", "These figures that", "That these figures", "Because these figures"], answer: 0, explain: "'These figures' funciona como el objeto topicalizado directo de 'could dispute'." },
      { q: "¿Cuál es la diferencia principal entre la topicalización y la inversión negativa?", options: ["La topicalización mantiene el orden Sujeto + Verbo; la inversión altera el orden a Auxiliar + Sujeto", "La topicalización requiere siempre el pronombre 'it'", "La inversión no permite el uso de adjetivos", "La topicalización solo se utiliza en preguntas"], answer: 0, explain: "La topicalización solo mueve el elemento al inicio sin invertir el auxiliar con el sujeto." },
    ],
  },
  {
    slug: "c2-modalidad-matizada",
    eyebrow: "C2 · Modalidad",
    title: "Modalidad",
    emphasis: "matizada",
    goal: "Calibra grados extremos de certeza, suposición o inferencia lógica usando 'may well', 'must have', 'can't have' y 'would have to be'.",
    conceptRows: [
      { key: "Probabilidad muy alta (may well)", value: "The central bank may well raise interest rates next quarter.", highlights: ["may well raise"] },
      { key: "Deducción lógica pasada (+)", value: "The auditors must have overlooked the secondary ledger.", highlights: ["must have overlooked"] },
      { key: "Deducción lógica pasada (-)", value: "They can't have finalized the contract without legal approval.", highlights: ["can't have finalized"] },
      { key: "Inferencia forzada presente", value: "For costs to double, there would have to be systemic inefficiency.", highlights: ["would have to be"] },
    ],
    structureRows: [
      { key: "Afirmativa (Inferencia pasada)", value: "Sujeto + must have + participio pasado · She must have left early.", highlights: ["must have left"] },
      { key: "Negativa (Imposibilidad pasada)", value: "Sujeto + cannot/can't have + participio pasado · He can't have known.", highlights: ["can't have known"] },
      { key: "Afirmativa (Probabilidad fortalecida)", value: "Sujeto + may/might well + verbo base · Prices may well surge soon.", highlights: ["may well surge"] },
    ],
    contextExamples: [
      { key: "Investigación forense", value: "The security breach must have occurred during the system maintenance window." },
      { key: "Proyecciones económicas", value: "Given current trends, the market may well experience a correction." },
      { key: "Análisis de credibilidad", value: "The defendant can't have been at the scene; witnesses place him elsewhere." },
      { key: "Evaluación de hipótesis", value: "To explain such anomalous data, there would have to be an unrecorded variable." },
    ],
    contrastColumns: [
      {
        label: "Must have + Participio",
        rule: "Indica certeza lógica absoluta sobre un evento del pasado basada en evidencia",
        examples: ["The streets are wet; it must have rained last night."],
      },
      {
        label: "May/Might have + Participio",
        rule: "Indica una posibilidad pasada incierta u opcional",
        examples: ["He hasn't arrived; he might have missed his train."],
      },
    ],
    quickReferenceRows: [
      { key: "1. 'May well' refuerza la probabilidad", value: "Significa 'es highly probable que' (más fuerte que 'may' a secas)." },
      { key: "2. 'Can't have' para imposibilidad", value: "NUNCA uses 'mustn't have' para deducción negativa pasada; usa 'can't have'." },
      { key: "3. 'Would have to be'", value: "Se utiliza para expresar la condición o conclusión inevitable de una situación." },
      { key: "4. Participio pasado indispensable", value: "Todas las inferencias sobre el pasado requieren la estructura modal + have + participio." },
    ],
    mistake: { bad: "They mustn't have received the payment because the system shows zero balance.", good: "They can't have received the payment because the system shows zero balance.", note: "La imposibilidad deductiva pasada se expresa con 'can't have', no con 'mustn't have'." },
    quiz: [
      { q: "The management team ___ known about the flaw; otherwise, they would have halted distribution.", options: ["can't have", "mustn't have", "shouldn't have", "won't have"], answer: 0, explain: "'Can't have + participio' expresa la imposibilidad lógica de un evento pasado." },
      { q: "Considering our rapid growth, we ___ need to recruit additional engineers soon.", options: ["may well", "must to", "can well", "would to"], answer: 0, explain: "'May well' indica una alta probabilidad en el presente/futuro." },
      { q: "¿Qué opción expresa una inferencia lógica afirmativa fundamentada en evidencia pasada?", options: ["The server logs show thousands of requests; we must have suffered a DDoS attack.", "The server logs show thousands of requests; we can have suffered a DDoS attack.", "The server logs show thousands of requests; we would suffer a DDoS attack.", "The server logs show thousands of requests; we may to suffer a DDoS attack."], answer: 0, explain: "'Must have + participio' es la forma para conclusiones afirmativas de alta certeza sobre el pasado." },
    ],
  },
  {
    slug: "c2-marcadores-pragmaticos",
    eyebrow: "C2 · Pragmática",
    title: "Marcadores",
    emphasis: "pragmáticos",
    goal: "Modula la postura, actitud y distancia comunicativa del hablante mediante marcadores pragmáticos ('frankly', 'presumably', 'as it were').",
    conceptRows: [
      { key: "Franqueza directa", value: "Frankly / To be frank, the current strategy is unsustainable.", highlights: ["Frankly"] },
      { key: "Deducción hipotética", value: "Presumably, the legal department has already reviewed these clauses.", highlights: ["Presumably"] },
      { key: "Atenuación metafórica", value: "He has become the undisputed architect of the project, as it were.", highlights: ["as it were"] },
      { key: "Perspectiva personal", value: "If you ask me, the market is overestimating their growth potential.", highlights: ["If you ask me"] },
    ],
    structureRows: [
      { key: "Afirmativa (Postura oracional)", value: "Marcador pragmático + coma + oración principal · Frankly, we cannot afford more delays.", highlights: ["Frankly"] },
      { key: "Afirmativa (Marcador incrustado)", value: "The plan is, presumably, going to be approved by the board.", highlights: ["presumably"] },
      { key: "Afirmativa (Marcador final)", value: "They have established a monopoly, as it were.", highlights: ["as it were"] },
    ],
    contextExamples: [
      { key: "Evaluaciones críticas", value: "Frankly, the performance figures presented today are unsatisfactory." },
      { key: "Suposiciones gerenciales", value: "Presumably, the team will complete testing prior to the public release." },
      { key: "Explicaciones conceptuales", value: "The new division will act as an incubator, as it were, for fresh talent." },
      { key: "Comentarios de pasillo / Reuniones", value: "If you ask me, we should have negotiated harder on pricing." },
    ],
    contrastColumns: [
      {
        label: "Frankly / To be frank",
        rule: "Introduce una opinión honesta y directa que puede ser incómoda o confrontativa",
        examples: ["Frankly, we don't have the expertise to execute this in-house."],
      },
      {
        label: "Presumably",
        rule: "Indica una suposición razonable basada en la lógica o rutina, sin confirmación absoluta",
        examples: ["Presumably, they will notify us when the audit is complete."],
      },
    ],
    quickReferenceRows: [
      { key: "1. Moduladores de actitud", value: "Los marcadores pragmáticos no cambian la gramática de la frase, sino cómo debe ser interpretada." },
      { key: "2. 'As it were' atenúa metáforas", value: "Úsalo para señalar que una expresión no debe tomarse de forma strictly literal." },
      { key: "3. 'Presumably' presupone lógica", value: "Equivale a 'I assume that', aportando distancia profesional." },
      { key: "4. Puntuación", value: "Separa los marcadores pragmáticos con comas al inicio, centro o final de la oración." },
    ],
    mistake: { bad: "Frankly to say, the project is a failure.", good: "Frankly, the project is a failure. / To be frank, the project is a failure.", note: "No mezcles 'frankly' con 'to say'; usa 'Frankly,' o 'To be frank,'." },
    quiz: [
      { q: "___, the board has already agreed on the successor, though no official announcement was made.", options: ["Presumably", "As it were", "Frankly to say", "To be frankly"], answer: 0, explain: "'Presumably' refleja una deducción lógica basada en las circunstancias." },
      { q: "The startup is living on borrowed time, ___.", options: ["as it were", "presumably that", "if asking me", "frankly to say"], answer: 0, explain: "'As it were' atenúa la metáfora 'living on borrowed time'." },
      { q: "¿Qué marcador pragmático introduce una opinión directa y honesta sin rodeos?", options: ["Frankly", "As it were", "Notwithstanding", "In so far as"], answer: 0, explain: "'Frankly' indica franqueza directa en la exposición de una postura." },
    ],
  },
  {
    slug: "c2-cambio-registro",
    eyebrow: "C2 · Registro",
    title: "Cambio de",
    emphasis: "registro",
    goal: "Alterna con fluidez entre registros formales (densidad nominal, pasivas) e informales (phrasal verbs, voz activa, elipsis).",
    conceptRows: [
      { key: "Registro Formal (Académico/Legal)", value: "The unexpected termination of the contract resulted in financial litigation.", highlights: ["termination", "resulted in litigation"] },
      { key: "Registro Informal (Conversacional)", value: "They suddenly canceled the contract, so we had to sue them.", highlights: ["canceled", "sue them"] },
      { key: "Formal: Pasiva Impersonal", value: "It is recommended that procedures be adhered to rigorously.", highlights: ["It is recommended"] },
      { key: "Informal: Activa Directa", value: "Make sure you stick to the rules.", highlights: ["stick to"] },
    ],
    structureRows: [
      { key: "Formal (Alta densidad nominal)", value: "Sustantivos complejos + verbos de origen latino · The implementation of reforms is vital.", highlights: ["implementation of reforms"] },
      { key: "Informal (Basado en verbos)", value: "Verbos dinámicos + Phrasal verbs · Carrying out reforms is key.", highlights: ["Carrying out"] },
      { key: "Ajuste de conectores", value: "Formal: 'Furthermore' / Informal: 'Plus' · Formal: 'Consequently' / Informal: 'So'.", highlights: ["Furthermore", "Consequently"] },
    ],
    contextExamples: [
      { key: "Email ejecutivo (Formal)", value: "Should you require further clarification, please do not hesitate to contact me." },
      { key: "Chat de trabajo (Informal)", value: "Let me know if you need anything else!" },
      { key: "Informe oficial (Formal)", value: "Subsequent to the investigation, corrective measures were introduced." },
      { key: "Reunión de equipo (Informal)", value: "After looking into it, we fixed the problems." },
    ],
    contrastColumns: [
      {
        label: "Registro Formal (Escrito / Corporativo)",
        rule: "Prioriza nominalizaciones, voz pasiva, conectores latinos y ausencia de contracciones",
        examples: ["Prior to departure, verification must be conducted."],
      },
      {
        label: "Registro Informal (Hablado / Coloquial)",
        rule: "Prioriza verbos simples, phrasals, contracciones, voz activa y conectores cortos",
        examples: ["Before you leave, check everything."],
      },
    ],
    quickReferenceRows: [
      { key: "1. Nominalización vs. Verbo", value: "El registro formal convierte verbos en sustantivos ('decide' → 'make a decision')." },
      { key: "2. Vocabulario germánico vs. latino", value: "Usa raíces latinas en formal ('investigate') y phrasals en informal ('look into')." },
      { key: "3. Uso de contracciones", value: "Evita contracciones en correos y documentos oficiales ('cannot', 'do not')." },
      { key: "4. Estructuras impersonales", value: "Sustituye 'you' o 'we' por estructuras pasivas o impersonales en textos formales." },
    ],
    mistake: { bad: "Hey Mr. Davis, pursuant to your email, we gonna check the numbers.", good: "Dear Mr. Davis, with reference to your email, we will verify the figures.", note: "Evita mezclar conectores ultra formales ('pursuant to') con jerga informal ('gonna')." },
    quiz: [
      { q: "Which version is most appropriate for a formal legal notice?", options: ["Failure to comply with these terms will result in contract termination.", "If you don't stick to these rules, we will break the contract.", "If you fail these terms, we are gonna cancel the deal.", "Not complying these terms makes the contract end."], answer: 0, explain: "La nominalización ('Failure to comply', 'contract termination') marca el registro formal correcto." },
      { q: "Select the informal equivalent of: 'The investigation was postponed due to inclement weather.'", options: ["They put off the investigation because of the bad weather.", "The inquiry was delayed on account of severe weather.", "Owing to rain, the investigation was deferred.", "The team postponed investigating due to weather conditions."], answer: 0, explain: "'Put off' y 'bad weather' reemplazan a 'postponed' e 'inclement weather' en registro informal." },
      { q: "¿Qué elemento es característico del registro formal en inglés?", options: ["Uso de nominalizaciones y pasivas impersonales", "Abundancia de phrasal verbs e interjecciones", "Uso constante de contracciones y elipsis", "Sustitución de sustantivos por pronombres genéricos"], answer: 0, explain: "La nominalización y la voz pasiva elevan la densidad formal del texto." },
    ],
  },
  {
    slug: "c2-pasiva-estilistica",
    eyebrow: "C2 · Pasiva",
    title: "Pasiva",
    emphasis: "estilística",
    goal: "Utiliza pasivas impersonales y de reportaje ('It is believed that', 'He is said to be') para distanciar al autor o comunicar rumores oficiales.",
    conceptRows: [
      { key: "It + Pasiva + Clause", value: "It is widely acknowledged that climate change threatens global security.", highlights: ["It is widely acknowledged"] },
      { key: "Sujeto + Pasiva + Infinitivo", value: "The CEO is reported to be considering a major buyout.", highlights: ["is reported to be considering"] },
      { key: "Infinitivo perfecto pasivo", value: "The suspect is believed to have left the country.", highlights: ["is believed to have left"] },
      { key: "Pasiva continua presente", value: "New policies are currently being drafted by the committee.", highlights: ["are currently being drafted"] },
    ],
    structureRows: [
      { key: "Afirmativa (Impersonal It)", value: "It + is/was + participio de reporte + that + cláusula · It is rumored that they will merge.", highlights: ["It is rumored that"] },
      { key: "Afirmativa (Sujeto personal)", value: "Sujeto + be + participio + to + infinitivo (simple/continuo/perfecto) · She is said to be rich.", highlights: ["is said to be"] },
      { key: "Negativa", value: "The preliminary findings are not expected to be published until next year.", highlights: ["are not expected to be published"] },
    ],
    contextExamples: [
      { key: "Periodismo internacional", value: "It is reported that negotiations have reached a stalemate in Geneva." },
      { key: "Información de mercado", value: "The tech giant is understood to be developing a quantum processor." },
      { key: "Informes policiales/judiciales", value: "The fugitive is thought to have crossed the border under a false identity." },
      { key: "Redacción académica", value: "It has been demonstrated that the compound inhibits viral replication." },
    ],
    contrastColumns: [
      {
        label: "Pasiva impersonal (It is said that)",
        rule: "Introduce una creencia general usando 'It' como sujeto nulo",
        examples: ["It is alleged that the executive committed fraud."],
      },
      {
        label: "Pasiva personal (He is said to)",
        rule: "Hace del sujeto de la noticia el foco de la oración mediante un infinitivo",
        examples: ["The executive is alleged to have committed fraud."],
      },
    ],
    quickReferenceRows: [
      { key: "1. Verbos de reporte comunes", value: "Usa 'allege', 'believe', 'claim', 'consider', 'estimate', 'report', 'say', 'understand'." },
      { key: "2. Infinitivo pasado (to have done)", value: "Usa 'to have + participio' si la acción reportada ocurrió antes que el reporte." },
      { key: "3. Infinitivo continuo (to be doing)", value: "Usa 'to be + -ing' si la acción reportada ocurre de manera simultánea." },
      { key: "4. Distanciamiento profesional", value: "Evita atribuir declaraciones sin verificar usando 'It is claimed that'." },
    ],
    mistake: { bad: "People is said that the company is going bankrupt.", good: "It is said that the company is going bankrupt. / The company is said to be going bankrupt.", note: "No combines 'People' con la estructura pasiva de reporte; usa 'It is said' o el sujeto directo." },
    quiz: [
      { q: "The missing artwork is believed ___ stolen during the early hours of Tuesday.", options: ["to have been", "to be", "that it was", "having been"], answer: 0, explain: "'To have been + participio' expresa una acción pasiva completada en el pasado." },
      { q: "___ that the new tax reform will pass without major amendments.", options: ["It is anticipated", "They are anticipated", "He is anticipated", "Is anticipated"], answer: 0, explain: "La pasiva impersonal requiere el sujeto preparatorio 'It' ('It is anticipated that')." },
      { q: "¿Cuál es la forma correcta de transformar 'People say he works 80 hours a week' a pasiva estilística personal?", options: ["He is said to work 80 hours a week.", "It is said he to work 80 hours a week.", "He says to work 80 hours a week.", "He is saying to work 80 hours a week."], answer: 0, explain: "Sujeto + is said + infinitivo presente ('to work')." },
    ],
  },
  {
    slug: "c2-subjuntivo-formulas",
    eyebrow: "C2 · Subjuntivo",
    title: "Subjuntivo",
    emphasis: "fórmulas fijas",
    goal: "Reconoce y aplica expresiones subjuntivas congeladas y formulaicas ('be that as it may', 'come what may', 'suffice it to say').",
    conceptRows: [
      { key: "Concesión de punto (Sea como fuere)", value: "Be that as it may, we must adhere to our strategic timetable.", highlights: ["Be that as it may"] },
      { key: "Determinación (Pase lo que pase)", value: "Come what may, the organization will support its employees.", highlights: ["Come what may"] },
      { key: "Síntesis (Baste decir que)", value: "Suffice it to say, the project was an overwhelming success.", highlights: ["Suffice it to say"] },
      { key: "Aceptación solemne (Que así sea)", value: "If they refuse our proposal, then so be it.", highlights: ["so be it"] },
    ],
    structureRows: [
      { key: "Afirmativa (Be that as it may)", value: "Be that as it may, + cláusula principal de contraste.", highlights: ["Be that as it may"] },
      { key: "Afirmativa (Suffice it to say)", value: "Suffice it to say (that) + cláusula aclaratoria.", highlights: ["Suffice it to say"] },
      { key: "Afirmativa (God forbid / Far be it from me)", value: "Far be it from me to criticize, but we need better organization.", highlights: ["Far be it from me"] },
    ],
    contextExamples: [
      { key: "Debates de alta dirección", value: "Sales were lower than expected. Be that as it may, our profits remain stable." },
      { key: "Declaraciones institucionales", value: "Come what may, our firm will honor all contractual obligations." },
      { key: "Resúmenes ejecutivos", value: "Suffice it to say, the launch surpassed all performance benchmarks." },
      { key: "Intervenciones diplomáticas", value: "Far be it from me to dictate strategy, but caution is advised." },
    ],
    contrastColumns: [
      {
        label: "Fórmula Subjuntiva Fija (C2)",
        rule: "Son expresiones fosilizadas que mantienen la forma base del verbo en posición inicial o fija",
        examples: ["Suffice it to say that we won."],
      },
      {
        label: "Paráfrasis Estándar (B2)",
        rule: "Utiliza gramática convencional y conectores modernos",
        examples: ["It is enough to say that we won."],
      },
    ],
    quickReferenceRows: [
      { key: "1. Inalterabilidad gramatical", value: "No cambies los tiempos ni pronombres de estas expresiones (ej. 'Be that as it is' es INCORRECTO)." },
      { key: "2. 'Suffice it to say'", value: "Significa 'baste decir'; se usa para resumir una explicación larga." },
      { key: "3. 'Far be it from me'", value: "Se usa antes de dar una opinión o crítica para sonar cortés o atenuado." },
      { key: "4. 'Heaven forbid / God forbid'", value: "Expresa el deseo ferviente de que algo no ocurra." },
    ],
    mistake: { bad: "Be that as it is, we will continue.", good: "Be that as it may, we will continue.", note: "'Be that as it may' es una fórmula subjuntiva fija; la forma 'is' es un error." },
    quiz: [
      { q: "The economic outlook is uncertain. ___, we must proceed with the expansion.", options: ["Be that as it may", "Be that as it is", "Being that as it may", "As it may be that"], answer: 0, explain: "'Be that as it may' (sea como fuere) es la expresión subjuntiva fija correcta." },
      { q: "___ to say, the audit revealed zero irregularities.", options: ["Suffice it", "Suffices it", "Sufficing it", "It suffices"], answer: 0, explain: "'Suffice it to say' es la fórmula fija congelada para indicar 'baste decir'." },
      { q: "¿Qué expresión fija subjuntiva transmite aceptación incondicional ante cualquier adversidad futura?", options: ["Come what may", "God forbids", "Far be it to me", "Be it as it may"], answer: 0, explain: "'Come what may' equivale a 'pase lo que pase'." },
    ],
  },
];
