import type { DeckSpec } from "./grammar-pattern-deck-specs-b1-b2";

export const C1_C2_DECK_SPECS: DeckSpec[] = [
  {
    slug: "c1-comparativos-dobles",
    eyebrow: "C1 · Comparativos",
    title: "Comparativos",
    emphasis: "dobles (the … the …)",
    goal: "Ya expresas relaciones proporcionales con the + comparativo, the + comparativo: cuanto más X, más Y.",
    conceptRows: [
      { key: "Estructura", value: "The + comparativo, the + comparativo · The harder you work, the more you achieve.", highlights: ["The harder", "the more"] },
      { key: "Adjetivo", value: "The older I get, the wiser I become.", highlights: ["The older"] },
      { key: "Adverbio", value: "The sooner we leave, the better.", highlights: ["The sooner"] },
      { key: "Registro", value: "muy frecuente en escritura formal y argumentos", highlights: ["The"] },
    ],
    mistake: { bad: "More you study, more you learn.", good: "The more you study, the more you learn.", note: "ambas partes llevan the" },
    quiz: [{ q: "___ earlier we start, ___ sooner we finish.", options: ["The / the", "More / more"], answer: 0, explain: "Patrón proporcional: the + comparativo en ambas cláusulas." }],
  },
  {
    slug: "c1-relativas-complejas",
    eyebrow: "C1 · Relativas",
    title: "Estructuras",
    emphasis: "relativas complejas",
    goal: "Ya usas relativas reducidas, preposición al inicio y relativas encajadas para empaquetar información precisa.",
    conceptRows: [
      { key: "Reducida", value: "The report submitted yesterday… (= which was submitted)", highlights: ["submitted"] },
      { key: "Prep. inicial", value: "the person to whom I spoke · formal", highlights: ["to whom"] },
      { key: "Encajada", value: "The policy, which the board debated, which analysts criticised…", highlights: ["which"] },
      { key: "Precisión", value: "una sola oración, múltiples capas de detalle", highlights: ["which"] },
    ],
    mistake: { bad: "The man who I spoke to him…", good: "The man to whom I spoke… / The man I spoke to.", note: "no dupliques el pronombre objeto" },
    quiz: [{ q: "The documents ___ last week are ready.", options: ["reviewed", "reviewing"], answer: 0, explain: "Relativa reducida pasiva → participio pasado." }],
  },
  {
    slug: "c1-verbos-delexicales",
    eyebrow: "C1 · Colocaciones",
    title: "Verbos",
    emphasis: "delexicales",
    goal: "Ya combinas make/do/take/have con sustantivos en colocaciones fijas: make a decision, take responsibility.",
    conceptRows: [
      { key: "make", value: "make a mistake · make progress · make an effort", highlights: ["make"] },
      { key: "do", value: "do research · do your best · do business", highlights: ["do"] },
      { key: "take", value: "take action · take responsibility · take a break", highlights: ["take"] },
      { key: "have", value: "have a meeting · have an impact · have trouble", highlights: ["have"] },
    ],
    mistake: { bad: "do a decision", good: "make a decision", note: "colocación fija, no traducible palabra a palabra" },
    quiz: [{ q: "We need to ___ responsibility for the delay.", options: ["take", "make"], answer: 0, explain: "take responsibility es la colocación natural." }],
  },
  {
    slug: "c1-marcadores-discurso",
    eyebrow: "C1 · Discurso",
    title: "Marcadores",
    emphasis: "del discurso",
    goal: "Ya organizas argumentos complejos con marcadores avanzados: notwithstanding, in so far as, to put it another way.",
    conceptRows: [
      { key: "Marco", value: "To put it another way, the risk remains.", highlights: ["To put it another way"] },
      { key: "Concesión", value: "Notwithstanding this, we proceeded.", highlights: ["Notwithstanding"] },
      { key: "Alcance", value: "In so far as I know, the data is accurate.", highlights: ["In so far as"] },
      { key: "Cierre", value: "It goes without saying that safety comes first.", highlights: ["It goes without saying"] },
    ],
    mistake: { bad: "Notwithstanding this, but we continued.", good: "Notwithstanding this, we continued.", note: "no mezcles con but" },
    quiz: [{ q: "___, the figures are still preliminary.", options: ["It goes without saying", "In so far as"], answer: 0, explain: "Introduce algo obvio o acordado." }],
  },
  {
    slug: "c1-anteposicion-enfasis",
    eyebrow: "C1 · Énfasis",
    title: "Anteposición",
    emphasis: "para énfasis",
    goal: "Ya adelantas objetos o adverbiales al inicio de la oración para destacar información y crear contraste.",
    conceptRows: [
      { key: "Objeto", value: "This proposal, we cannot accept.", highlights: ["This proposal"] },
      { key: "Adverbial", value: "On no account should you share the password.", highlights: ["On no account"] },
      { key: "Contraste", value: "The budget I can manage; the timeline is another matter.", highlights: ["The budget"] },
      { key: "Registro", value: "formal, retórico, escrito académico", highlights: ["should"] },
    ],
    mistake: { bad: "This point we cannot ignore it.", good: "This point we cannot ignore.", note: "no repitas el pronombre tras topicalizar" },
    quiz: [{ q: "___ should this data be shared externally.", options: ["Under no circumstances", "Under no circumstance"], answer: 0, explain: "Anteposición + inversión con expresión negativa." }],
  },
  {
    slug: "c1-futuro-en-pasado",
    eyebrow: "C1 · Tiempo",
    title: "Futuro",
    emphasis: "en el pasado",
    goal: "Ya describes planes o predicciones pasadas con was/were going to y would desde un punto de vista anterior.",
    conceptRows: [
      { key: "was going to", value: "I was going to call, but I forgot. · plan no cumplido", highlights: ["was going to"] },
      { key: "would", value: "We knew the price would rise. · predicción desde el pasado", highlights: ["would rise"] },
      { key: "Narrativa", value: "She was going to resign when the offer arrived.", highlights: ["was going to"] },
      { key: "Reported", value: "He said he would finish by Friday.", highlights: ["would finish"] },
    ],
    mistake: { bad: "I was going to called him.", good: "I was going to call him.", note: "going to + base del verbo" },
    quiz: [{ q: "They ___ going to launch in March, but postponed.", options: ["were", "would"], answer: 0, explain: "Plan pasado → was/were going to." }],
  },
  {
    slug: "c1-matices-modales",
    eyebrow: "C1 · Modales",
    title: "Matices",
    emphasis: "modales",
    goal: "Ya usas will/would para hábitos característicos y may/might en concesiones: That may be true, but…",
    conceptRows: [
      { key: "will (hábito)", value: "She will talk for hours. · tendencia irritante o típica", highlights: ["will talk"] },
      { key: "would (pasado)", value: "He would always arrive late.", highlights: ["would always"] },
      { key: "may/might (concesión)", value: "That may be true, but the data suggests otherwise.", highlights: ["may be true"] },
      { key: "Matiz", value: "no es futuro literal; es actitud del hablante", highlights: ["will", "may"] },
    ],
    mistake: { bad: "She will to talk for hours.", good: "She will talk for hours.", note: "will + base, sin to" },
    quiz: [{ q: "He ___ always forget his keys. (hábito pasado)", options: ["would", "will"], answer: 0, explain: "Hábito pasado característico → would." }],
  },
  {
    slug: "c1-phrasal-verbs-avanzados",
    eyebrow: "C1 · Phrasal verbs",
    title: "Phrasal verbs",
    emphasis: "avanzados",
    goal: "Ya dominas phrasals de tres partes, separables e idiomáticos en registros formales e informales.",
    conceptRows: [
      { key: "Tres partes", value: "put up with · get away with · look forward to", highlights: ["put up with"] },
      { key: "Separable", value: "turn the offer down · turn down the offer", highlights: ["turn down"] },
      { key: "Inseparable", value: "come across as · run into someone", highlights: ["come across"] },
      { key: "Idiomático", value: "significado no literal · aprende como unidad", highlights: ["put up with"] },
    ],
    mistake: { bad: "I can't put up it anymore.", good: "I can't put up with it anymore.", note: "pronombre entre verbo y partícula si es separable" },
    quiz: [{ q: "We had to ___ the noise for months.", options: ["put up with", "put with up"], answer: 0, explain: "put up with es inseparable en orden fijo." }],
  },
  {
    slug: "c1-subjuntivo-formal",
    eyebrow: "C1 · Subjuntivo",
    title: "Subjuntivo",
    emphasis: "formal",
    goal: "Ya usas la forma base tras suggest/insist/demand + that: They insisted that he be present.",
    conceptRows: [
      { key: "Verbos", value: "suggest · insist · demand · recommend · propose", highlights: ["insist"] },
      { key: "Estructura", value: "that + sujeto + base · no -s en 3ª persona", highlights: ["that he be"] },
      { key: "Ejemplo", value: "She demanded that he leave immediately.", highlights: ["leave"] },
      { key: "Alternativa", value: "should + infinitivo en registro menos formal", highlights: ["should"] },
    ],
    mistake: { bad: "They insisted that he leaves.", good: "They insisted that he leave.", note: "subjuntivo formal → base sin -s" },
    quiz: [{ q: "The board recommended that she ___ the role.", options: ["take", "takes"], answer: 0, explain: "Tras recommend that → forma base." }],
  },
  {
    slug: "c1-pasado-irreal-avanzado",
    eyebrow: "C1 · Pasado irreal",
    title: "Pasado irreal",
    emphasis: "avanzado",
    goal: "Ya usas wish/if only + past perfect, as if + past, e it's time + past simple para significados hipotéticos.",
    conceptRows: [
      { key: "wish + pp", value: "I wish I had studied harder. · arrepentimiento pasado", highlights: ["had studied"] },
      { key: "as if", value: "He talks as if he knew everything. · irreal presente", highlights: ["knew"] },
      { key: "it's time", value: "It's high time we left. · debería ocurrir ya", highlights: ["we left"] },
      { key: "Idea", value: "pasado = irreal, no tiempo literal", highlights: ["wish", "as if"] },
    ],
    mistake: { bad: "It's time we leave.", good: "It's time we left.", note: "it's time + past simple para urgencia" },
    quiz: [{ q: "She acts as if she ___ the owner.", options: ["were", "is"], answer: 0, explain: "as if + past para hipótesis irreal." }],
  },
  {
    slug: "c2-elipsis-sustitucion-avanzada",
    eyebrow: "C2 · Cohesión",
    title: "Elipsis y sustitución",
    emphasis: "avanzadas",
    goal: "Ya comprimes el discurso con elipsis sofisticada y sustitución con do so, not y one/ones en textos densos.",
    conceptRows: [
      { key: "Elipsis verbal", value: "A: Will you attend? B: I might. (= might attend)", highlights: ["might"] },
      { key: "do so", value: "The firm may restructure if required to do so.", highlights: ["do so"] },
      { key: "not", value: "Will it succeed? I hope not.", highlights: ["not"] },
      { key: "Economía", value: "evita repetir cláusulas completas con elegancia", highlights: ["do so"] },
    ],
    mistake: { bad: "I hope no.", good: "I hope not.", note: "not sustituye la cláusula negativa completa" },
    quiz: [{ q: "The board may vote; shareholders are expected to do ___.", options: ["so", "it"], answer: 0, explain: "do so recupera la acción vote." }],
  },
  {
    slug: "c2-sintagmas-nominales",
    eyebrow: "C2 · Sintaxis",
    title: "Sintagmas",
    emphasis: "nominales complejos",
    goal: "Ya construyes sintagmas nominales densos con modificadores, participios, prep. y relativas alrededor del núcleo.",
    conceptRows: [
      { key: "Núcleo", value: "sustantivo central · decision", highlights: ["decision"] },
      { key: "Modificadores", value: "the recent controversial board decision on restructuring", highlights: ["recent", "controversial"] },
      { key: "Participio", value: "the policy announced yesterday", highlights: ["announced"] },
      { key: "Relativa", value: "the analyst who led the review", highlights: ["who led"] },
    ],
    mistake: { bad: "a decision recent controversial", good: "a recent controversial decision", note: "orden de adjetivos en inglés" },
    quiz: [{ q: "Identify the head noun: 'the rapidly evolving regulatory framework'", options: ["rapidly", "framework", "regulatory"], answer: 1, explain: "framework es el núcleo del sintagma." }],
  },
  {
    slug: "c2-concesion-avanzada",
    eyebrow: "C2 · Concesión",
    title: "Concesión",
    emphasis: "avanzada",
    goal: "Ya concedes y matizas con much as, whatever, however + adj/adv y estructuras invertidas de concesión.",
    conceptRows: [
      { key: "much as", value: "Much as I admire her work, I disagree.", highlights: ["Much as"] },
      { key: "whatever", value: "Whatever the outcome, we proceed.", highlights: ["Whatever"] },
      { key: "however", value: "However hard we try, delays persist.", highlights: ["However hard"] },
      { key: "Matiz", value: "reconoces un punto antes de refutarlo", highlights: ["Much as"] },
    ],
    mistake: { bad: "Much as I admire her, but I disagree.", good: "Much as I admire her, I disagree.", note: "no añadas but tras much as" },
    quiz: [{ q: "___ the evidence, doubts remain.", options: ["Compelling as", "As compelling"], answer: 0, explain: "Adj + as + sujeto + verbo: concesión invertida." }],
  },
  {
    slug: "c2-condicionales-idiomaticas",
    eyebrow: "C2 · Condicionales",
    title: "Condicionales",
    emphasis: "idiomáticas",
    goal: "Ya usas condicionales comprimidas: Had I known…, Were it not for…, If need be, If so/if not.",
    conceptRows: [
      { key: "Had I known", value: "Had I known, I would have acted. · elipsis de if", highlights: ["Had I known"] },
      { key: "Were it not for", value: "Were it not for her help, we would have failed.", highlights: ["Were it not for"] },
      { key: "If need be", value: "We can reschedule if need be.", highlights: ["if need be"] },
      { key: "If so / if not", value: "Is it urgent? If so, call me.", highlights: ["If so"] },
    ],
    mistake: { bad: "If I would have known…", good: "Had I known… / If I had known…", note: "condicional pasado sin would en la parte if" },
    quiz: [{ q: "___ it not for the grant, the project would collapse.", options: ["Were", "Was"], answer: 0, explain: "Were it not for = if it were not for." }],
  },
  {
    slug: "c2-inversion-literaria",
    eyebrow: "C2 · Inversión",
    title: "Inversión",
    emphasis: "literaria",
    goal: "Ya creas énfasis dramático con So great was…, Such was… y otras inversiones literarias.",
    conceptRows: [
      { key: "So + adj", value: "So great was her despair that she resigned.", highlights: ["So great was"] },
      { key: "Such + noun", value: "Such was his courage that everyone followed.", highlights: ["Such was"] },
      { key: "Registro", value: "literario, ceremonial, retórico", highlights: ["So great"] },
      { key: "Efecto", value: "llama la atención al elemento inicial", highlights: ["was"] },
    ],
    mistake: { bad: "So great her despair was…", good: "So great was her despair…", note: "inversión: So + adj + was + sujeto" },
    quiz: [{ q: "___ impressive was the result that applause erupted.", options: ["So", "Such"], answer: 0, explain: "So + adjetivo + was + sujeto." }],
  },
  {
    slug: "c2-topicalizacion",
    eyebrow: "C2 · Topicalización",
    title: "Orden de palabras",
    emphasis: "marcado",
    goal: "Ya topicalizas elementos al inicio para marcar el tema del discurso y crear cohesión temática.",
    conceptRows: [
      { key: "Topicalización", value: "This issue, we have debated for years.", highlights: ["This issue"] },
      { key: "Foco", value: "señala qué es el tema de la frase siguiente", highlights: ["This issue"] },
      { key: "Contraste", value: "The data I trust; the interpretation, less so.", highlights: ["The data"] },
      { key: "Estilo", value: "escritura formal, retórica, análisis", highlights: ["less so"] },
    ],
    mistake: { bad: "This issue, we have debated it for years.", good: "This issue, we have debated for years.", note: "no dupliques el objeto topicalizado" },
    quiz: [{ q: "The timeline, ___ cannot accept.", options: ["we", "us"], answer: 0, explain: "Sujeto tras topicalización: we." }],
  },
  {
    slug: "c2-modalidad-matizada",
    eyebrow: "C2 · Modalidad",
    title: "Modalidad",
    emphasis: "matizada",
    goal: "Ya calibras certeza con may well, must have, can't have y would have to be con precisión epistémica.",
    conceptRows: [
      { key: "may well", value: "It may well be true. · probabilidad alta", highlights: ["may well"] },
      { key: "must have", value: "She must have left early. · inferencia fuerte pasada", highlights: ["must have"] },
      { key: "can't have", value: "He can't have known. · imposibilidad inferida", highlights: ["can't have"] },
      { key: "would have to", value: "That would have to be the answer. · conclusión forzada", highlights: ["would have to"] },
    ],
    mistake: { bad: "She must left early.", good: "She must have left early.", note: "inferencia pasada → must have + pp" },
    quiz: [{ q: "They ___ have missed the memo; everyone else complied.", options: ["can't", "mustn't"], answer: 0, explain: "can't have = imposible que haya ocurrido." }],
  },
  {
    slug: "c2-marcadores-pragmaticos",
    eyebrow: "C2 · Pragmática",
    title: "Marcadores",
    emphasis: "pragmáticos",
    goal: "Ya posicionas tu actitud con frankly, presumably, as it were y if you ask me.",
    conceptRows: [
      { key: "frankly", value: "Frankly, the plan won't work. · honestidad directa", highlights: ["Frankly"] },
      { key: "presumably", value: "Presumably, they already know.", highlights: ["Presumably"] },
      { key: "as it were", value: "a kind of bridge, as it were · distanciamiento irónico", highlights: ["as it were"] },
      { key: "if you ask me", value: "If you ask me, it's too risky. · opinión personal", highlights: ["If you ask me"] },
    ],
    mistake: { bad: "Frankly to say…", good: "Frankly, … / To be frank, …", note: "frankly va al inicio o como frase hecha" },
    quiz: [{ q: "___, the merger is already decided.", options: ["Presumably", "Frankly"], answer: 0, explain: "Presumably = suposición razonable, no confesión directa." }],
  },
  {
    slug: "c2-cambio-registro",
    eyebrow: "C2 · Registro",
    title: "Cambio de",
    emphasis: "registro",
    goal: "Ya pasas de formal a informal (y viceversa) ajustando densidad, pasiva, nominalización y phrasal verbs.",
    conceptRows: [
      { key: "Formal", value: "The implementation was delayed. · pasiva, nominalización", highlights: ["implementation"] },
      { key: "Informal", value: "They put off rolling it out. · phrasal, activa", highlights: ["put off"] },
      { key: "Variables", value: "densidad, contracciones, explicitud, evidencia", highlights: ["formal", "informal"] },
      { key: "Propósito", value: "misma información, distinta relación con la audiencia", highlights: ["audience"] },
    ],
    mistake: { bad: "Hey, pursuant to our discussion…", good: "As we discussed… / Following our chat…", note: "alinea registro con canal y relación" },
    quiz: [{ q: "Which is more formal?", options: ["We need to look into it.", "The matter requires investigation."], answer: 1, explain: "Nominalización + vocabulario latino = registro formal." }],
  },
  {
    slug: "c2-pasiva-estilistica",
    eyebrow: "C2 · Pasiva",
    title: "Pasiva",
    emphasis: "estilística",
    goal: "Ya usas pasiva impersonal y reportada: It is believed that…, He is said to be…, It is reported that…",
    conceptRows: [
      { key: "It is believed", value: "It is believed that costs will rise.", highlights: ["It is believed"] },
      { key: "is said to", value: "He is said to be considering retirement.", highlights: ["is said to be"] },
      { key: "Impersonal", value: "oculta o difumina el agente", highlights: ["It is"] },
      { key: "Registro", value: "académico, periodístico, oficial", highlights: ["believed", "reported"] },
    ],
    mistake: { bad: "People is said that…", good: "It is said that… / He is said to…", note: "estructura impersonal fija" },
    quiz: [{ q: "The CEO ___ to be negotiating a deal.", options: ["is said", "says"], answer: 0, explain: "Reportaje pasivo → is said to + infinitivo." }],
  },
  {
    slug: "c2-subjuntivo-formulas",
    eyebrow: "C2 · Subjuntivo",
    title: "Subjuntivo",
    emphasis: "fórmulas fijas",
    goal: "Ya reconoces y usas fórmulas subjuntivas: be that as it may, come what may, suffice it to say, so be it.",
    conceptRows: [
      { key: "be that as it may", value: "sea como fuere · concesión formal", highlights: ["be that as it may"] },
      { key: "come what may", value: "pase lo que pase", highlights: ["come what may"] },
      { key: "suffice it to say", value: "baste decir", highlights: ["suffice it to say"] },
      { key: "so be it", value: "así sea · aceptación solemne", highlights: ["so be it"] },
    ],
    mistake: { bad: "Be that as it is…", good: "Be that as it may…", note: "fórmula fija congelada" },
    quiz: [{ q: "___, we must proceed regardless.", options: ["Come what may", "Comes what may"], answer: 0, explain: "Fórmula subjuntiva fija: come what may." }],
  },
];
