import type { DeckSpec } from "./generate-grammar-pattern-decks";

export const B1_B2_DECK_SPECS: DeckSpec[] = [
  {
    slug: "b1-articulos-superlativos-cero",
    eyebrow: "B1 · Artículos",
    title: "Artículos con",
    emphasis: "superlativos y cero",
    goal: "Ya usas the con superlativos y omites el artículo con sustantivos abstractos o generales.",
    conceptRows: [
      { key: "Superlativo", value: "the + -est / most · She is the tallest girl in class.", highlights: ["the"] },
      { key: "Entidad única", value: "the sun, the internet, the government · cosas únicas", highlights: ["the"] },
      { key: "Artículo cero (Abstracto)", value: "sin artículo · Love and health are important.", highlights: ["Love"] },
      { key: "Artículo cero (Plural general)", value: "sin artículo · Cats love milk.", highlights: ["Cats"] },
    ],
    structureRows: [
      { key: "Afirmativa (Superlativo)", value: "Sujeto + be + the + superlativo + complemento · This is the cheapest room.", highlights: ["the cheapest"] },
      { key: "Afirmativa (Cero abstracto)", value: "Sustantivo incontable / plural + verbo · Knowledge is power.", highlights: ["Knowledge"] },
      { key: "Negativa (Cero abstracto)", value: "Sujeto + don't/doesn't + verbo + sustantivo general · I don't like fast food.", highlights: ["fast food"] },
      { key: "Interrogativa", value: "Is/Are + sustantivo general + adjetivo? · Are computers necessary?", highlights: ["computers"] },
    ],
    contextExamples: [
      { key: "En el trabajo", value: "This is the most efficient software we have used this year." },
      { key: "Hablando del clima", value: "August is usually the hottest month in Spain." },
      { key: "Filosofía de vida", value: "Money cannot buy happiness or peace of mind." },
      { key: "Intereses personales", value: "I enjoy reading books about science and technology." },
    ],
    contrastColumns: [
      { label: "The + Sustantivo (Específico)", rule: "Se refiere a cosas concretas o ya mencionadas previamente", examples: ["The dogs in that garden are barking."] },
      { label: "Artículo Cero (General)", rule: "Habla de toda la especie, categoría o concepto en abstracto", examples: ["Dogs are very loyal animals."] },
    ],
    quickReferenceRows: [
      { key: "Superlativos", value: "Usa siempre 'the' antes de '-est' o 'most' (ej. the best, the most interesting)." },
      { key: "Conceptos abstractos", value: "No uses 'the' para educación, amor, dinero o vida en general." },
      { key: "Plurales generales", value: "Omite 'the' al hablar de cosas o personas en plural general." },
      { key: "Entidades únicas", value: "Usa 'the' con el sol, la luna, la tierra o el internet." },
    ],
    mistake: { bad: "The life is beautiful when you travel.", good: "Life is beautiful when you travel.", note: "'life' en sentido general no lleva el artículo 'the'" },
    quiz: [
      { q: "Tokyo is ___ largest city in Japan.", options: ["the", "a", "cero (sin artículo)"], answer: 0, explain: "Los adjetivos superlativos como 'largest' requieren el artículo definido 'the'." },
      { q: "___ is essential for human survival.", options: ["Water", "The water", "A water"], answer: 0, explain: "Los sustantivos incontables usados en sentido general no llevan artículo." },
      { q: "I prefer ___ to violent movies.", options: ["comedies", "the comedies", "a comedy"], answer: 0, explain: "Para referirse a un género o categoría plural en general se usa el artículo cero." },
    ],
  },
  {
    slug: "b1-modificadores-comparativos",
    eyebrow: "B1 · Comparativos",
    title: "Modificadores de",
    emphasis: "comparativos",
    goal: "Ya intensificas comparativos con much, far, a bit, a little y slightly.",
    conceptRows: [
      { key: "much / far", value: "gran diferencia (+++) · much bigger, far more expensive", highlights: ["much", "far"] },
      { key: "a bit / a little", value: "pequeña diferencia (+) · a bit colder, a little easier", highlights: ["a bit", "a little"] },
      { key: "slightly", value: "diferencia muy leve · slightly taller than me", highlights: ["slightly"] },
      { key: "even", value: "énfasis adicional · even faster than before", highlights: ["even"] },
    ],
    structureRows: [
      { key: "Afirmativa (Gran dif.)", value: "Sujeto + verbo + much/far + comparativo + than... · This train is much faster than the bus.", highlights: ["much faster"] },
      { key: "Afirmativa (Peq. dif.)", value: "Sujeto + verbo + a bit/a little + comparativo + than... · My room is a bit larger than yours.", highlights: ["a bit larger"] },
      { key: "Negativa", value: "Sujeto + isn't/aren't + much + comparativo... · It isn't much more expensive.", highlights: ["much more"] },
      { key: "Interrogativa", value: "Is + sujeto + slightly + comparativo + than...? · Is this seat slightly cheaper than that one?", highlights: ["slightly cheaper"] },
    ],
    contextExamples: [
      { key: "De compras", value: "This leather jacket is far more durable than the plastic one." },
      { key: "En la oficina", value: "The new strategy is much more effective for our team." },
      { key: "Comparando precios", value: "The hotel room was only a bit cheaper on weekdays." },
      { key: "Ajuste de horario", value: "Could we meet slightly earlier tomorrow morning?" },
    ],
    contrastColumns: [
      { label: "Much / Far (Intensificadores fuertes)", rule: "Indican un margen o diferencia amplia entre dos elementos", examples: ["Flying is far faster than driving."] },
      { label: "A bit / Slightly (Intensificadores suaves)", rule: "Indican una diferencia mínima o imperceptible entre dos elementos", examples: ["Today is slightly warmer than yesterday."] },
    ],
    quickReferenceRows: [
      { key: "Modificador + Comparativo", value: "El intensificador va SIEMPRE antes del comparativo (much taller, NO taller much)." },
      { key: "No dupliques 'more'", value: "No digas 'much more better', di 'much better'." },
      { key: "Far (formal)", value: "'Far more expensive' suena más elegante que 'a lot more expensive'." },
      { key: "A bit (informal)", value: "Úsalo en conversaciones cotidianas en lugar de 'slightly'." },
    ],
    mistake: { bad: "She feels more much better today.", good: "She feels much better today.", note: "el modificador 'much' se coloca antes del comparativo sin añadir 'more'" },
    quiz: [
      { q: "Learning Chinese is ___ harder than learning Spanish for me.", options: ["much", "more", "very"], answer: 0, explain: "Para intensificar un comparativo corto (-er) se utiliza 'much' o 'far', no 'very' ni 'more'." },
      { q: "The new smartphone is only ___ more expensive than the old model.", options: ["a bit", "many", "too"], answer: 0, explain: "'A bit' modifica comparativos indicando una diferencia pequeña." },
      { q: "This apartment is ___ larger than our previous one.", options: ["far", "very", "so"], answer: 0, explain: "'Far' actúa como intensificador fuerte ante un comparativo." },
    ],
  },
  {
    slug: "b1-preposiciones-dependientes",
    eyebrow: "B1 · Preposiciones",
    title: "Preposiciones",
    emphasis: "dependientes",
    goal: "Ya eliges la preposición correcta tras adjetivos y verbos: depend on, good at, interested in, proud of.",
    conceptRows: [
      { key: "depend on / rely on", value: "depender de / confiar en · It depends on the weather.", highlights: ["on"] },
      { key: "good at / bad at", value: "habilidad o torpeza · She is good at maths.", highlights: ["at"] },
      { key: "interested in", value: "interesado en · interested in art", highlights: ["in"] },
      { key: "proud of / afraid of", value: "orgulloso de / temeroso de · proud of her achievements", highlights: ["of"] },
    ],
    structureRows: [
      { key: "Afirmativa (Adjetivo)", value: "Sujeto + be + adjetivo + preposición + sustantivo/-ing · She is good at solving problems.", highlights: ["good at"] },
      { key: "Negativa (Verbo)", value: "Sujeto + don't/doesn't + verbo + preposición... · We don't depend on public transport.", highlights: ["depend on"] },
      { key: "Interrogativa", value: "What + correspondencia be + sujeto + adjetivo + preposición? · What are you interested in?", highlights: ["interested in"] },
      { key: "Verbo + preposición", value: "Sujeto + verbo + preposición + objeto · Everything depends on the situation.", highlights: ["depends on"] },
    ],
    contextExamples: [
      { key: "Entrevista de trabajo", value: "I am very good at working under pressure and managing teams." },
      { key: "Hobbies y gustos", value: "My brother is really interested in learning foreign languages." },
      { key: "Emociones familiares", value: "Her parents are extremely proud of her academic achievements." },
      { key: "Decisiones", value: "Whether we go to the beach depends on the weather tomorrow." },
    ],
    contrastColumns: [
      { label: "Good at / Bad at", rule: "Usado exclusivamente para describir destrezas o habilidades personales", examples: ["He is good at playing chess."] },
      { label: "Interested in", rule: "Usado para describir atracción, curiosidad o interés hacia un tema", examples: ["She is interested in modern art."] },
    ],
    quickReferenceRows: [
      { key: "Preposición + -ing", value: "Tras cualquier preposición, el verbo siguiente debe ir en gerundio (interested in buying)." },
      { key: "Depend on", value: "Nunca digas 'depend of'; la preposición correcta en inglés es 'on'." },
      { key: "Good at", value: "No uses 'good in' para habilidades o aptitudes." },
      { key: "Afraid of / Proud of", value: "Adjetivos de sentimiento suelen combinarse con la preposición 'of'." },
    ],
    mistake: { bad: "Everything depends of your choice.", good: "Everything depends on your choice.", note: "el verbo 'depend' exige la preposición 'on', jamás 'of'" },
    quiz: [
      { q: "Are you interested ___ joining our English book club?", options: ["in", "on", "at"], answer: 0, explain: "El adjetivo 'interested' rige siempre la preposición 'in'." },
      { q: "My sister has always been very good ___ playing the piano.", options: ["at", "in", "for"], answer: 0, explain: "Para expresar destreza en una actividad se usa 'good at'." },
      { q: "They are afraid ___ losing their current jobs.", options: ["of", "about", "from"], answer: 0, explain: "El adjetivo 'afraid' se combina con la preposición 'of'." },
    ],
  },
  {
    slug: "b1-futuro-continuo",
    eyebrow: "B1 · Futuro",
    title: "Futuro",
    emphasis: "continuo",
    goal: "Ya describes acciones en progreso en un momento futuro determinado con will be + -ing.",
    conceptRows: [
      { key: "Acción en curso futura", value: "will be + -ing · At 10 am, I will be taking an exam.", highlights: ["will be taking"] },
      { key: "Marcadores temporales", value: "this time tomorrow, at 8 tonight, in five years", highlights: ["this time tomorrow"] },
      { key: "Preguntas corteses", value: "Will you be using the printer?", highlights: ["Will you be"] },
      { key: "Planes programados", value: "acciones previstas en curso como rutina", highlights: ["will be"] },
    ],
    structureRows: [
      { key: "Afirmativa", value: "Sujeto + will be + verbo-ing + tiempo futuro · I will be sleeping at midnight.", highlights: ["will be sleeping"] },
      { key: "Negativa", value: "Sujeto + won't be + verbo-ing + tiempo futuro · She won't be working next week.", highlights: ["won't be working"] },
      { key: "Interrogativa", value: "Will + sujeto + be + verbo-ing...? · Will they be arriving around 7 pm?", highlights: ["Will they be arriving"] },
    ],
    contextExamples: [
      { key: "Rutina de estudio", value: "This time next week, I will be lying on the beach in Valencia." },
      { key: "En el trabajo", value: "Please don't call me at 3 pm; I will be presenting our report." },
      { key: "Cortesía", value: "Will you be passing by the supermarket on your way home?" },
      { key: "Planes grupales", value: "They will be staying with us during the holiday weekend." },
    ],
    contrastColumns: [
      { label: "Will (Futuro simple)", rule: "Decisiones espontáneas o eventos puntuales futuros sin duración", examples: ["I will call you at 8."] },
      { label: "Will be + -ing (Futuro continuo)", rule: "Enfatiza una acción que ya estará transcurriendo en un momento exacto", examples: ["At 8, I will be having dinner."] },
    ],
    quickReferenceRows: [
      { key: "Punto temporal específico", value: "Exige mencionar o sobreentender un momento futuro puntual." },
      { key: "Forma invariable 'be'", value: "'will be' no cambia según la persona (I will be, She will be)." },
      { key: "Preguntas de cortesía", value: "'Will you be using...?' suena más educado que 'Are you going to use...?'." },
      { key: "Negativa 'won't be'", value: "Contracción habitual de 'will not be'." },
    ],
    mistake: { bad: "Don't call me at 9 because I will work.", good: "Don't call me at 9 because I will be working.", note: "se usa futuro continuo porque la acción estará en progreso en ese momento exacto" },
    quiz: [
      { q: "At this exact time tomorrow, we ___ across the Atlantic.", options: ["will be flying", "will fly", "are fly"], answer: 0, explain: "Para una acción que estará en desarrollo en un punto futuro concreto se usa 'will be + -ing'." },
      { q: "___ you be using your computer this afternoon?", options: ["Will", "Do", "Are"], answer: 0, explain: "Forma interrogativa de futuro continuo para preguntar amablemente sobre intenciones: 'Will + sujeto + be + -ing'." },
      { q: "He won't ___ working on Sunday, so we can meet up.", options: ["be", "been", "is"], answer: 0, explain: "La estructura del futuro continuo negativo requiere 'won't be + -ing'." },
    ],
  },
  {
    slug: "b1-pasado-perfecto",
    eyebrow: "B1 · Pasado perfecto",
    title: "Pasado",
    emphasis: "perfecto",
    goal: "Ya ordenas dos acciones pasadas usando had + participio para la acción anterior en el tiempo.",
    conceptRows: [
      { key: "Pasado del pasado", value: "had + participio · The train had left when I arrived.", highlights: ["had left"] },
      { key: "Conectores clave", value: "when, before, after, by the time, already, just", highlights: ["by the time"] },
      { key: "Experiencia previa pas.", value: "had never seen snow until last winter", highlights: ["had never seen"] },
      { key: "Causa y efecto pasado", value: "He failed because he hadn't studied", highlights: ["hadn't studied"] },
    ],
    structureRows: [
      { key: "Afirmativa", value: "Sujeto + had + participio pasado · She had finished her homework before dinner.", highlights: ["had finished"] },
      { key: "Negativa", value: "Sujeto + hadn't + participio pasado · They hadn't seen each other for years.", highlights: ["hadn't seen"] },
      { key: "Interrogativa", value: "Had + sujeto + participio pasado...? · Had you met him before the party?", highlights: ["Had you met"] },
    ],
    contextExamples: [
      { key: "Malentendido u olvido", value: "When I reached the airport, I realized I had left my passport at home." },
      { key: "Cine y eventos", value: "By the time we got to the cinema, the movie had already started." },
      { key: "Experiencia única", value: "She was nervous because she had never flown in a helicopter before." },
      { key: "Éxito laboral", value: "He landed the job because he had prepared his presentation thoroughly." },
    ],
    contrastColumns: [
      { label: "Pasado simple (V2)", rule: "Acción más reciente o secuencia cronológica paso a paso en el pasado", examples: ["I opened the door and entered."] },
      { label: "Pasado perfecto (had + V3)", rule: "Acción ocurrida ANTES de otra acción pasada de referencia", examples: ["The meeting had ended before I arrived."] },
    ],
    quickReferenceRows: [
      { key: "Auxiliar invariable 'had'", value: "Se usa 'had' para todas las personas (I, he, we, they had)." },
      { key: "By the time...", value: "Suele introducir una cláusula en pasado simple y requiere pasado perfecto en la principal." },
      { key: "Already / Just", value: "Se colocan entre 'had' y el participio (had already left)." },
      { key: "No abuses de él", value: "Si las acciones siguen un orden cronológico claro con 'and', usa pasado simple." },
    ],
    mistake: { bad: "When I arrived at the station, the bus already left.", good: "When I arrived at the station, the bus had already left.", note: "la salida del autobús ocurrió antes de la llegada, requiere pasado perfecto" },
    quiz: [
      { q: "By the time Sarah arrived, everybody ___ home.", options: ["had gone", "went", "has gone"], answer: 0, explain: "La acción de irse a casa ocurrió antes de la llegada de Sarah → 'had gone'." },
      { q: "I couldn't get into my flat because I ___ my keys.", options: ["had lost", "lost", "have lost"], answer: 0, explain: "Perder las llaves ocurrió con anterioridad a no poder entrar." },
      { q: "___ you ever visited London before you moved there?", options: ["Had", "Have", "Did"], answer: 0, explain: "Experiencia previa a un momento del pasado → 'Had + sujeto + participio'." },
    ],
  },
  {
    slug: "b1-condicional-cero",
    eyebrow: "B1 · Condicional cero",
    title: "Condicional",
    emphasis: "cero",
    goal: "Ya expresas hechos científicos, verdades generales y reglas con if / when + presente simple.",
    conceptRows: [
      { key: "Causa y efecto constante", value: "If + presente simple, presente simple", highlights: ["If"] },
      { key: "Verdades generales", value: "If you heat ice, it melts.", highlights: ["melts"] },
      { key: "Equivalencia con 'when'", value: "When it rains, the grass gets wet.", highlights: ["When"] },
      { key: "Instrucciones y reglas", value: "If the alarm sounds, leave the building.", highlights: ["If"] },
    ],
    structureRows: [
      { key: "Afirmativa", value: "If/When + sujeto + presente, sujeto + presente · If you press this button, the light turns on.", highlights: ["If you press", "turns on"] },
      { key: "Negativa", value: "If + sujeto + don't/doesn't + verbo, sujeto + don't/doesn't + verbo · If you don't water plants, they die.", highlights: ["don't water", "die"] },
      { key: "Interrogativa", value: "What happens if + sujeto + presente simple? · What happens if you mix red and yellow?", highlights: ["What happens if"] },
    ],
    contextExamples: [
      { key: "Ciencia y cocina", value: "If you boil water long enough, it evaporates into steam." },
      { key: "Salud y cuerpo", value: "If people don't sleep well, they feel tired the next day." },
      { key: "Normas de tráfico", value: "If the traffic light is red, drivers must stop." },
      { key: "Rutinas personales", value: "When I drink coffee late at night, I cannot sleep." },
    ],
    contrastColumns: [
      { label: "Condicional Cero", rule: "Hechos siempre ciertos, leyes físicas o hábitos universales incontestables", examples: ["If you drop a stone, it falls."] },
      { label: "Primer Condicional", rule: "Una situación específica, particular y probable en el futuro", examples: ["If it rains tomorrow, we will stay home."] },
    ],
    quickReferenceRows: [
      { key: "Sin 'will' en condicional cero", value: "Ambas cláusulas utilizan presente simple." },
      { key: "If = When", value: "Se pueden intercambiar libremente al hablar de verdades generales." },
      { key: "Unless", value: "Significa 'if not' (a menos que). Ej: Unless it rains, plants wither." },
      { key: "Uso de comas", value: "Pon coma solo cuando la cláusula con 'if' va al inicio de la oración." },
    ],
    mistake: { bad: "If you will heat water to 100°C, it boils.", good: "If you heat water to 100°C, it boils.", note: "en condicional cero no se usa 'will' tras 'if', solo presente simple" },
    quiz: [
      { q: "If you touch a hot stove, you ___ yourself.", options: ["burn", "will burn", "burned"], answer: 0, explain: "Verdad general inmediata → presente simple en ambas oraciones." },
      { q: "When the sun goes down, it ___ dark.", options: ["gets", "will get", "got"], answer: 0, explain: "Hecho natural constante: 'When + presente, presente'." },
      { q: "Ice melts if you ___ it out of the freezer.", options: ["leave", "will leave", "left"], answer: 0, explain: "Cláusula con 'if' en condicional cero siempre requiere presente simple." },
    ],
  },
  {
    slug: "b1-both-either-neither",
    eyebrow: "B1 · Cuantificadores",
    title: "Both, either",
    emphasis: "y neither",
    goal: "Ya utilizas correctamente both (ambos), either (uno u otro) y neither (ninguno de los dos) con 2 opciones.",
    conceptRows: [
      { key: "both (+ plural)", value: "ambos / los dos · Both restaurants are good.", highlights: ["Both"] },
      { key: "either (+ singular)", value: "cualquiera de los dos · You can take either road.", highlights: ["Either"] },
      { key: "neither (+ singular)", value: "ninguno de los dos · Neither answer is correct.", highlights: ["Neither"] },
      { key: "Correlativos", value: "both... and / either... or / neither... nor", highlights: ["both", "either", "neither"] },
    ],
    structureRows: [
      { key: "Both + plural", value: "Both + sustantivo plural + verbo plural · Both options sound interesting.", highlights: ["Both options"] },
      { key: "Either + singular", value: "Either + sustantivo singular + verbo singular · Either day suits me fine.", highlights: ["Either day"] },
      { key: "Neither + singular", value: "Neither + sustantivo singular + verbo afirmativo · Neither candidate has experience.", highlights: ["Neither candidate"] },
      { key: "Estructura 'of the'", value: "Neither/Either/Both of the + sustantivo plural · Neither of the cars is cheap.", highlights: ["Neither of"] },
    ],
    contextExamples: [
      { key: "Menú y comida", value: "Both dishes taste delicious, so pick whichever you prefer." },
      { key: "Coordinación de reuniones", value: "We can meet on Monday or Tuesday; either day works for me." },
      { key: "Opinión sobre películas", value: "Neither movie was worth watching at the cinema." },
      { key: "Respuestas cortas", value: "—Do you prefer tea or coffee? —Neither, I drink warm water." },
    ],
    contrastColumns: [
      { label: "Either (Opción A u Opción B)", rule: "Expresa alternativa entre dos opciones posibles", examples: ["You can wear either shirt."] },
      { label: "Neither (Ni A ni B)", rule: "Expresa negación de ambas opciones (sin usar sintaxis negativa)", examples: ["Neither shirt fits me."] },
    ],
    quickReferenceRows: [
      { key: "Siempre para 2 elementos", value: "Para 3 o más elementos usa 'all', 'any' o 'none'." },
      { key: "Neither ya es negativo", value: "NUNCA uses verbo negativo con 'neither' (no digas 'neither doesn't work')." },
      { key: "Both exige plural", value: "Both friends are..." },
      { key: "Parejas de conectores", value: "Both... and / Either... or / Neither... nor." },
    ],
    mistake: { bad: "Neither of my brothers don't live here.", good: "Neither of my brothers lives here.", note: "'neither' aporta significado negativo, por lo que el verbo debe ser afirmativo" },
    quiz: [
      { q: "___ of the two candidates passed the final interview.", options: ["Neither", "None", "No one"], answer: 0, explain: "Para negar 2 elementos específicos se utiliza 'Neither'." },
      { q: "You can choose ___ the red coat or the blue jacket.", options: ["either", "both", "neither"], answer: 0, explain: "La estructura correlativa 'either... or' expresa una elección entre dos." },
      { q: "Both my parents ___ doctors.", options: ["are", "is", "be"], answer: 0, explain: "'Both' siempre concierta con verbo en plural." },
    ],
  },
  {
    slug: "b1-make-let-allow",
    eyebrow: "B1 · Causa y permiso",
    title: "Make, let",
    emphasis: "y allow",
    goal: "Ya estructuras make/let + objeto + verbo base y allow + objeto + to + infinitivo.",
    conceptRows: [
      { key: "make", value: "obligar / hacer que alguien haga algo · She made me clean my room.", highlights: ["made me clean"] },
      { key: "let", value: "permitir / dejar hacer algo · My parents let me stay out late.", highlights: ["let me stay"] },
      { key: "allow", value: "permitir (forma formal con 'to') · They don't allow students to use phones.", highlights: ["allow students to"] },
      { key: "Pasiva de Make", value: "be made to do · He was made to apologize.", highlights: ["made to"] },
    ],
    structureRows: [
      { key: "Make (Obligación)", value: "Sujeto + make + persona + verbo base (sin to) · The boss made us work late.", highlights: ["made us work"] },
      { key: "Let (Permiso informal)", value: "Sujeto + let + persona + verbo base (sin to) · Let him speak.", highlights: ["Let him speak"] },
      { key: "Allow (Permiso formal)", value: "Sujeto + allow + persona + to + infinitivo · We allow clients to cancel for free.", highlights: ["allow clients to cancel"] },
    ],
    contextExamples: [
      { key: "Recuerdos escolares", value: "Our teacher made us memorize 50 English verbs every week." },
      { key: "Reglas en el hogar", value: "My flatmates let me borrow their tools whenever I need them." },
      { key: "Normativa de empresa", value: "The company allows employees to work remotely two days a week." },
      { key: "Cine y entretenimiento", value: "Sad movies always make me cry." },
    ],
    contrastColumns: [
      { label: "Let + objeto + verbo base", rule: "Estructura de permiso cotidiana e informal que NO lleva 'to'", examples: ["Let me go."] },
      { label: "Allow + objeto + to + infinitivo", rule: "Estructura de permiso más formal que exige llevar 'to'", examples: ["Allow me to go."] },
    ],
    quickReferenceRows: [
      { key: "Cero 'to' con Let y Make", value: "NUNCA pongas 'to' tras 'let' o 'make' activo (ej. let me stay, make me laugh)." },
      { key: "To obligatorio con Allow", value: "Siempre usa 'allow someone TO do something'." },
      { key: "Pasiva de Make", value: "En pasiva 'make' SÍ lleva 'to': She was made TO pay a fine." },
      { key: "No existe 'be let to'", value: "En pasiva de permiso se usa 'be allowed to'." },
    ],
    mistake: { bad: "My parents didn't let me to go to the party.", good: "My parents didn't let me go to the party.", note: "el verbo 'let' se construye con el objeto y la forma base del verbo sin 'to'" },
    quiz: [
      { q: "The security guard didn't ___ us enter the building.", options: ["allow", "let", "make"], answer: 0, explain: "Como hay un infinitivo con 'to' implícito o explícito ('to enter'), el verbo adecuado es 'allow'." },
      { q: "Her funny joke really made everyone ___.", options: ["laugh", "to laugh", "laughing"], answer: 0, explain: "'Make + objeto' se combina con la forma base del verbo sin 'to'." },
      { q: "Will your boss let you ___ home early today?", options: ["go", "to go", "going"], answer: 0, explain: "'Let + persona' requiere el verbo en su forma base (bare infinitive)." },
    ],
  },
  {
    slug: "b1-wish-presente",
    eyebrow: "B1 · Wish",
    title: "Wish + pasado",
    emphasis: "simple",
    goal: "Ya expresas deseos o lamentos sobre situaciones presentes deseadas con I wish / If only + pasado simple.",
    conceptRows: [
      { key: "Presente irreal", value: "I wish + sujeto + pasado simple · I wish I had a car.", highlights: ["had"] },
      { key: "Estados deseadas", value: "I wish I lived in a warmer country.", highlights: ["lived"] },
      { key: "Uso de 'were'", value: "I wish I were taller / I wish it were summer", highlights: ["were"] },
      { key: "Capacidad", value: "I wish I could speak fluent German.", highlights: ["could"] },
    ],
    structureRows: [
      { key: "Afirmativa (Tener/Estar)", value: "I wish + sujeto + pasado simple · I wish I knew his telephone number.", highlights: ["I wish I knew"] },
      { key: "Negativa", value: "I wish + sujeto + didn't + verbo base · I wish I didn't have to work on Saturday.", highlights: ["didn't have"] },
      { key: "Poder / Capacidad", value: "I wish + sujeto + could + verbo base · I wish we could travel more often.", highlights: ["could travel"] },
    ],
    contextExamples: [
      { key: "Vivienda y clima", value: "I wish I lived closer to the beach so I could swim every morning." },
      { key: "Economía personal", value: "I wish I didn't have to pay so much rent for this apartment." },
      { key: "Habilidades", value: "I wish I could play the guitar like a professional musician." },
      { key: "Trabajo", value: "I wish my job were less stressful during peak season." },
    ],
    contrastColumns: [
      { label: "Hope + Presente", rule: "Expresa un deseo real, posible y alcanzable para el futuro", examples: ["I hope I pass the exam tomorrow."] },
      { label: "Wish + Pasado", rule: "Expresa una situación hipotética o lamento sobre una realidad presente insatisfactoria", examples: ["I wish I passed all my exams without studying."] },
    ],
    quickReferenceRows: [
      { key: "Pasado = Presente irreal", value: "Aunque el verbo va en pasado (had, lived), te refieres al presente actual." },
      { key: "Wish + could", value: "Usa 'could' para deseos sobre habilidades o posibilidades (I wish I could fly)." },
      { key: "Wish + were", value: "En inglés formal se prefiere 'I wish I were' a 'I wish I was'." },
      { key: "No confundas Wish con Hope", value: "Usa 'hope' para eventos probables del futuro." },
    ],
    mistake: { bad: "I wish I have more free time this week.", good: "I wish I had more free time this week.", note: "'wish' requiere pasado simple para indicar un deseo sobre el presente" },
    quiz: [
      { q: "I'm stuck in traffic. I wish I ___ by train today.", options: ["were travelling", "am travelling", "will travel"], answer: 0, explain: "Deseo o lamento sobre una acción presente en curso → 'wish + pasado continuo'." },
      { q: "I wish I ___ speak French as fluently as you.", options: ["could", "can", "would can"], answer: 0, explain: "Deseo sobre una habilidad o posibilidad actual → 'wish + could'." },
      { q: "If only it ___ so cold outside today!", options: ["were not", "is not", "will not be"], answer: 0, explain: "'If only' sigue las mismas reglas que 'wish' exigiendo el pasado hipotético." },
    ],
  },
  {
    slug: "b1-cuantificadores",
    eyebrow: "B1 · Cuantificadores",
    title: "All, most,",
    emphasis: "none, each, every",
    goal: "Ya usas all, most, none, each y every ajustando la concordancia de plural o singular.",
    conceptRows: [
      { key: "all / most (+ plural)", value: "All students passed. / Most people enjoy music.", highlights: ["All", "Most"] },
      { key: "none of (+ determinante)", value: "None of the answers is correct.", highlights: ["None of"] },
      { key: "each (+ singular)", value: "Each member gets a badge (individualizado).", highlights: ["Each"] },
      { key: "every (+ singular)", value: "Every day is a fresh start (todos como grupo).", highlights: ["Every"] },
    ],
    structureRows: [
      { key: "All / Most + Plural", value: "All/Most + sustantivo plural + verbo plural · Most apples are red.", highlights: ["Most apples are"] },
      { key: "Each / Every + Singular", value: "Each/Every + sustantivo singular + verbo singular · Every applicant needs a passport.", highlights: ["Every applicant needs"] },
      { key: "None of + determinante", value: "None of the + sustantivo plural + verbo singular/plural · None of us has finished.", highlights: ["None of us"] },
    ],
    contextExamples: [
      { key: "Organización de eventos", value: "Every guest must register at the main desk upon arrival." },
      { key: "Trabajo en equipo", value: "Each member of our group contributed unique ideas to the project." },
      { key: "Encuestas y opiniones", value: "Most citizens agree with the new environmental policy." },
      { key: "Resultados", value: "None of the submitted applications met all the mandatory criteria." },
    ],
    contrastColumns: [
      { label: "Every + Sustantivo Singular", rule: "Considera a todos los miembros de un grupo juntos colectivamente", examples: ["Every child needs love."] },
      { label: "Each + Sustantivo Singular", rule: "Considera a los miembros de uno en uno, de forma individual", examples: ["Each child received a different present."] },
    ],
    quickReferenceRows: [
      { key: "Every y Each son singulares", value: "NUNCA uses sustantivo en plural tras 'every' o 'each' (every student, NO every students)." },
      { key: "All of / Most of", value: "Usan 'of' solo cuando hay un determinante (all of my friends vs all friends)." },
      { key: "Every day vs Everyday", value: "'Every day' (cada día, adverbio); 'everyday' (cotidiano, adjetivo)." },
      { key: "None of + plural", value: "Lleva verbo singular en registro formal y plural en informal." },
    ],
    mistake: { bad: "Every students in the class has a computer.", good: "Every student in the class has a computer.", note: "'every' exige sustantivo singular" },
    quiz: [
      { q: "___ passenger must show their boarding pass before entering.", options: ["Every", "All", "Most"], answer: 0, explain: "Como 'passenger' está en singular, se requiere 'Every' (o 'Each')." },
      { q: "___ of my friends could come to the party last night.", options: ["None", "No", "Every"], answer: 0, explain: "La estructura 'None of + determinante + plural' expresa 'ninguno de'." },
      { q: "Each room in the hotel ___ equipped with air conditioning.", options: ["is", "are", "be"], answer: 0, explain: "'Each + sustantivo singular' toma un verbo en singular ('is')." },
    ],
  },
  {
    slug: "b2-conectores-avanzados",
    eyebrow: "B2 · Conectores",
    title: "Conectores",
    emphasis: "avanzados",
    goal: "Ya enlazas ideas formales con however, furthermore, therefore y nevertheless.",
    conceptRows: [
      { key: "however (contraste)", value: "Muestra un contraste directo entre dos oraciones · The team worked hard. However, they missed the deadline.", highlights: ["However"] },
      { key: "furthermore (adición)", value: "Añade una razón o argumento adicional con mayor peso · The product is expensive. Furthermore, it lacks support.", highlights: ["Furthermore"] },
      { key: "therefore (consecuencia)", value: "Indica un resultado o consecuencia lógica · Sales dropped; therefore, we had to cut costs.", highlights: ["therefore"] },
      { key: "nevertheless (concesión)", value: "Expresa 'a pesar de ello' en contexto formal · It was raining. Nevertheless, the outdoor event continued.", highlights: ["Nevertheless"] },
    ],
    structureRows: [
      { key: "Afirmativa (Inicio)", value: "Oración 1. Conector + coma + Oración 2 · The proposal was risky. Furthermore, it was costly.", highlights: ["Furthermore,"] },
      { key: "Afirmativa (Punto y coma)", value: "Oración 1; conector + coma + Oración 2 · The results were poor; therefore, we revised the plan.", highlights: ["; therefore,"] },
      { key: "Negativa", value: "Sujeto + verbo negativo. Conector + coma + Oración · We didn't win. However, we learned a lot.", highlights: ["However,"] },
      { key: "Interrogativa de seguimiento", value: "¿Pregunta? Conector, ¿pregunta adicional? · Is the project feasible? Furthermore, is it profitable?", highlights: ["Furthermore,"] },
    ],
    contextExamples: [
      { key: "Presentación de negocios", value: "Inflation has risen sharply; therefore, central banks are raising interest rates." },
      { key: "Ensayo académico", value: "The initial experiment failed. However, subsequent trials yielded positive results." },
      { key: "Informe técnico", value: "The server hardware is outdated. Furthermore, the software requires urgent security patches." },
      { key: "Debate formal", value: "The candidate lacked executive experience. Nevertheless, she won the majority of votes." },
    ],
    contrastColumns: [
      { label: "However / Nevertheless (Contraste)", rule: "Conectan dos ideas opuestas u objetan la expectativa previa.", examples: ["The test was tough. However, everyone passed.", "It was late. Nevertheless, he kept working."] },
      { label: "Furthermore / Therefore (Adición y Resultado)", rule: "Furthermore agrega más información; Therefore expresa la consecuencia directa.", examples: ["She is smart. Furthermore, she is diligent.", "He lied; therefore, nobody trusts him."] },
    ],
    quickReferenceRows: [
      { key: "Coma obligatoria", value: "Coloca siempre una coma inmediatamente después del conector al iniciar oración." },
      { key: "Punto y coma opcional", value: "Puedes usar ';' antes del conector si unes dos cláusulas independientes relacionadas." },
      { key: "Evita 'however but'", value: "Nunca combines 'however' y 'but' en la misma cláusula." },
      { key: "Registro formal", value: "Usa estos conectores en informes, correos profesionales y ensayos, no en chats casuales." },
    ],
    mistake: { bad: "The weather was bad, however we went to the beach.", good: "The weather was bad. However, we went to the beach.", note: "'however' no une dos oraciones simples con una sola coma; requiere punto (.) o punto y coma (;) seguido de coma" },
    quiz: [
      { q: "The company lost money this quarter. ___, they decided to freeze all hiring.", options: ["Therefore", "However", "Although"], answer: 0, explain: "Se expresa la consecuencia lógica de perder dinero (freeze hiring) mediante 'Therefore'." },
      { q: "The project was extremely challenging. ___, the team delivered it on schedule.", options: ["Nevertheless", "Furthermore", "Because"], answer: 0, explain: "'Nevertheless' expresa concesión o contraste ('a pesar de ello') frente al desafío del proyecto." },
      { q: "The new laptop is lightweight and durable. ___, its battery life exceeds 15 hours.", options: ["Furthermore", "However", "Unless"], answer: 0, explain: "'Furthermore' añade un beneficio o argumento adicional del mismo signo positivo." },
    ],
  },
  {
    slug: "b2-oraciones-hendidas",
    eyebrow: "B2 · Énfasis",
    title: "Oraciones",
    emphasis: "hendidas",
    goal: "Ya destacas información con it-cleft y what-cleft.",
    conceptRows: [
      { key: "It-cleft (Enfoque en sujeto/objeto)", value: "It + be + elemento enfatizado + that/who · It was Sarah who solved the issue.", highlights: ["It was", "who"] },
      { key: "What-cleft (Enfoque en acción/hecho)", value: "What + cláusula + be + elemento clave · What we need is more time.", highlights: ["What", "is"] },
      { key: "All-cleft (Enfoque exclusivo)", value: "All + cláusula + be + elemento · All I want is a clear explanation.", highlights: ["All", "is"] },
      { key: "Wh-cleft de lugar/tiempo", value: "Where/When + cláusula + be + complemento · Where he lives is in central London.", highlights: ["Where", "is"] },
    ],
    structureRows: [
      { key: "Afirmativa (It-cleft)", value: "It + is/was + sustantivo/persona + relative clause · It is quality that matters most.", highlights: ["It is", "that"] },
      { key: "Afirmativa (What-cleft)", value: "What + sujeto + verbo + is/was + sustantivo/infinitivo · What I enjoy is solving complex puzzles.", highlights: ["What", "is"] },
      { key: "Negativa (It-cleft)", value: "It wasn't + persona/cosa + that/who... · It wasn't Mark who made the mistake.", highlights: ["It wasn't", "who"] },
      { key: "Interrogativa (It-cleft)", value: "Was it + persona/cosa + that/who...? · Was it yesterday that the parcel arrived?", highlights: ["Was it", "that"] },
    ],
    contextExamples: [
      { key: "Resolviendo un malentendido", value: "It was David, not me, who sent the email with the wrong attachments." },
      { key: "En el trabajo", value: "What we really need to focus on right now is improving customer retention." },
      { key: "Conversación cotidiana", value: "All I am asking for is ten minutes of your undivided attention." },
      { key: "Reclamación de servicio", value: "It was the lack of communication that disappointed us the most." },
    ],
    contrastColumns: [
      { label: "Oración Estándar (Sin énfasis)", rule: "Orden neutro S+V+O sin estructura enfática especial.", examples: ["Sarah solved the problem yesterday.", "We need more time to finish."] },
      { label: "Oración Hendida / Cleft (Con énfasis)", rule: "Reorganiza la oración para poner el foco principal en un elemento clave.", examples: ["It was Sarah who solved the problem.", "What we need is more time."] },
    ],
    quickReferenceRows: [
      { key: "It-cleft usa 'that' o 'who'", value: "Usa 'who' para personas y 'that' para cosas, lugares o acciones." },
      { key: "What-cleft usa el verbo 'be'", value: "Asegúrate de que el verbo 'be' concuerde con la información enfatizada." },
      { key: "Uso de 'All'", value: "'All' equivale a 'the only thing' (All I need is rest = La única cosa que necesito)." },
      { key: "No olvides la cláusula de relativo", value: "No puedes omitir 'who' o 'that' tras el elemento destacado en it-clefts." },
    ],
    mistake: { bad: "It was John called the manager.", good: "It was John who called the manager.", note: "las oraciones it-cleft requieren el pronombre relativo 'who' o 'that' para conectar la cláusula" },
    quiz: [
      { q: "It was in 2020 ___ we opened our first office in Madrid.", options: ["that", "which", "what"], answer: 0, explain: "En las it-clefts que enfatizan tiempo o lugar se utiliza la conjunción 'that'." },
      { q: "___ I appreciate most about this team is their dedication.", options: ["What", "Which", "That"], answer: 0, explain: "Las pseudo-clefts o what-clefts comienzan con el pronombre relativo 'What'." },
      { q: "All she wants to do this weekend ___ relax at home.", options: ["is", "are", "were"], answer: 0, explain: "La estructura 'All + cláusula singular' requiere la forma verbal 'is'." },
    ],
  },
  {
    slug: "b2-concesion",
    eyebrow: "B2 · Concesión",
    title: "Even though,",
    emphasis: "while y whereas",
    goal: "Ya contrastas ideas con even though, while y whereas.",
    conceptRows: [
      { key: "even though (concesión fuerte)", value: "Introduce un hecho real sorprendente o inesperado · Even though it rained, we enjoyed the walk.", highlights: ["Even though"] },
      { key: "while (contraste / concesión)", value: "Expresa 'si bien' o 'mientras que' · While I understand your view, I disagree.", highlights: ["While"] },
      { key: "whereas (contraste directo)", value: "Compara dos hechos o situaciones opuestas · Tom likes tea, whereas Anna prefers coffee.", highlights: ["whereas"] },
      { key: "Posición de cláusula", value: "Pueden ir al inicio (con coma en medio) o en la segunda mitad de la oración.", highlights: [","] },
    ],
    structureRows: [
      { key: "Afirmativa (Inicio)", value: "Even though / While / Whereas + S + V, S + V · Even though she was tired, she kept working.", highlights: ["Even though", ","] },
      { key: "Afirmativa (Medio)", value: "S + V + whereas / while + S + V · He earns a lot, whereas his brother saves little.", highlights: ["whereas"] },
      { key: "Negativa", value: "Even though + S + didn't + V, S + V · Even though we didn't win, we were proud.", highlights: ["Even though"] },
      { key: "Interrogativa", value: "Do you prefer X, whereas others prefer Y? · Why do you stay here while others leave?", highlights: ["while"] },
    ],
    contextExamples: [
      { key: "Comparación comercial", value: "Our product is handcrafted, whereas competitors rely entirely on mass automation." },
      { key: "Opinión profesional", value: "While the strategy carries some financial risk, the potential reward is immense." },
      { key: "Vida cotidiana", value: "Even though the flight was delayed by three hours, the passengers remained calm." },
      { key: "Hábitos familiares", value: "My sister loves living in big cities, whereas I prefer small coastal towns." },
    ],
    contrastColumns: [
      { label: "Even Though (Concesión / Hecho real)", rule: "Equivale a 'a pesar de que'; enfatiza un obstáculo superado.", examples: ["Even though he was injured, he played the final match."] },
      { label: "Whereas / While (Contraste formal)", rule: "Muestra la diferencia objetiva entre dos conceptos o sujetos distintos.", examples: ["Private cars pollute, whereas public transport reduces emissions."] },
    ],
    quickReferenceRows: [
      { key: "No uses 'but' con Even though", value: "Nunca pongas 'but' en la segunda cláusula si ya empezaste con 'Even though'." },
      { key: "Whereas compara dos cosas", value: "Usa 'whereas' para contraponer dos datos o perfiles (X es así, mientras que Y es asá)." },
      { key: "While puede ser temporal o concesivo", value: "En nivel B2, 'while' se usa frecuentemente como 'si bien' o 'aunque'." },
      { key: "Uso de comas", value: "Si la cláusula con 'Even though/While' va primero, separa con coma la oración principal." },
    ],
    mistake: { bad: "Even though it was freezing cold, but we went swimming.", good: "Even though it was freezing cold, we went swimming.", note: "no dupliques conectores adversativos; usa 'Even though' al inicio o 'but' en el medio, jamás ambos" },
    quiz: [
      { q: "___ my sister loves travelling abroad, I prefer spending holidays at home.", options: ["While", "Despite", "Because"], answer: 0, explain: "'While' funciona aquí como conector de contraste ('si bien / mientras que') entre dos preferencias." },
      { q: "Electric cars produce zero emissions, ___ petrol cars contribute to air pollution.", options: ["whereas", "unless", "in order to"], answer: 0, explain: "'Whereas' establece una comparación y contraste directo entre dos elementos." },
      { q: "___ he had little experience, he performed exceptionally well during his trial week.", options: ["Even though", "Despite of", "However"], answer: 0, explain: "'Even though' introduce una cláusula completa con sujeto y verbo para indicar concesión." },
    ],
  },
  {
    slug: "b2-conectores-condicionales",
    eyebrow: "B2 · Condicionales",
    title: "Unless, provided",
    emphasis: "y as long as",
    goal: "Ya matizas condiciones con unless, provided (that) y as long as.",
    conceptRows: [
      { key: "unless (condición negativa)", value: "Equivale a 'if not' (a menos que) · Unless you study, you won't pass.", highlights: ["Unless"] },
      { key: "provided (that) (requisito formal)", value: "Establece una condición o garantía previa · Provided that you pay, you can stay.", highlights: ["Provided that"] },
      { key: "as long as (duración / permiso)", value: "Significa 'con tal de que' o 'mientras' · You can stay as long as you are quiet.", highlights: ["as long as"] },
      { key: "in case (precaución)", value: "Expresa preparación 'por si acaso' · Take an umbrella in case it rains.", highlights: ["in case"] },
    ],
    structureRows: [
      { key: "Afirmativa (Unless)", value: "Unless + sujeto + verbo afirmativo en presente, sujeto + won't... · Unless it stops raining, we won't leave.", highlights: ["Unless", "won't"] },
      { key: "Afirmativa (As long as / Provided)", value: "Sujeto + will... + as long as / provided + sujeto + presente · You will succeed as long as you work hard.", highlights: ["as long as"] },
      { key: "Negativa", value: "Sujeto + won't... + provided + sujeto + doesn't... · We won't launch provided tests don't fail.", highlights: ["provided"] },
      { key: "Interrogativa", value: "Can we go provided that we finish early? · Will you come unless it rains?", highlights: ["provided that"] },
    ],
    contextExamples: [
      { key: "Acuerdo contractual", value: "The contract will be signed provided that all legal terms are met by Friday." },
      { key: "Norma de convivencia", value: "You are welcome to borrow my bicycle as long as you return it in good condition." },
      { key: "Advertencia laboral", value: "Unless we increase our quarterly revenue, the project will be cancelled." },
      { key: "Planes de viaje", value: "I will pack extra bottles of water in case we get stuck in traffic." },
    ],
    contrastColumns: [
      { label: "Unless (A menos que = If not)", rule: "La condición exige que NO ocurra algo para obtener un resultado.", examples: ["I won't call you unless there is a major problem."] },
      { label: "Provided / As long as (Con tal de que)", rule: "El resultado ocurre SIEMPRE QUE se cumpla la condición positiva planteada.", examples: ["I will call you provided that I get news."] },
    ],
    quickReferenceRows: [
      { key: "No uses verbo negativo tras 'unless'", value: "'Unless' ya es negativo por sí mismo (say 'Unless you ask', not 'Unless you don't ask')." },
      { key: "Sin 'will' en la condición", value: "Tras unless, provided that o as long as usa presente simple para hablar del futuro." },
      { key: "Diferencia 'in case' vs 'if'", value: "'In case' es prevención antes del evento; 'if' es respuesta tras el evento." },
      { key: "'That' es opcional", value: "Puedes decir 'provided that' o simplemente 'provided'." },
    ],
    mistake: { bad: "Unless you don't hurry, we will miss the train.", good: "Unless you hurry, we will miss the train.", note: "'unless' significa 'if not', por lo que la cláusula posterior debe llevar el verbo en afirmativo" },
    quiz: [
      { q: "You can stay at our house ___ you help with the housework.", options: ["as long as", "unless", "in case"], answer: 0, explain: "'As long as' expresa una condición positiva ('con tal de que / mientras')." },
      { q: "We will proceed with the outdoor concert ___ it starts pouring with rain.", options: ["unless", "provided that", "so that"], answer: 0, explain: "'Unless' significa 'a menos que' (salvo que comience a llover a cántaros)." },
      { q: "Take some extra cash with you ___ the card payment machine is out of order.", options: ["in case", "unless", "provided"], answer: 0, explain: "'In case' indica una medida de precaución ante una posibilidad futura." },
    ],
  },
  {
    slug: "b2-enfasis-auxiliares",
    eyebrow: "B2 · Énfasis",
    title: "Do/does/did",
    emphasis: "de énfasis",
    goal: "Ya enfatizas con auxiliares do/does/did en afirmaciones.",
    conceptRows: [
      { key: "do (énfasis presente plural/I/you)", value: "Destaca la veracidad de la acción · I do want to visit Japan.", highlights: ["do want"] },
      { key: "does (énfasis presente 3ª persona)", value: "Enfatiza el hecho en 3ª persona · She does speak English fluently.", highlights: ["does speak"] },
      { key: "did (énfasis pasado)", value: "Reafirma una acción pasada cuestionada · I did send the report yesterday!", highlights: ["did send"] },
      { key: "Contraste y corrección", value: "Corrige una suposición falsa · You think I don't care, but I do care.", highlights: ["do care"] },
    ],
    structureRows: [
      { key: "Afirmativa con do/does", value: "Sujeto + do/does + verbo base (sin -s) · He does like seafood, despite what he said.", highlights: ["does like"] },
      { key: "Afirmativa con did", value: "Sujeto + did + verbo base (forma infinitiva) · We did meet them at the conference.", highlights: ["did meet"] },
      { key: "Contraste concesivo", value: "Although + S + V, S + do/does/did + V base · Although tired, I do want to continue.", highlights: ["do want"] },
      { key: "Imperativo enfático", value: "Do + verbo base! (invitación/orden cálida) · Do sit down and make yourself at home!", highlights: ["Do sit"] },
    ],
    contextExamples: [
      { key: "Defendiendo una postura", value: "I know you think I forgot your birthday, but I did buy you a gift!" },
      { key: "Hospitalidad", value: "Please do call me if you experience any difficulties during your stay." },
      { key: "Confirmando información", value: "Although she rarely speaks in meetings, she does have brilliant ideas." },
      { key: "Superando dudas", value: "Many doubted our team, but we did manage to complete the project on time." },
    ],
    contrastColumns: [
      { label: "Oración Afirmativa Estándar", rule: "Declaración neutra sin acento tonal especial en el auxiliar.", examples: ["I like your new apartment.", "He called you yesterday."] },
      { label: "Oración con Auxiliar Enfático", rule: "Usa do/does/did recargado para reafirmar la verdad frente a una duda o negación previa.", examples: ["I DO like your new apartment!", "He DID call you yesterday!"] },
    ],
    quickReferenceRows: [
      { key: "Verbo principal en forma base", value: "Tras do/does/did el verbo principal NUNCA lleva -s ni -ed (She does know, He did call)." },
      { key: "Acento prosódico", value: "En el habla hablada, el estrés de la voz recae sobre el propio auxiliar (do/does/did)." },
      { key: "Imperativos amables", value: "Usar 'Do' antes de un imperativo le da un tono de cortesía entusiasta (Do come in!)." },
      { key: "Uso con 'Although'", value: "Combina muy bien para matizar: 'Although expensive, it does work well'." },
    ],
    mistake: { bad: "She does works very hard every day.", good: "She does work very hard every day.", note: "cuando se usa el auxiliar enfático 'does', el verbo principal vuelve a su forma base infinitiva sin '-s'" },
    quiz: [
      { q: "Why did you say I didn't lock the door? I ___ lock it!", options: ["did", "do", "have"], answer: 0, explain: "Para reafirmar con énfasis una acción en el pasado cuestionada se utiliza 'did'." },
      { q: "Although he doesn't talk much, he ___ care deeply about his work.", options: ["does", "is", "do"], answer: 0, explain: "Tercera persona del singular en presente con énfasis → 'does + verbo base'." },
      { q: "Please ___ try some of this homemade cake; it is delicious!", options: ["do", "does", "did"], answer: 0, explain: "El auxiliar 'Do' antes de un verbo imperativo añade una invitación entusiasta y cortés." },
    ],
  },
  {
    slug: "b2-gerundio-significado",
    eyebrow: "B2 · Gerundio vs infinitivo",
    title: "Cambio de",
    emphasis: "significado",
    goal: "Ya distingues remember/stop/try con -ing o to según el significado.",
    conceptRows: [
      { key: "stop + -ing vs stop + to", value: "stop smoking (interrumpir hábito) vs stop to smoke (pausar para fumar)", highlights: ["stop smoking", "stop to smoke"] },
      { key: "remember + -ing vs to", value: "remember doing (recuerdas el pasado) vs remember to do (recordar tarea futura)", highlights: ["remember doing", "remember to do"] },
      { key: "try + -ing vs try + to", value: "try changing (experimentar método) vs try to lift (hacer un esfuerzo físico)", highlights: ["try changing", "try to lift"] },
      { key: "regret + -ing vs to", value: "regret saying (arrepentirse de algo dicho) vs regret to inform (lamentar dar una noticia)", highlights: ["regret saying", "regret to inform"] },
    ],
    structureRows: [
      { key: "Patrón -ing (Memoria/Hábito/Experimento)", value: "Sujeto + verbo + verbo-ing + objeto · I remember visiting Rome in 2018.", highlights: ["remember visiting"] },
      { key: "Patrón to + Infinitivo (Propósito/Obligación/Esfuerzo)", value: "Sujeto + verbo + to + infinitivo + objeto · He stopped to buy a coffee.", highlights: ["stopped to buy"] },
      { key: "Negativa con -ing", value: "Sujeto + verbo + not + verbo-ing · I regret not studying harder for the test.", highlights: ["regret not studying"] },
      { key: "Interrogativa", value: "Did you remember to send the email? · Have you tried restarting the computer?", highlights: ["remember to send"] },
    ],
    contextExamples: [
      { key: "En el trabajo", value: "We regret to inform you that your application was not successful on this occasion." },
      { key: "Soporte técnico", value: "If the screen stays black, try unplugging the cable and plugging it in again." },
      { key: "Salud y hábitos", value: "My doctor advised me to stop working so late at night." },
      { key: "Memoria personal", value: "I clearly remember locking the front door before we left this morning." },
    ],
    contrastColumns: [
      { label: "Verbo + -ing (Acción previa / Experimento)", rule: "La acción del verbo secundario ocurre ANTES o como experimento en sí.", examples: ["I remember posting the letter. (Recuerdo haberlo hecho)", "Try adding more salt. (Prueba a ver qué pasa)"] },
      { label: "Verbo + to + Infinitivo (Objetivo / Tarea futura)", rule: "La acción del verbo secundario es el OBJETIVO o la obligación por realizar.", examples: ["Remember to post the letter! (No olvides hacerlo)", "Try to open the heavy door. (Haz el esfuerzo)"] },
    ],
    quickReferenceRows: [
      { key: "Remember to = Tarea pendiente", value: "Usar 'to' significa recordar que debes hacer algo antes de ejecutarlo." },
      { key: "Remember -ing = Recuerdo pasado", value: "Usar '-ing' significa evocar en tu memoria una vivencia ya ocurrida." },
      { key: "Stop -ing = Abandono definitivo", value: "Significa cesar una actividad por completo (I stopped eating sugar)." },
      { key: "Regret to inform = Noticia formal", value: "Fórmula estándar en cartas formales para comunicar noticias desfavorables." },
    ],
    mistake: { bad: "I stopped to smoke three years ago and now I feel great.", good: "I stopped smoking three years ago and now I feel great.", note: "'stop to smoke' significa parar para encender un cigarrillo; para abandonar el hábito se usa 'stop smoking'" },
    quiz: [
      { q: "Please remember ___ off the lights before leaving the lecture hall.", options: ["to turn", "turning", "turn"], answer: 0, explain: "Se trata de una obligación o tarea por cumplir en el futuro → 'remember + to + infinitivo'." },
      { q: "I will never forget ___ the Eiffel Tower for the very first time.", options: ["seeing", "to see", "see"], answer: 0, explain: "Evocar el recuerdo de una experiencia del pasado requiere la forma en gerundio ('-ing')." },
      { q: "He tried ___ the heavy box, but it was far too heavy for one person.", options: ["to lift", "lifting", "lifted"], answer: 0, explain: "'Try + to + infinitivo' expresa hacer el esfuerzo físico de lograr un objetivo difícil." },
    ],
  },
  {
    slug: "b2-condicionales-mixtos",
    eyebrow: "B2 · Condicionales",
    title: "Condicionales",
    emphasis: "mixtos",
    goal: "Ya combinas tiempos en condicionales mixtos (pasado → presente, etc.).",
    conceptRows: [
      { key: "Tipo A: Causa pasada → Efecto presente", value: "If + past perfect, would + verbo base · If I had studied medicine, I would be a doctor today.", highlights: ["had studied", "would be"] },
      { key: "Tipo B: Causa presente → Efecto pasado", value: "If + past simple, would have + participio · If I were braver, I would have accepted the offer.", highlights: ["were", "would have accepted"] },
      { key: "Marcadores temporales claros", value: "Uso de 'now', 'today', 'at the time' para indicar el tiempo de cada cláusula.", highlights: ["today", "now"] },
      { key: "Variación de modales", value: "Se puede usar could / might en lugar de would para indicar posibilidad.", highlights: ["might be"] },
    ],
    structureRows: [
      { key: "Afirmativa (Pasado → Presente)", value: "If + sujet + had + V3, sujet + would + V base + now · If she had saved money, she would own a house now.", highlights: ["had saved", "would own"] },
      { key: "Afirmativa (Presente → Pasado)", value: "If + sujet + past simple, sujet + would have + V3 · If I spoke French, I would have translated it.", highlights: ["spoke", "would have translated"] },
      { key: "Negativa", value: "If I hadn't missed the train, I wouldn't be stuck here now. · Past perfect neg + would neg", highlights: ["hadn't missed", "wouldn't be"] },
      { key: "Interrogativa", value: "Would you be happier now if you had taken that job? · Would + S + V base if + had + V3?", highlights: ["Would you be", "had taken"] },
    ],
    contextExamples: [
      { key: "Decisiones de carrera", value: "If I had accepted the promotion in London, I would be living there right now." },
      { key: "Rasgos de personalidad", value: "If Peter weren't so indecisive, he would have bought that property last week." },
      { key: "Consecuencias presentes", value: "If we hadn't lost our passports, we wouldn't be waiting at the embassy today." },
      { key: "Reflexión de vida", value: "If I had learned to code at school, I would have a much higher salary now." },
    ],
    contrastColumns: [
      { label: "Tercer Condicional Puro (Pasado → Pasado)", rule: "Tanto la hipótesis como el resultado imaginario pertenecen 100% al pasado.", examples: ["If I had studied, I would have passed the exam last year."] },
      { label: "Condicional Mixto (Pasado → Presente)", rule: "La causa hipotética ocurrió en el pasado, pero su efecto afecta la realidad presente.", examples: ["If I had studied, I would have a degree now."] },
    ],
    quickReferenceRows: [
      { key: "Mezcla de tiempos deliberada", value: "No es un error gramatical; se combinan tiempos para reflejar la realidad temporal de la frase." },
      { key: "'If I were' para estados permanentes", value: "Si la condición es un rasgo continuo del presente, usa pasado simple en la cláusula con 'if'." },
      { key: "Atención a 'now' y 'today'", value: "Estas palabras en la cláusula principal suelen indicar el uso de 'would + verbo base'." },
      { key: "'Could have' o 'Might have'", value: "Sustituyen a 'would have' para expresar capacidad o posibilidad reducida en el pasado." },
    ],
    mistake: { bad: "If I had win the lottery last year, I would buy a yacht today.", good: "If I had won the lottery last year, I would buy a yacht today.", note: "la cláusula de condición pasada requiere 'had + participio pasado' (had won)" },
    quiz: [
      { q: "If I ___ my keys yesterday, I wouldn't be locked out of my apartment right now.", options: ["hadn't lost", "didn't lose", "don't lose"], answer: 0, explain: "Causa pasada hipotética (perder las llaves ayer) → past perfect negative ('hadn't lost')." },
      { q: "If Sarah were more organized, she ___ her presentation on time last night.", options: ["would have finished", "would finish", "will finish"], answer: 0, explain: "Condición presente/habitual (ser organizada) con resultado pasado (terminar anoche) → 'would have + V3'." },
      { q: "If we had taken the map with us, we ___ lost in the forest right now.", options: ["wouldn't be", "wouldn't have been", "won't be"], answer: 0, explain: "La consecuencia actual ('right now') de una acción pasada requiere 'wouldn't be + adjetivo'." },
    ],
  },
  {
    slug: "b2-relativas-no-definitorias",
    eyebrow: "B2 · Relativas",
    title: "Cláusulas",
    emphasis: "explicativas",
    goal: "Ya usas oraciones de relativo no definitorias con comas y who/which.",
    conceptRows: [
      { key: "Separadas por comas", value: "Añaden detalles prescindibles · My boss, who is 45, loves marathon running.", highlights: [",", "who", ","] },
      { key: "uso de 'which' para oraciones", value: "which modifica toda la idea anterior · He arrived late, which annoyed everyone.", highlights: [", which"] },
      { key: "whose para posesión", value: "whose indica pertenencia en cláusula extra · Dr. Evans, whose son is a doctor, retired.", highlights: ["whose"] },
      { key: "Prohibición de 'that'", value: "NUNCA se utiliza 'that' entre comas en oraciones no definitorias.", highlights: ["who", "which"] },
    ],
    structureRows: [
      { key: "Afirmativa (Persona entre comas)", value: "Sujeto, who + verbo + complemento, verbo principal + complemento · Mary, who works with me, got promoted.", highlights: [", who", ","] },
      { key: "Afirmativa (Cosa/Lugar entre comas)", value: "Sujeto, which/where + verbo, verbo principal... · Tokyo, where I lived, is fascinating.", highlights: [", where", ","] },
      { key: "Negativa dentro de la relativa", value: "Sujeto, who didn't attend the meeting, was informed later. · relative neg", highlights: [", who didn't", ","] },
      { key: "Cláusula al final de la oración", value: "Oración principal, relative clause. · She showed me her new house, which was built in 1920.", highlights: [", which was"] },
    ],
    contextExamples: [
      { key: "Presentación de colegas", value: "Professor Miller, who has published several books on linguistics, will deliver the keynote speech." },
      { key: "Descripción de viajes", value: "We visited Barcelona, which is famous for its stunning modernist architecture." },
      { key: "Comentario sobre eventos", value: "The company doubled its profits this quarter, which was a surprise to all investors." },
      { key: "Contexto familiar", value: "My uncle, whose car was stolen last week, had to buy a new one." },
    ],
    contrastColumns: [
      { label: "Relativa Definitoria (Sin comas)", rule: "Información ESENCIAL para identificar de qué persona o cosa se habla; admite 'that'.", examples: ["The doctor who treated me was very kind.", "The car that I bought is blue."] },
      { label: "Relativa No Definitoria (Entre comas)", rule: "Información ADICIONAL que se puede eliminar sin cambiar el sentido principal; PROHÍBE 'that'.", examples: ["Dr. Smith, who is a surgeon, was very kind.", "My car, which is blue, is fast."] },
    ],
    quickReferenceRows: [
      { key: "Las comas son obligatorias", value: "Si la cláusula se puede eliminar sin romper el sentido, pon comas al inicio y final." },
      { key: "'That' está totalmente prohibido", value: "Nunca uses 'that' tras una coma en inglés (say 'Paris, which...', not 'Paris, that...')." },
      { key: "'Which' refiere a toda la oración", value: "Usa ', which' al final para dar tu opinión sobre todo el hecho anterior." },
      { key: "'Whose' no lleva apóstrofe", value: "'whose' indica posesión de una persona u objeto (whose roof, whose son)." },
    ],
    mistake: { bad: "My elder brother, that lives in Sydney, is coming to visit.", good: "My elder brother, who lives in Sydney, is coming to visit.", note: "en las oraciones relativas explicativas (no definitorias entre comas) jamás debe utilizarse 'that', sino 'who' o 'which'" },
    quiz: [
      { q: "The new shopping mall, ___ opened last month, features over 200 luxury stores.", options: ["which", "that", "where"], answer: 0, explain: "Cláusula explicativa sobre una cosa entre comas → se debe utilizar el pronombre 'which'." },
      { q: "My colleague Julia, ___ husband is a pilot, travels around the world frequently.", options: ["whose", "who", "whom"], answer: 0, explain: "Para indicar una relación de posesión ('cuyo marido') se utiliza el pronombre relativo 'whose'." },
      { q: "He passed all his final examinations with honors, ___ made his parents immensely proud.", options: ["which", "what", "that"], answer: 0, explain: "', which' se utiliza para hacer referencia y comentar la totalidad de la proposición anterior." },
    ],
  },
  {
    slug: "b2-pasiva-reportada",
    eyebrow: "B2 · Pasiva",
    title: "Reportaje",
    emphasis: "pasivo",
    goal: "Ya reportas con It is said that… y subject + is said to + infinitivo.",
    conceptRows: [
      { key: "It + pasiva + that", value: "It is reported that the company is expanding. · Estructura impersonal", highlights: ["It is reported that"] },
      { key: "Sujeto + pasiva + to + infinitivo", value: "The CEO is expected to resign tomorrow. · Enfoque en el sujeto", highlights: ["is expected to"] },
      { key: "Pasado de la pasiva reportada", value: "He is believed to have left the country. · to have + participio", highlights: ["is believed to have"] },
      { key: "Verbos de reporte comunes", value: "say, believe, think, report, claim, consider, expect, rumor", highlights: ["is said", "is believed"] },
    ],
    structureRows: [
      { key: "Estructura 1 (Impersonal)", value: "It + is/was + participio + that + oración · It is thought that the economy will recover.", highlights: ["It is thought that"] },
      { key: "Estructura 2 (Sujeto + Presente)", value: "Sujeto + is/are + participio + to + infinitivo base · The painting is said to be authentic.", highlights: ["is said to be"] },
      { key: "Estructura 3 (Sujeto + Pasado previo)", value: "Sujeto + is/are + participio + to have + V3 · The suspect is reported to have escaped.", highlights: ["is reported to have"] },
      { key: "Negativa", value: "It is not expected that prices will fall. / He is not thought to be involved.", highlights: ["is not thought to"] },
    ],
    contextExamples: [
      { key: "Noticias de prensa", value: "It is estimated that over ten thousand people attended the demonstration in Berlin." },
      { key: "Historia y arqueología", value: "The ancient fortress is believed to have been constructed during the 14th century." },
      { key: "Informes corporativos", value: "The tech giant is rumored to be developing a revolutionary artificial intelligence chip." },
      { key: "Comunicado oficial", value: "The government minister is expected to deliver a public address later this evening." },
    ],
    contrastColumns: [
      { label: "Voz Activa (Sujeto activo impreciso)", rule: "Menciona a la gente o fuentes generales como sujeto de la oración.", examples: ["People say that he earns millions.", "Journalists report that the fire started at midnight."] },
      { label: "Pasiva Reportada (Periodística / Formal)", rule: "Elimina el sujeto difuso y le da tono objetivo y periodístico al enunciado.", examples: ["He is said to earn millions.", "The fire is reported to have started at midnight."] },
    ],
    quickReferenceRows: [
      { key: "'It is said that...' no cambia el verbo", value: "La oración tras 'that' mantiene su estructura y tiempo normal." },
      { key: "'Subject + is said to...' usa infinitivo", value: "Usa 'to be' para estados presentes y 'to have been' para eventos pasados." },
      { key: "Ideal para textos formales", value: "Es la estructura preferida en noticias, investigación y redacción académica." },
      { key: "Concordancia de sujeto", value: "Asegúrate de cambiar 'is' por 'are' si el sujeto es plural (They are said to be...)." },
    ],
    mistake: { bad: "People is said that the castle is haunted.", good: "It is said that the castle is haunted. / The castle is said to be haunted.", note: "no mezcles la pasiva reportada con 'People'; usa la forma impersonal 'It is said that' o el sujeto 'The castle is said to'" },
    quiz: [
      { q: "The missing painting ___ to have been destroyed during the war.", options: ["is believed", "believes", "is believing"], answer: 0, explain: "Estructura pasiva de reporte con sujeto de enfoque: 'Sujeto + is believed + to have + V3'." },
      { q: "___ is reported that negotiators have reached a preliminary peace agreement.", options: ["It", "There", "What"], answer: 0, explain: "La estructura impersonal de reporte comienza con el pronombre neutro 'It' ('It is reported that...')." },
      { q: "The company's CEO is expected ___ his resignation later today.", options: ["to announce", "announcing", "announce"], answer: 0, explain: "Tras 'is expected' se requiere el infinitivo con 'to' ('to announce')." },
    ],
  },
  {
    slug: "b2-pasiva-completa",
    eyebrow: "B2 · Pasiva",
    title: "Pasiva en",
    emphasis: "todos los tiempos",
    goal: "Ya formas la voz pasiva en todos los tiempos verbales comunes.",
    conceptRows: [
      { key: "Presente/Pasado Continuo Pasivo", value: "is/was being + V3 · The road is being repaired.", highlights: ["is being repaired"] },
      { key: "Presente/Pasado Perfecto Pasivo", value: "has/had been + V3 · The decision has been made.", highlights: ["has been made"] },
      { key: "Futuro Pasivo", value: "will be + V3 / is going to be + V3 · The results will be published tomorrow.", highlights: ["will be published"] },
      { key: "Modales Pasivos", value: "can/must/should be + V3 · Safety rules must be followed.", highlights: ["must be followed"] },
    ],
    structureRows: [
      { key: "Afirmativa (Continuo)", value: "Sujeto + am/is/are/was/were + being + participio · A new stadium is being built in the city.", highlights: ["is being built"] },
      { key: "Afirmativa (Perfecto)", value: "Sujeto + has/have/had + been + participio · All tickets have already been sold.", highlights: ["have been sold"] },
      { key: "Negativa (Modales)", value: "Sujeto + modal + not + be + participio · The confidential files must not be shared.", highlights: ["must not be shared"] },
      { key: "Interrogativa", value: "Has the project been approved by the board yet? · Has + S + been + V3?", highlights: ["Has", "been approved"] },
    ],
    contextExamples: [
      { key: "Noticias de infraestructura", value: "A modern hospital is currently being constructed near the main railway station." },
      { key: "Gestión de proyectos", value: "All required documents have been reviewed and signed by our legal counsel." },
      { key: "Instrucciones de seguridad", value: "Emergency exits must be kept clear of any obstacles at all times." },
      { key: "Eventos corporativos", value: "The annual conference will be hosted in Paris next November." },
    ],
    contrastColumns: [
      { label: "Voz Activa (Foco en el agente)", rule: "El sujeto realiza la acción expresada por el verbo principal.", examples: ["Engineers are testing the software.", "They have delivered the package."] },
      { label: "Voz Pasiva (Foco en la acción / objeto)", rule: "El sujeto recibe la acción; el agente es secundario u omitido.", examples: ["The software is being tested.", "The package has been delivered."] },
    ],
    quickReferenceRows: [
      { key: "La fórmula sagrada: BE + V3", value: "Cualquier tiempo pasivo se forma cambiando el verbo 'be' al tiempo correspondiente seguido de V3." },
      { key: "'Being' para tiempos continuos", value: "En presente o pasado continuo pasivo NUNCA olvides 'being' (is being built)." },
      { key: "'Been' para tiempos perfectos", value: "En presente o pasado perfecto pasivo NUNCA olvides 'been' (has been finished)." },
      { key: "Agente con 'by'", value: "Añade 'by + persona/agente' solo si la información sobre quién lo hizo es relevante." },
    ],
    mistake: { bad: "The new bridge was build in less than six months.", good: "The new bridge was built in less than six months.", note: "la voz pasiva siempre exige el participio pasado del verbo principal (built), no el presente ni el infinitivo" },
    quiz: [
      { q: "The stolen jewels ___ by the local police in an abandoned warehouse.", options: ["have been recovered", "have recovered", "were recovering"], answer: 0, explain: "Acción pasiva completada con relevancia presente → presente perfecto pasivo ('have been recovered')." },
      { q: "Don't enter that room right now; it ___ painted by the decorators.", options: ["is being", "is", "has"], answer: 0, explain: "Acción pasiva que ocurre progresivamente en este instante → presente continuo pasivo ('is being')." },
      { q: "All applications must ___ before the midnight deadline.", options: ["be submitted", "submit", "been submitted"], answer: 0, explain: "Voz pasiva con verbo modal → 'modal + be + participio pasado' ('must be submitted')." },
    ],
  },
  {
    slug: "b2-relativas-preposiciones",
    eyebrow: "B2 · Relativas",
    title: "Relativas con",
    emphasis: "preposiciones",
    goal: "Ya colocas preposiciones al final o antes del relativo en estilo formal.",
    conceptRows: [
      { key: "Preposición al final (Informal)", value: "The man I was talking to · posición natural conversacional", highlights: ["talking to"] },
      { key: "Preposición al inicio (Formal)", value: "The man to whom I was speaking · registro formal escrito", highlights: ["to whom"] },
      { key: "Cuantificador + of + whom/which", value: "I have three brothers, two of whom live in London.", highlights: ["two of whom"] },
      { key: "whose con preposición", value: "The author in whose books I am interested · pertenencia formal", highlights: ["in whose"] },
    ],
    structureRows: [
      { key: "Estilo Cotidiano (Preposición al final)", value: "Sujeto + (who/that/which) + S + V + preposición · The candidate (who) we voted for won.", highlights: ["voted for"] },
      { key: "Estilo Formal (Preposición al inicio)", value: "Sujeto + preposición + whom/which + S + V · The candidate for whom we voted won.", highlights: ["for whom"] },
      { key: "Cuantificadores en relativa", value: "Sujeto, cuantificador + of + whom/which + V · They interviewed ten applicants, three of whom were hired.", highlights: [", three of whom"] },
      { key: "Negativa en relativa", value: "There were several proposals, none of which were accepted. · quantifier neg", highlights: [", none of which"] },
    ],
    contextExamples: [
      { key: "Entorno académico", value: "The research field to which she dedicated her entire career has advanced rapidly." },
      { key: "Reunión de equipo", value: "We discussed several potential solutions, none of which proved to be cost-effective." },
      { key: "Redes profesionales", value: "She introduced me to her colleagues, most of whom had years of industry experience." },
      { key: "Trámites oficiales", value: "The company with which we signed the contract has offices across Europe." },
    ],
    contrastColumns: [
      { label: "Posición Informal / Hablada", rule: "La preposición queda atrapada al final de la cláusula; admite omitir el pronombre.", examples: ["That's the company I worked for.", "Who were you speaking to?"] },
      { label: "Posición Formal / Académica", rule: "La preposición encabeza la cláusula seguida imperativamente de 'whom' (personas) o 'which' (cosas).", examples: ["That is the company for which I worked.", "To whom were you speaking?"] },
    ],
    quickReferenceRows: [
      { key: "Preposición + WHOM para personas", value: "Tras una preposición NUNCA se usa 'who' ni 'that', solo 'whom' (with whom, about whom)." },
      { key: "Preposición + WHICH para cosas", value: "Usa 'which' para objetos o instituciones (in which, to which)." },
      { key: "Cuantificadores comunes", value: "some of whom, all of which, half of whom, neither of which." },
      { key: "Omitir el pronombre en uso informal", value: "En el habla cotidiana puedes omitir 'who/that' si la preposición va al final." },
    ],
    mistake: { bad: "The committee member to who I sent the file was absent.", good: "The committee member to whom I sent the file was absent. / The member who I sent the file to was absent.", note: "si la preposición precede directamente al pronombre relativo referido a personas, se debe usar 'whom', no 'who'" },
    quiz: [
      { q: "He manages a team of twelve engineers, all of ___ hold master's degrees.", options: ["whom", "who", "which"], answer: 0, explain: "Tras la preposición 'of' referida a personas en un cuantificador se utiliza obligatoriamente 'whom'." },
      { q: "The hotel at ___ we stayed during our trip to Florence was built in the 18th century.", options: ["which", "that", "where"], answer: 0, explain: "Tras una preposición directa referida a un edificio o cosa ('at...'), el pronombre adecuado es 'which'." },
      { q: "She had dozens of books on her shelves, many of ___ she had never actually read.", options: ["which", "whom", "that"], answer: 0, explain: "Cuantificador referido a objetos inanimados ('books') → 'many of which'." },
    ],
  },
  {
    slug: "b2-oraciones-resultado",
    eyebrow: "B2 · Resultado",
    title: "So/such",
    emphasis: "… that",
    goal: "Ya expresas resultado con so + adj/adv + that y such + (a) + sustantivo + that.",
    conceptRows: [
      { key: "so + adjetivo / adverbio + that", value: "The book was so good that I finished it in one day.", highlights: ["so good that"] },
      { key: "such + (a/an) + adjetivo + sustantivo + that", value: "It was such a good book that I recommended it.", highlights: ["such a good book that"] },
      { key: "so much / so many + sustantivo + that", value: "There were so many people that we couldn't enter.", highlights: ["so many", "that"] },
      { key: "Omitir 'that' en conversación", value: "The test was so hard I failed (that se puede omitir).", highlights: ["so hard"] },
    ],
    structureRows: [
      { key: "Afirmativa con SO", value: "Sujeto + verbo + so + adjetivo/adverbio + (that) + resultado · She ran so fast that she won.", highlights: ["so fast that"] },
      { key: "Afirmativa con SUCH (Singular contable)", value: "Sujeto + verbo + such a/an + adj + sustantivo singular + (that) + resultado · It was such a loud noise that I jumped.", highlights: ["such a loud noise that"] },
      { key: "Afirmativa con SUCH (Plural / Incontable)", value: "Sujeto + verbo + such + adj + sustantivo plural/incontable + (that) + resultado · They have such expensive cars that everyone looks.", highlights: ["such expensive cars"] },
      { key: "Negativa", value: "The weather wasn't so cold that we needed coats. / It wasn't such a bad day.", highlights: ["wasn't so cold that"] },
    ],
    contextExamples: [
      { key: "Experiencia de viaje", value: "The mountain view was so breath-taking that we took dozens of photographs." },
      { key: "Restaurante", value: "It was such a delicious meal that we decided to leave a generous tip for the waiter." },
      { key: "Cansancio", value: "I had so much work to complete yesterday that I didn't sleep until 2 am." },
      { key: "Clima extremo", value: "There was such heavy traffic on the motorway that we missed our flight connection." },
    ],
    contrastColumns: [
      { label: "SO (Modifica Adjetivos y Adverbios)", rule: "Se coloca directamente antes de un adjetivo o adverbio sin sustantivo posterior.", examples: ["The exam was so difficult that nobody passed.", "He spoke so quietly that I couldn't hear."] },
      { label: "SUCH (Modifica Sustantivos / Grupos Nominales)", rule: "Exige ir seguido de un grupo nominal (adjetivo + sustantivo).", examples: ["It was such a difficult exam that nobody passed."] },
    ],
    quickReferenceRows: [
      { key: "So + Adjetivo", value: "so tired, so bright, so quickly." },
      { key: "Such + (a/an) + Sustantivo", value: "such a mess, such a disaster, such nice people." },
      { key: "So much / So many", value: "Usa 'so much' para incontables (so much noise) y 'so many' para plurales (so many cars)." },
      { key: "'That' es opcional", value: "En el habla cotidiana informal se suele prescindir de la palabra 'that'." },
    ],
    mistake: { bad: "It was so a beautiful day that we went to the beach.", good: "It was such a beautiful day that we went to the beach. / The day was so beautiful that we went...", note: "no uses 'so' delante de 'a/an + adjetivo + sustantivo'; debes usar 'such a beautiful day'" },
    quiz: [
      { q: "The lecture was ___ boring that half of the audience fell asleep.", options: ["so", "such", "such a"], answer: 0, explain: "Delante de un adjetivo aislado ('boring') sin sustantivo posterior se debe usar 'so'." },
      { q: "It was ___ unexpected news that nobody knew how to react initially.", options: ["such", "so", "such an"], answer: 0, explain: "'News' es un sustantivo incontable, por lo que exige 'such' sin artículo indefinido." },
      { q: "He made ___ many spelling mistakes in his essay that he lost ten marks.", options: ["so", "such", "too"], answer: 0, explain: "Con los cuantificadores 'many' o 'much' se combina siempre 'so' ('so many... that')." },
    ],
  },
  {
    slug: "b2-verbo-objeto-gerundio",
    eyebrow: "B2 · Patrones verbales",
    title: "Verbo + objeto",
    emphasis: "+ -ing / to",
    goal: "Ya usas patrones como want someone to, catch someone -ing y persuade someone to.",
    conceptRows: [
      { key: "verbo + objeto + to + infinitivo", value: "want/allow/encourage/persuade + obj + to · She persuaded me to stay.", highlights: ["persuade me to"] },
      { key: "verbo + objeto + -ing", value: "catch/find/hear/see + obj + -ing · I caught him stealing cookies.", highlights: ["caught him stealing"] },
      { key: "Evita 'that' tras 'want/would like'", value: "I want you to help me (JAMÁS 'I want that you help me').", highlights: ["want you to"] },
      { key: "Verbos de percepción (Base vs -ing)", value: "saw her leave (acción completa) vs saw her leaving (acción en progreso)", highlights: ["saw her leave", "saw her leaving"] },
    ],
    structureRows: [
      { key: "Afirmativa (con TO)", value: "Sujeto + verbo + persona/objeto + to + infinitivo · My parents encouraged me to apply.", highlights: ["encouraged me to apply"] },
      { key: "Afirmativa (con -ING)", value: "Sujeto + verbo + persona/objeto + verbo-ing · The guard found them lurking nearby.", highlights: ["found them lurking"] },
      { key: "Negativa", value: "Sujeto + verbo + objeto + not + to + infinitivo · He warned us not to touch the wires.", highlights: ["warned us not to"] },
      { key: "Interrogativa", value: "Did you expect him to arrive so early? · Would you mind me sitting here?", highlights: ["expect him to"] },
    ],
    contextExamples: [
      { key: "En la oficina", value: "Our team manager encouraged us to take regular breaks during long shifts." },
      { key: "Testimonio policial", value: "The witness reported seeing the suspect running away from the scene of the crime." },
      { key: "Relaciones personales", value: "I finally managed to convince my brother to join the gym with me." },
      { key: "Seguridad e higiene", value: "The signs strictly forbid visitors from feeding the animals in the park." },
    ],
    contrastColumns: [
      { label: "Verbos de Persuasión / Orden (+ objeto + to)", rule: "Indican influencia sobre otra persona para ejecutar un propósito (want, allow, advise, tell, ask, persuade).", examples: ["She asked me to open the window.", "I expect you to be punctual."] },
      { label: "Verbos de Percepción / Hallazgo (+ objeto + -ing)", rule: "Indican observación directa de alguien realizando una acción en curso (see, hear, catch, find, notice).", examples: ["I saw him walking in the park.", "They caught her cheating on the exam."] },
    ],
    quickReferenceRows: [
      { key: "Cero 'that' con WANT", value: "Nunca digas 'I want that you go'; la forma correcta es 'I want you to go'." },
      { key: "Warn someone NOT to", value: "Para aconsejar que no hagan algo coloca 'not' antes de 'to' (warned us NOT to go)." },
      { key: "Catch someone -ING", value: "Significa descubrir a alguien haciendo algo indebido o sopresivo." },
      { key: "Diferencia de percepción", value: "I saw her dance (vi todo el baile) vs I saw her dancing (la vi en mitad del baile)." },
    ],
    mistake: { bad: "My teacher wants that I write a 500-word essay.", good: "My teacher wants me to write a 500-word essay.", note: "el verbo 'want' se construye con objeto + infinitivo con 'to', jamás con una cláusula introducida por 'that'" },
    quiz: [
      { q: "The security guard caught the teenager ___ graffiti on the wall.", options: ["painting", "to paint", "paint"], answer: 0, explain: "Descubrir a alguien en el acto de realizar una acción exige el patrón 'catch + objeto + -ing'." },
      { q: "Her mother advised her ___ that expensive second-hand car.", options: ["not to buy", "to not buy", "don't buy"], answer: 0, explain: "Negación con patrón de objeto + infinitivo: 'advise + objeto + not + to + infinitivo'." },
      { q: "I didn't expect them ___ so quickly after the long flight.", options: ["to arrive", "arriving", "that they arrive"], answer: 0, explain: "El verbo 'expect' exige la estructura 'expect + objeto + to + infinitivo'." },
    ],
  },
  {
    slug: "b2-despite-in-spite",
    eyebrow: "B2 · Concesión",
    title: "Despite /",
    emphasis: "in spite of",
    goal: "Ya contrastas con despite/in spite of + sustantivo o -ing (no cláusula con verbo conjugado).",
    conceptRows: [
      { key: "despite + sustantivo / -ing", value: "despite the rain / despite feeling ill · Sin 'of'", highlights: ["despite"] },
      { key: "in spite of + sustantivo / -ing", value: "in spite of the delay / in spite of working hard · Con 'of'", highlights: ["in spite of"] },
      { key: "despite the fact that + cláusula", value: "despite the fact that it rained · Permite oración con verbo conjugado", highlights: ["the fact that"] },
      { key: "although + oración completa", value: "although it was raining · Requiere sujeto y verbo conjugado", highlights: ["although"] },
    ],
    structureRows: [
      { key: "Afirmativa con Sustantivo", value: "Despite / In spite of + sustantivo, sujeto + verbo · Despite the heavy traffic, we arrived on time.", highlights: ["Despite the heavy traffic"] },
      { key: "Afirmativa con Gerundio", value: "Despite / In spite of + verbo-ing, sujeto + verbo · In spite of being tired, she finished the report.", highlights: ["In spite of being"] },
      { key: "Afirmativa con 'the fact that'", value: "Despite the fact that + sujeto + verbo, sujeto + verbo · Despite the fact that he lacked experience, he got the job.", highlights: ["Despite the fact that"] },
      { key: "Negativa con gerundio", value: "Despite not having a degree, he built a successful business. · despite not -ing", highlights: ["Despite not having"] },
    ],
    contextExamples: [
      { key: "Rendimiento deportivo", value: "In spite of playing with ten men for most of the game, the team won the final." },
      { key: "Éxito profesional", value: "He secured the investment despite facing severe criticism from industry experts." },
      { key: "Condiciones climáticas", value: "We had a wonderful weekend at the campsite in spite of the gloomy weather." },
      { key: "Decisiones de compra", value: "Despite the high price tag of the device, thousands of customers queued overnight." },
    ],
    contrastColumns: [
      { label: "Despite / In Spite Of (Preposiciones)", rule: "Van seguidas ÚNICAMENTE de un sustantivo, un pronombre (this/that) o un gerundio (-ing).", examples: ["Despite the rain, we left.", "In spite of being late, he smiled."] },
      { label: "Although / Even Though (Conjunciones)", rule: "Van seguidas obligatoriamente de una ORACIÓN COMPLETA (Sujeto + Verbo conjugado).", examples: ["Although it was raining, we left.", "Even though he was late, he smiled."] },
    ],
    quickReferenceRows: [
      { key: "DESPITE jamás lleva 'of'", value: "Es un error común decir 'despite of'; di siempre 'despite' a secas." },
      { key: "IN SPITE exige 'of'", value: "No omitas la preposición 'of' cuando uses 'in spite' (in spite OF the cold)." },
      { key: "Usa 'the fact that' para oraciones", value: "Si quieres poner sujeto y verbo después de 'despite', añade 'the fact that'." },
      { key: "Mismo significado", value: "Despite e In spite of son 100% intercambiables entre sí." },
    ],
    mistake: { bad: "Despite of the terrible weather, we went hiking.", good: "Despite the terrible weather, we went hiking. / In spite of the terrible weather...", note: "la palabra 'despite' nunca lleva la preposición 'of'; 'in spite of' sí requiere 'of'" },
    quiz: [
      { q: "___ having a sore throat, the singer gave a magnificent performance.", options: ["Despite", "Although", "Even though"], answer: 0, explain: "Tras el hueco hay un verbo en gerundio ('having'), por lo que corresponde la preposición 'Despite'." },
      { q: "We enjoyed our picnic in the park ___ the cold wind.", options: ["in spite of", "despite of", "although"], answer: 0, explain: "'In spite of' es la forma correcta con preposición 'of' seguida de un grupo nominal ('the cold wind')." },
      { q: "___ he studied diligently for weeks, he failed to score top marks.", options: ["Although", "Despite", "In spite of"], answer: 0, explain: "Tras el hueco hay una oración completa con sujeto y verbo ('he studied'), exigiendo 'Although'." },
    ],
  },
];

