export type DeckSpec = {
  slug: string;
  eyebrow: string;
  title: string;
  emphasis?: string;
  goal: string;
  conceptRows: Array<{ key: string; value: string; highlights?: string[] }>;
  mistake: { bad: string; good: string; note: string };
  quiz: Array<{ q: string; options: string[]; answer: number; explain: string }>;
};

export const B1_B2_DECK_SPECS: DeckSpec[] = [
  {
    slug: "b1-articulos-superlativos-cero",
    eyebrow: "B1 · Artículos",
    title: "Artículos con",
    emphasis: "superlativos y cero",
    goal: "Ya usas the con superlativos y omites el artículo con sustantivos abstractos o generales.",
    conceptRows: [
      { key: "Superlativo", value: "the + -est/most · the best student", highlights: ["the best"] },
      { key: "Único", value: "the sun, the president · cosas únicas", highlights: ["the"] },
      { key: "Artículo cero", value: "sin artículo · Life is hard.", highlights: ["Life"] },
      { key: "General plural", value: "Dogs are loyal. · categorías", highlights: ["Dogs"] },
    ],
    mistake: { bad: "She is best in class.", good: "She is the best in class.", note: "superlativo → the" },
    quiz: [{ q: "He is ___ tallest in the team.", options: ["the", "a"], answer: 0, explain: "Con superlativo va the." }],
  },
  {
    slug: "b1-modificadores-comparativos",
    eyebrow: "B1 · Comparativos",
    title: "Modificadores de",
    emphasis: "comparativos",
    goal: "Ya intensificas comparativos con much, far, a bit, a little y slightly.",
    conceptRows: [
      { key: "much / far", value: "much bigger · far more expensive", highlights: ["much", "far"] },
      { key: "a bit / a little", value: "a bit colder · a little easier", highlights: ["a bit"] },
      { key: "slightly", value: "slightly taller · matiz suave", highlights: ["slightly"] },
      { key: "even", value: "even better · énfasis extra", highlights: ["even"] },
    ],
    mistake: { bad: "She is more much taller.", good: "She is much taller.", note: "much va antes del comparativo, no con more" },
    quiz: [{ q: "This version is ___ better.", options: ["much", "more"], answer: 0, explain: "much + comparativo (-er o more)." }],
  },
  {
    slug: "b1-preposiciones-dependientes",
    eyebrow: "B1 · Preposiciones",
    title: "Preposiciones",
    emphasis: "dependientes",
    goal: "Ya eliges la preposición correcta tras adjetivos y verbos: depend on, good at, interested in.",
    conceptRows: [
      { key: "depend on", value: "depende de · It depends on the weather.", highlights: ["on"] },
      { key: "good at", value: "bueno en · She's good at maths.", highlights: ["at"] },
      { key: "interested in", value: "interesado en · interested in art", highlights: ["in"] },
      { key: "afraid of", value: "miedo a · afraid of spiders", highlights: ["of"] },
    ],
    mistake: { bad: "I'm interested on music.", good: "I'm interested in music.", note: "interested + in" },
    quiz: [{ q: "She's good ___ tennis.", options: ["at", "in"], answer: 0, explain: "good at + actividad." }],
  },
  {
    slug: "b1-futuro-continuo",
    eyebrow: "B1 · Futuro",
    title: "Futuro",
    emphasis: "continuo",
    goal: "Ya describes acciones en progreso en un momento futuro con will be + -ing.",
    conceptRows: [
      { key: "Forma", value: "will be + -ing · I will be working at 9.", highlights: ["will be working"] },
      { key: "Momento", value: "this time tomorrow · at 8 tonight", highlights: ["this time"] },
      { key: "Pregunta cortés", value: "Will you be using the car?", highlights: ["Will you be"] },
      { key: "Planes fijos", value: "acción ya prevista en curso", highlights: ["be + -ing"] },
    ],
    mistake: { bad: "I will work at 9 tomorrow.", good: "I will be working at 9 tomorrow.", note: "acción en curso en un punto futuro" },
    quiz: [{ q: "This time next week I ___ on a beach.", options: ["will be lying", "will lie"], answer: 0, explain: "Momento concreto futuro → continuo." }],
  },
  {
    slug: "b1-pasado-perfecto",
    eyebrow: "B1 · Pasado perfecto",
    title: "Pasado",
    emphasis: "perfecto",
    goal: "Ya ordenas dos acciones pasadas con had + participio para la más antigua.",
    conceptRows: [
      { key: "Forma", value: "had + participio · had left", highlights: ["had"] },
      { key: "Antes de otra", value: "When I arrived, he had left.", highlights: ["had left"] },
      { key: "Experiencia previa", value: "I had never seen snow before.", highlights: ["had never seen"] },
      { key: "Señal", value: "already, just, never, by the time", highlights: ["by the time"] },
    ],
    mistake: { bad: "When I arrived, he left already.", good: "When I arrived, he had already left.", note: "la salida fue antes de llegar" },
    quiz: [{ q: "She ___ the keys before she left.", options: ["had lost", "lost"], answer: 0, explain: "Perder las llaves fue antes de irse." }],
  },
  {
    slug: "b1-condicional-cero",
    eyebrow: "B1 · Condicional cero",
    title: "Condicional",
    emphasis: "cero",
    goal: "Ya expresas verdades generales y reglas con if + presente, presente.",
    conceptRows: [
      { key: "Estructura", value: "if + presente, presente · If you heat ice, it melts.", highlights: ["If you heat"] },
      { key: "Reglas", value: "scientific facts · general truths", highlights: ["melts"] },
      { key: "when", value: "When it rains, the streets get wet.", highlights: ["When"] },
      { key: "unless", value: "unless = if not · a menos que", highlights: ["unless"] },
    ],
    mistake: { bad: "If you will heat ice, it melts.", good: "If you heat ice, it melts.", note: "condicional cero: sin will tras if" },
    quiz: [{ q: "If water ___ to 100°C, it boils.", options: ["is heated", "will be heated"], answer: 0, explain: "Verdad general → presente en ambas partes." }],
  },
  {
    slug: "b1-both-either-neither",
    eyebrow: "B1 · Cuantificadores",
    title: "Both, either",
    emphasis: "y neither",
    goal: "Ya distingues both (los dos), either (uno u otro) y neither (ninguno de los dos).",
    conceptRows: [
      { key: "both", value: "los dos · Both answers are correct.", highlights: ["Both"] },
      { key: "either", value: "cualquiera de dos · Either option works.", highlights: ["Either"] },
      { key: "neither", value: "ninguno · Neither answer is right.", highlights: ["Neither"] },
      { key: "So do I", value: "So do I. / Neither do I. · acuerdo", highlights: ["So do I"] },
    ],
    mistake: { bad: "Both of them doesn't like it.", good: "Neither of them likes it.", note: "neither + singular" },
    quiz: [{ q: "___ of the two roads leads to the centre.", options: ["Neither", "Both"], answer: 0, explain: "Ninguna de las dos → neither." }],
  },
  {
    slug: "b1-make-let-allow",
    eyebrow: "B1 · Causa y permiso",
    title: "Make, let",
    emphasis: "y allow",
    goal: "Ya usas make/let + objeto + base y allow + objeto + to + infinitivo.",
    conceptRows: [
      { key: "make", value: "obligar · She made me wait.", highlights: ["made me wait"] },
      { key: "let", value: "permitir · Let me help you.", highlights: ["Let me"] },
      { key: "allow", value: "permitir (formal) · allow us to leave", highlights: ["allow us to"] },
      { key: "passive", value: "I was made to apologise.", highlights: ["was made to"] },
    ],
    mistake: { bad: "She let me to go.", good: "She let me go.", note: "let + objeto + verbo base, sin to" },
    quiz: [{ q: "My parents won't ___ me stay out late.", options: ["let", "allow"], answer: 0, explain: "let + objeto + base; allow llevaría to." }],
  },
  {
    slug: "b1-wish-presente",
    eyebrow: "B1 · Wish",
    title: "Wish + pasado",
    emphasis: "simple",
    goal: "Ya lamentas situaciones presentes con I wish + pasado simple.",
    conceptRows: [
      { key: "Presente irreal", value: "I wish I had more time.", highlights: ["had"] },
      { key: "Estado", value: "I wish I lived closer.", highlights: ["lived"] },
      { key: "were", value: "I wish it were warmer. · todas las personas", highlights: ["were"] },
      { key: "Contraste", value: "I don't have time → I wish I had time.", highlights: ["wish"] },
    ],
    mistake: { bad: "I wish I have more money.", good: "I wish I had more money.", note: "wish + pasado para presente irreal" },
    quiz: [{ q: "I wish I ___ speak French.", options: ["could", "can"], answer: 0, explain: "Deseo sobre el presente → pasado modal." }],
  },
  {
    slug: "b1-cuantificadores",
    eyebrow: "B1 · Cuantificadores",
    title: "All, most,",
    emphasis: "none, each, every",
    goal: "Ya usas all, most, none, each y every con concordancia correcta.",
    conceptRows: [
      { key: "all / most", value: "All students passed. · Most people agree.", highlights: ["All", "Most"] },
      { key: "none", value: "None of them is ready. · singular", highlights: ["None"] },
      { key: "each", value: "each + singular · Each child has a book.", highlights: ["Each"] },
      { key: "every", value: "every + singular · every day", highlights: ["every"] },
    ],
    mistake: { bad: "Every students have a book.", good: "Every student has a book.", note: "every/each + singular" },
    quiz: [{ q: "___ of the cake is gone.", options: ["None", "All"], answer: 0, explain: "None of + singular cuando el sustantivo es incontable." }],
  },
  {
    slug: "b2-conectores-avanzados",
    eyebrow: "B2 · Conectores",
    title: "Conectores",
    emphasis: "avanzados",
    goal: "Ya enlazas ideas formales con however, furthermore, therefore y nevertheless.",
    conceptRows: [
      { key: "however", value: "contraste · However, the plan failed.", highlights: ["However"] },
      { key: "furthermore", value: "añadir · Furthermore, costs rose.", highlights: ["Furthermore"] },
      { key: "therefore", value: "consecuencia · Therefore, we postponed.", highlights: ["Therefore"] },
      { key: "nevertheless", value: "a pesar de · Nevertheless, we continued.", highlights: ["Nevertheless"] },
    ],
    mistake: { bad: "However it was late, but we stayed.", good: "However, it was late, so we left.", note: "no mezcles however con but" },
    quiz: [{ q: "Costs rose; ___, we raised prices.", options: ["therefore", "although"], answer: 0, explain: "Consecuencia lógica → therefore." }],
  },
  {
    slug: "b2-oraciones-hendidas",
    eyebrow: "B2 · Énfasis",
    title: "Oraciones",
    emphasis: "hendidas",
    goal: "Ya destacas información con it-cleft y what-cleft.",
    conceptRows: [
      { key: "It-cleft", value: "It was John who called.", highlights: ["It was John who"] },
      { key: "What-cleft", value: "What I need is a break.", highlights: ["What I need is"] },
      { key: "Énfasis", value: "resalta sujeto, objeto o adverbio", highlights: ["who", "what"] },
      { key: "All-cleft", value: "All I want is peace.", highlights: ["All I want"] },
    ],
    mistake: { bad: "It was John called me.", good: "It was John who called me.", note: "it-cleft necesita who/that" },
    quiz: [{ q: "___ I can't stand is the noise.", options: ["What", "That"], answer: 0, explain: "What-cleft: What + cláusula + is/was." }],
  },
  {
    slug: "b2-concesion",
    eyebrow: "B2 · Concesión",
    title: "Even though,",
    emphasis: "while y whereas",
    goal: "Ya contrastas ideas con even though, while y whereas.",
    conceptRows: [
      { key: "even though", value: "aunque (énfasis) · Even though it rained…", highlights: ["Even though"] },
      { key: "while", value: "mientras / aunque · While I agree…", highlights: ["While"] },
      { key: "whereas", value: "mientras que (contraste) · whereas he prefers tea", highlights: ["whereas"] },
      { key: "Posición", value: "pueden ir al inicio o en medio", highlights: ["Even though"] },
    ],
    mistake: { bad: "Even though it was late, but we stayed.", good: "Even though it was late, we stayed.", note: "no uses but con even though" },
    quiz: [{ q: "___ he is rich, he lives simply.", options: ["Whereas", "Because"], answer: 0, explain: "Contraste entre dos hechos → whereas." }],
  },
  {
    slug: "b2-conectores-condicionales",
    eyebrow: "B2 · Condicionales",
    title: "Unless, provided",
    emphasis: "y as long as",
    goal: "Ya matizas condiciones con unless, provided (that) y as long as.",
    conceptRows: [
      { key: "unless", value: "a menos que (= if not) · unless you hurry", highlights: ["unless"] },
      { key: "provided (that)", value: "siempre que · provided you pay", highlights: ["provided"] },
      { key: "as long as", value: "mientras / con tal de que · as long as you're happy", highlights: ["as long as"] },
      { key: "in case", value: "por si acaso · take an umbrella in case", highlights: ["in case"] },
    ],
    mistake: { bad: "Unless you will not hurry…", good: "Unless you hurry…", note: "unless ya implica negación" },
    quiz: [{ q: "You can go out ___ you finish your homework.", options: ["as long as", "unless"], answer: 0, explain: "Condición positiva → as long as." }],
  },
  {
    slug: "b2-enfasis-auxiliares",
    eyebrow: "B2 · Énfasis",
    title: "Do/does/did",
    emphasis: "de énfasis",
    goal: "Ya enfatizas con auxiliares do/does/did en afirmaciones.",
    conceptRows: [
      { key: "do/does", value: "I do agree. · She does know.", highlights: ["do agree", "does know"] },
      { key: "did", value: "I did tell you! · pasado", highlights: ["did tell"] },
      { key: "Contraste", value: "I like it → I do like it (énfasis)", highlights: ["do"] },
      { key: "Pronunciación", value: "el auxiliar lleva el acento", highlights: ["do"] },
    ],
    mistake: { bad: "I do likes it.", good: "I do like it.", note: "tras do/does/did va la base del verbo" },
    quiz: [{ q: "She ___ want to come, honestly.", options: ["does", "is"], answer: 0, explain: "Énfasis en presente → does + base." }],
  },
  {
    slug: "b2-gerundio-significado",
    eyebrow: "B2 · Gerundio vs infinitivo",
    title: "Cambio de",
    emphasis: "significado",
    goal: "Ya distingues remember/stop/try con -ing o to según el significado.",
    conceptRows: [
      { key: "stop + -ing", value: "dejar de · stop smoking", highlights: ["stop smoking"] },
      { key: "stop + to", value: "parar para · stop to rest", highlights: ["stop to rest"] },
      { key: "remember + -ing", value: "recordar hecho pasado · remember meeting her", highlights: ["remember meeting"] },
      { key: "remember + to", value: "no olvidar · remember to call", highlights: ["remember to call"] },
    ],
    mistake: { bad: "I stopped to smoke.", good: "I stopped smoking.", note: "dejar el hábito → stop + -ing" },
    quiz: [{ q: "Remember ___ the door when you leave.", options: ["to lock", "locking"], answer: 0, explain: "Acción futura que no debes olvidar → to." }],
  },
  {
    slug: "b2-condicionales-mixtos",
    eyebrow: "B2 · Condicionales",
    title: "Condicionales",
    emphasis: "mixtos",
    goal: "Ya combinas tiempos en condicionales mixtos (pasado → presente, etc.).",
    conceptRows: [
      { key: "Pasado → presente", value: "If I had studied, I would have a better job now.", highlights: ["had studied", "would have"] },
      { key: "Presente → pasado", value: "If I were taller, I would have joined the team.", highlights: ["were", "would have"] },
      { key: "Idea", value: "condición en un tiempo, resultado en otro", highlights: ["If"] },
      { key: "Señal", value: "now, then, at the time", highlights: ["now"] },
    ],
    mistake: { bad: "If I studied harder, I would have passed.", good: "If I had studied harder, I would have passed.", note: "arrepentimiento pasado → past perfect" },
    quiz: [{ q: "If I ___ the train, I would be there now.", options: ["had caught", "caught"], answer: 0, explain: "Condición pasada, resultado presente → had + pp." }],
  },
  {
    slug: "b2-relativas-no-definitorias",
    eyebrow: "B2 · Relativas",
    title: "Cláusulas",
    emphasis: "explicativas",
    goal: "Ya usas oraciones de relativo no definitorias con comas y who/which.",
    conceptRows: [
      { key: "Comas", value: "My brother, who lives in Rome, …", highlights: [","] },
      { key: "Información extra", value: "no define; solo añade detalle", highlights: ["who"] },
      { key: "which", value: "The book, which I bought yesterday, …", highlights: ["which"] },
      { key: "that", value: "no se usa that en no definitorias", highlights: ["which"] },
    ],
    mistake: { bad: "My brother that lives in Rome…", good: "My brother, who lives in Rome,…", note: "información extra → comas + who" },
    quiz: [{ q: "London, ___ I visited last year, is huge.", options: ["which", "that"], answer: 0, explain: "No definitoria → which entre comas." }],
  },
  {
    slug: "b2-pasiva-reportada",
    eyebrow: "B2 · Pasiva",
    title: "Reportaje",
    emphasis: "pasivo",
    goal: "Ya reportas con It is said that… y subject + is said to + infinitivo.",
    conceptRows: [
      { key: "It is said that", value: "It is said that he is rich.", highlights: ["It is said that"] },
      { key: "is said to", value: "He is said to be rich.", highlights: ["is said to be"] },
      { key: "Otros verbos", value: "is believed/reported/known to", highlights: ["is believed"] },
      { key: "Impersonal", value: "no se dice quién reporta", highlights: ["It is"] },
    ],
    mistake: { bad: "People say that he is rich.", good: "He is said to be rich.", note: "estilo más formal e impersonal" },
    quiz: [{ q: "The artist ___ to live abroad.", options: ["is said", "says"], answer: 0, explain: "Reportaje pasivo → is said to." }],
  },
  {
    slug: "b2-pasiva-completa",
    eyebrow: "B2 · Pasiva",
    title: "Pasiva en",
    emphasis: "todos los tiempos",
    goal: "Ya formas la voz pasiva en todos los tiempos verbales comunes.",
    conceptRows: [
      { key: "Presente", value: "is/are + pp · is made", highlights: ["is made"] },
      { key: "Pasado", value: "was/were + pp · was built", highlights: ["was built"] },
      { key: "Perfecto", value: "has been + pp · has been done", highlights: ["has been"] },
      { key: "Modales", value: "can be + pp · must be finished", highlights: ["can be"] },
    ],
    mistake: { bad: "The house was build in 1990.", good: "The house was built in 1990.", note: "pasiva → participio pasado" },
    quiz: [{ q: "The report ___ by Friday.", options: ["must be finished", "must finish"], answer: 0, explain: "Obligación pasiva → must be + pp." }],
  },
  {
    slug: "b2-relativas-preposiciones",
    eyebrow: "B2 · Relativas",
    title: "Relativas con",
    emphasis: "preposiciones",
    goal: "Ya colocas preposiciones al final o antes del relativo en estilo formal.",
    conceptRows: [
      { key: "Al final", value: "the person I spoke to · informal", highlights: ["spoke to"] },
      { key: "Formal", value: "the person to whom I spoke", highlights: ["to whom"] },
      { key: "whose", value: "the student whose essay won", highlights: ["whose"] },
      { key: "quantifiers", value: "many of whom, most of which", highlights: ["of whom"] },
    ],
    mistake: { bad: "the person to who I spoke", good: "the person who I spoke to", note: "who no lleva preposición delante en uso cotidiano" },
    quiz: [{ q: "The colleagues ___ I work with are great.", options: ["who/that", "whose"], answer: 0, explain: "Sujeto/objeto de la relativa → who/that." }],
  },
  {
    slug: "b2-oraciones-resultado",
    eyebrow: "B2 · Resultado",
    title: "So/such",
    emphasis: "… that",
    goal: "Ya expresas resultado con so + adj/adv + that y such + (a) + sustantivo + that.",
    conceptRows: [
      { key: "so + adj", value: "so tired that I fell asleep", highlights: ["so tired that"] },
      { key: "such + noun", value: "such a mess that…", highlights: ["such a"] },
      { key: "so many/much", value: "so many people that…", highlights: ["so many"] },
      { key: "Resultado", value: "that + cláusula de consecuencia", highlights: ["that"] },
    ],
    mistake: { bad: "It was so a long day.", good: "It was such a long day.", note: "such + sustantivo; so + adjetivo" },
    quiz: [{ q: "It was ___ cold that we stayed inside.", options: ["so", "such"], answer: 0, explain: "so + adjetivo (cold)." }],
  },
  {
    slug: "b2-verbo-objeto-gerundio",
    eyebrow: "B2 · Patrones verbales",
    title: "Verbo + objeto",
    emphasis: "+ -ing / to",
    goal: "Ya usas patrones como want someone to, catch someone -ing y persuade someone to.",
    conceptRows: [
      { key: "want/expect + obj + to", value: "I want you to try.", highlights: ["want you to"] },
      { key: "catch/find + obj + -ing", value: "I caught him lying.", highlights: ["caught him lying"] },
      { key: "persuade/convince", value: "persuade her to stay", highlights: ["persuade her to"] },
      { key: "see/hear + obj + base/-ing", value: "I saw her leave / leaving", highlights: ["saw her"] },
    ],
    mistake: { bad: "I want that you help me.", good: "I want you to help me.", note: "want + objeto + to, no that" },
    quiz: [{ q: "She persuaded me ___ the job.", options: ["to accept", "accepting"], answer: 0, explain: "persuade + objeto + to + infinitivo." }],
  },
  {
    slug: "b2-despite-in-spite",
    eyebrow: "B2 · Concesión",
    title: "Despite /",
    emphasis: "in spite of",
    goal: "Ya contrastas con despite/in spite of + sustantivo o -ing (no cláusula con verbo conjugado).",
    conceptRows: [
      { key: "despite", value: "despite the rain · + sustantivo/-ing", highlights: ["despite"] },
      { key: "in spite of", value: "in spite of the delay", highlights: ["in spite of"] },
      { key: "although", value: "although it rained · + cláusula", highlights: ["although"] },
      { key: "Contraste", value: "despite ≠ although en estructura", highlights: ["despite", "although"] },
    ],
    mistake: { bad: "Despite it rained…", good: "Despite the rain… / Although it rained…", note: "despite + sustantivo, no oración completa" },
    quiz: [{ q: "___ the weather, we went out.", options: ["Despite", "Although"], answer: 0, explain: "Tras despite va sustantivo (the weather)." }],
  },
];
