/**
 * Discriminated-union types for a CEFR "resource pack" — the bundle a learner
 * can download once (Essential Words + grammar decks + their audio + an
 * optional Coach content-bank slice) to study a whole level offline.
 *
 * Step 1 (Plan 057) only defines these types and generates the Essential
 * Words resource files + manifest. `resource-pack-manager.ts` (Step 3) reads
 * this manifest at download time; nothing here talks to CacheStorage or
 * Dexie yet.
 *
 * Registry-style discriminated union on `kind`, per ENGINEERING_STANDARDS.md
 * ("Many variants → registry + type guard, not long if/switch chains").
 */

import type { CefrLevel } from "@/lib/essential-words/types";

/** No C2 pack exists yet (Product contract, "Política C2"). */
export const OFFLINE_PACK_LEVELS: readonly CefrLevel[] = ["A1", "A2", "B1", "B2", "C1"] as const;

/** Site-relative URL of the generated manifest; also its key inside each pack cache. */
export const OFFLINE_PACK_MANIFEST_URL = "/offline-packs/manifest.json";

/** Bumped whenever this manifest's on-disk shape changes (not its content). */
export const OFFLINE_PACK_SCHEMA_VERSION = 1;

/**
 * Bumped whenever a *required* generated resource changes (new/edited words,
 * a grammar deck edit, a new audio file). A plain, hand-maintained string
 * (not a content hash) so a diff of this file is the changelog, matching the
 * plan's maintenance note: "Subir contentVersion cuando cambie un recurso
 * requerido." `scripts/offline-packs/generate.mjs` stamps every generated
 * file and the manifest with this same value so `validate.mjs` can catch a
 * stale/partial regeneration.
 */
export const OFFLINE_PACK_CONTENT_VERSION = "v1";

/** Ground truth for `scripts/offline-packs/validate.mjs` (Plan 057 "Current state"). */
export const EXPECTED_UNIQUE_WORD_COUNTS: Record<CefrLevel, number> = {
  A1: 740,
  A2: 645,
  B1: 523,
  B2: 752,
  C1: 137,
};

export const EXPECTED_TOTAL_UNIQUE_WORDS = 2797;

export type OfflinePackResourceKind =
  | "essential-words"
  | "grammar-deck"
  | "audio"
  | "coach-content-bank";

interface OfflinePackResourceBase {
  /** URL path (site-relative, starts with "/") the resource is fetched from. */
  url: string;
  /** Size on disk in bytes, measured at generation time. */
  estimatedBytes: number;
}

/** The level's Essential Words JSON, filtered + deduped for this level only. */
export interface EssentialWordsPackResource extends OfflinePackResourceBase {
  kind: "essential-words";
  wordCount: number;
}

/** One `public/grammar-decks/<slug>.json` belonging to this level's course path. */
export interface GrammarDeckPackResource extends OfflinePackResourceBase {
  kind: "grammar-deck";
  slug: string;
  /** Curriculum lesson title, shown in the offline hub's study list. */
  title: string;
  /** Curriculum lesson number within the level's track (progress crediting). */
  lessonNumber: number;
}

/**
 * A shared IPA sound clip (`public/sounds/*.ogg`) referenced by one of the
 * level's grammar decks (`deck.sounds` or a `pronunciation` block's `sound`).
 * Shared across levels — a given audio file may be listed by more than one
 * level's manifest entry, so downloading two packs does not double the file
 * on disk (same CacheStorage URL, cached once).
 */
export interface AudioPackResource extends OfflinePackResourceBase {
  kind: "audio";
  /** Bare IPA symbol this clip illustrates (IPA_AUDIO_MAP key). */
  ipaSymbol: string;
}

/**
 * Up to 100 pregenerated Coach exercises for this level (Product contract,
 * item 4). Never generated by `scripts/offline-packs/generate.mjs` — Step 3
 * downloads it live from the remote content bank per device, so it has no
 * on-disk file and no stable `estimatedBytes` until then. The type exists
 * now so the manifest shape does not change again in Step 3.
 */
export interface CoachContentBankPackResource {
  kind: "coach-content-bank";
  level: CefrLevel;
  /** Product contract cap. */
  maxExercises: number;
}

export type OfflinePackResource =
  | EssentialWordsPackResource
  | GrammarDeckPackResource
  | AudioPackResource
  | CoachContentBankPackResource;

export function isEssentialWordsResource(
  resource: OfflinePackResource
): resource is EssentialWordsPackResource {
  return resource.kind === "essential-words";
}

export function isGrammarDeckResource(
  resource: OfflinePackResource
): resource is GrammarDeckPackResource {
  return resource.kind === "grammar-deck";
}

export function isAudioResource(resource: OfflinePackResource): resource is AudioPackResource {
  return resource.kind === "audio";
}

export function isCoachContentBankResource(
  resource: OfflinePackResource
): resource is CoachContentBankPackResource {
  return resource.kind === "coach-content-bank";
}

/**
 * One CEFR level's downloadable pack. `required` must all be present for the
 * receipt to become `ready` (Step 2/3); `optional` — today just the Coach
 * content-bank placeholder — may fail without invalidating the pack.
 */
export interface OfflinePackManifestEntry {
  schemaVersion: number;
  contentVersion: string;
  level: CefrLevel;
  estimatedBytes: number;
  required: OfflinePackResource[];
  optional: OfflinePackResource[];
}

export interface OfflinePackManifest {
  schemaVersion: number;
  contentVersion: string;
  generatedAt: string;
  levels: OfflinePackManifestEntry[];
}
